### ISSUE TITLE
no output of Header Extra Class[tx_t3sbootstrap_header_class] in CType background_wrapper

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#101]
I miss the output of Header Extra Class[tx_t3sbootstrap_header_class] in CType background_wrapper

Tried to debug {header} in \Partials\Content\Header\All.html with set [tx_t3sbootstrap_header_class] = text-white
```
   class => '' (0 chars)
   hClass => '' (0 chars)
```
For other CTypes (textmedia) this is correct

Whats the difference between header.class and header.hclass and why are they missing?

t3sbootstrap 4.5.6
TYPO3 10.4.14

**Comment by t3solution** [comment]
In my test environment it works as expected.
@Info:
- header.class target to the <header> tag
- header.hclass is target to the <h> tag

**Comment by t3solution** [comment]
...

    header.class target to the "header" tag
    header.hclass is target to the "h" tag

**Comment by t3solution** [comment]
New version 5 - new issues!
