### ISSUE TITLE
translated accordion items not clickable

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#105]
translated accordion items are not clickable because parent element is not found => JS error

```<div id="accordion-3808 [Original-ID]" ``` and  ```<div id="collapse-3810" class="collapse" data-parent="#accordion-3821 [Translated-ID]">``` can not work together

source of a translated page:

```
<div id="c3808"> [Original-ID]
  <div class="fsc-default ce-collapsible_container">
    <div id="accordion-3808 [Original-ID]" class="collapsible-accordion" role="tablist">
      <div class="card">
        <a data-toggle="collapse" href="#collapse-3810 [Original-ID]" aria-expanded="false" aria-controls="collapse-3810" style="display: block;">
          <div class="card-header fsc-default ce-collapsible_accordion" id="heading-3810 [Original-ID]"><h5 class="mb-0">HEADER</h5</div>
        </a>
        <div id="collapse-3810" class="collapse" role="tabpanel" aria-labelledby="heading-3810 [Original-ID]" data-parent="#accordion-3821 [Translated-ID]"><div class="card-body"></div></div>
      </div>
... next card ...
```

Shouldn't instead of  [Original-ID] always [Translated-ID] be used?

**Comment by t3solution** [comment]
Unfortunately, I cannot understand that behavior.
In my dev-installation it works as expected!

**Comment by peerlight** [comment]
in newly generated tests this works

translated content with error was from old TYPO3 and old t3sbootstrap. 

so there are probably conversion errors - mainly in setting tx_container_parent of collapsible_accordion to the value of tx_gridelement_parent and not to the uid of the original collapsible_container

**Comment by t3solution** [comment]
New version 5 - new issues!
