### ISSUE TITLE
[Feature Request] Support of extension content_animations (aos on scroll library)

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#106]
I usually use animate css in the templates because is simple programming, but recently I started to use the [aos on scroll library](https://michalsnik.github.io/aos/) and its typo3 extension "[content_animations](https://docs.typo3.org/p/baschte/content-animations/2.1/en-us/Introduction/Index.html)" Because you can create a much better user experience with the scrolling triggers of the websites, since it has scroll-in, scroll-out and anchors for the animations.

I've started to integrate it in some of your templates, but I fear I'll have a lot of work every time you update t3sbootstrap. So, I was wondering if it would be possible to integrate this extension in the templates.

It only needs that the snippet is included in the outer html tag of the content elements. This will add all the necessary attributes and settings to the html tag.

``{f:if(condition: animationSettings, then: '{animationSettings -> f:format.raw()}')}``

**Comment by t3solution** [comment]
New version 5 - new issues!
