### ISSUE TITLE
How to change tab title?

### ISSUE THREAD

**Issue by fxp66** [t3solution/t3sbootstrap#107]
How can I change the browser tab title from e.g. "t3sbootstrap : bootstrap-komponenten" to "bootstrap-komponenten | t3sbootstrap  "?
Can't find correct typoscript for vers. 4.5.4

thx for reply

**Comment by t3solution** [comment]
You can do this as follows (for example):

```
page.config.noPageTitle = 2
page.headerData.66 = TEXT
page.headerData.66.field = title // subtitle
page.headerData.66.noTrimWrap = |<title>| &#921; Seitentitel</title>|
```

But that has nothing to do with t3sbootstrap!

**Comment by fxp66** [comment]
Excuse me for asking silly questions, you're absolute wright.
... I have do think twice before opening threads.

But thank you for answering, and thanks for the great extension!
