### ISSUE TITLE
jquery in footerlibs?

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#11]
just a temporary comment. But you cannot use a $() nowhere, if it is loaded in footerLibs. Maybe forceToTop or not. I'd position it in includeJsLibs. This is for normal and print TS.

**Comment by t3solution** [comment]
I include an option to load jquery into the header:
https://github.com/t3solution/t3sbootstrap/commit/e59a2a09f6dc5218e35fabd4481951d9c6a78a12
false: https://github.com/t3solution/t3sbootstrap/commit/0871d44d0a8d49ff2c8dc394003486c402211e3e
false fix: https://github.com/t3solution/t3sbootstrap/commit/9385621cf02f955f12a8dfff314a44ff744ac5e1

**Comment by t3solution** [comment]
... and a bugfix: https://github.com/t3solution/t3sbootstrap/commit/d4a025492248ec1c7be8b958e8056a2986232eb3

**Comment by TrueType** [comment]
great
