### ISSUE TITLE
Carousel after Patch 4.5.7 and webp

### ISSUE THREAD

**Issue by jStepo** [t3solution/t3sbootstrap#110]
Typo3 10.4.16
Custom Templates and Partials are off

**Carousel settings:**

![Carousel-settings](https://user-images.githubusercontent.com/29541947/119114738-b39f0980-ba26-11eb-8ed1-5ed351cab0a4.jpg)

**I'm getting following error message:**

![Error](https://user-images.githubusercontent.com/29541947/119114993-f8c33b80-ba26-11eb-8b12-69d76548a184.jpg)

If the image ratio field is empty then it works fine but now the webp extension doesn't work for the slider anymore.

In the version 4.5.6 I had to approximate the image ratio (Example: Image with 1920x1024 ----> ratio 19:10) and set it in the 
image ratio field in order to get webp inside the slider working, 

I have also tried all variations with "bootstrap.image.ratioWithHeight = 1/0" and "Use Original Image".

**Comment by CarstenHager** [comment]
try:

https://github.com/t3solution/t3sbootstrap/commit/3fcc7ff277fd7e1347566a878920136f8b3c78bb

**Comment by t3solution** [comment]
This issue already fixed:
https://github.com/t3solution/t3sbootstrap/commit/3fcc7ff277fd7e1347566a878920136f8b3c78bb

**Comment by jStepo** [comment]
Thank you for your quick response!

Now i can set the ratio but webp is still ignoring the images inside the "Bootstrap Carousel Item".
![test2](https://user-images.githubusercontent.com/29541947/119124110-996a2900-ba30-11eb-88f3-e8313355775d.jpg)


and here on the same page:
![test](https://user-images.githubusercontent.com/29541947/119123969-72135c00-ba30-11eb-9797-71cfdd0594e8.jpg)

**Comment by jStepo** [comment]
Also already fixed -_- 
[https://github.com/t3solution/t3sbootstrap/commit/70c67b5b82faf094fc321dcfa8505611ce6f8490](url)
