### ISSUE TITLE
Media adjustments not working properly

### ISSUE THREAD

**Issue by MVolontar** [t3solution/t3sbootstrap#112]
I'm developing a website in typo3, using your 4.5.6 t3sbootstrap and I'm having some problems with media adjustment in page edit.

When I add an image to a page and set its width and height, the values I put in do not take affect in FE. With some images the values do take affect but only to some specific value (different for every image) and if I set the width or height just over that, the image blows out of proportion (out of main container) to its full size. I tried to follow extension setup process on https://www.t3sbootstrap.de/ but with no luck. Also I tried to alter constant editor and extension configuration.

![ma](https://user-images.githubusercontent.com/44176749/119639798-3d304c00-be18-11eb-9118-2b84f34c316e.png)

I think I'm doing something wrong, but I have no idea what. Does someone have any ideas? Thank you!

Cheers, Matija

**Comment by t3solution** [comment]
I don't understand your question. 
There is no media adjustment when editing pages.

**Comment by MVolontar** [comment]
I'm sorry. I meant content element. This is a screenshot after clicking on content element to edit it. It is the same as here: https://www.t3sbootstrap.de/dokumentation/image-rendering

![ma](https://user-images.githubusercontent.com/44176749/119652729-c484bc00-be26-11eb-96a3-9a1a9537a7de.jpg)

**Comment by t3solution** [comment]
In my dev-installation it works as expected!
What settings do you have under "edit page" for backend layout & container?
Is your site online?

**Comment by MVolontar** [comment]
Below are settings used under "edit page".
![aa](https://user-images.githubusercontent.com/44176749/119693394-85696180-be4c-11eb-8464-0502123d97ba.png)

Yes, my developing site is online and avalible here: https://www.dev.kulturarchiv.ch/kulturarchiv-oberengadin
The old site, which is running on typo3 7.6 is avalible here: https://www.kulturarchiv.ch/index.php?id=39

So basicly, DEV site is a copy of the old one, but typo3 updated to 10.4.14. I would like to have the same options for image manipulation as I have on the old site - this is where I'm stuck. The image manipulation just doesn't work properly in my case. What else effects image manipulation that I can check and make sure that it is in order?

Thank you for you time!

**Comment by t3solution** [comment]
The class "img-fluid" is missing in the img-tag.
This is usually set by default!

**Comment by MVolontar** [comment]
Aha ok. Thanks!
How would you suggest to add "img-fluid" class to the img tag? I tried appending it by using "Extra class" field but it doesn't work. Even if I choose something from the dropdown, it doesn't work. Do I have to enable something in the extension settings or constant editor?

![aa](https://user-images.githubusercontent.com/44176749/119778713-221d1500-bec8-11eb-9d95-1f5ba65b4cca.png)

**Comment by t3solution** [comment]
As I said, this is usually set by default!
You probably don't use the original template.
Make a debug in the template and look for a variable {addmedia.imgclass}!
Compare it with this template: https://github.com/t3solution/t3sbootstrap/blob/master/Resources/Private/Partials/Content/Media/Rendering/Image.html

**Comment by MVolontar** [comment]
Well, I installed this template through extension menager. I would expect that it is original. I also updated the template to 4.5.7 and installed Container Content Elements + Content Defender.

`<f:debug title="Results">{addmedia.imgclass}</f:debug>` returned "NULL".
I compared the file Image.html on git with my version and they are identical.

Do you think it would be a good idea, to just overwrite my files with files from this Git? Could it be that there is something wrong with the way things in constant editor or extension setting are set up? Thank you!

**Comment by t3solution** [comment]
I can only guess!
It would be easiest if you give me admin-access to BE (by email).

**Comment by t3solution** [comment]
New version 5 - new issues!
