### ISSUE TITLE
use of image ratio and bootstrap carousel throws error

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#113]
10.4.16 / t3s 4.5.7 - use of image ratio and bootstrap carousel throws error
![ratio-bs-carousel](https://user-images.githubusercontent.com/47745128/119944439-8f967780-bf94-11eb-8ca6-daa1d4254550.png)
![image](https://user-images.githubusercontent.com/47745128/119944541-b18ffa00-bf94-11eb-9ad1-203f051186a8.png)

**Comment by t3solution** [comment]
Here is the bugfiy: https://github.com/t3solution/t3sbootstrap/commit/3fcc7ff277fd7e1347566a878920136f8b3c78bb

**Comment by asche76** [comment]
very nice, works, thank you)

**Comment by t3solution** [comment]
New version 5 - new issues!
