### ISSUE TITLE
Update 454 -> 460 + t3 10  Scheduler Task error

### ISSUE THREAD

**Issue by rimmeh** [t3solution/t3sbootstrap#117]
Hi,

i upgraded from T3 9 to 10 + T3s from 4.5.4 to 4.6.0. Everything worked good except one error with cdnToLocal Scheduler Task.

In BAckend:
`

Die  Klasse %s des registrierten Tasks konnte nicht gefunden werden. Sie  sollten die Erweiterung, die den Task zur Verfügung stellt,  neuinstallieren oder den Task löschen.
--

                    
ID | Task | &nbsp;
-- | -- | --
1 | T3SBS\T3sbootstrap\Tasks\CdnToLocal

`

But when i try to delete it, an new Error occurs:

Fatal error: TYPO3\CMS\Scheduler\Scheduler::fetchTask(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "T3SBS\T3sbootstrap\Tasks\CdnToLocal" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /var/customers/webs/guv/typo3/sysext/scheduler/Classes/Scheduler.php on line 349 

Any Suggestions?

Regards

**Comment by t3solution** [comment]
New version 5 - new issues!
