### ISSUE TITLE
Card sizes for decks with multiple card wrappers on a page

### ISSUE THREAD

**Issue by schnere** [t3solution/t3sbootstrap#118]
If someone uses multiple card on a single page the amount of cards in the last card wrapper is responsible for the card size on the whole page when using decks.

Source: https://github.com/t3solution/t3sbootstrap/blob/c697a89f74d8cf4816a1fcbf10e918ec78943454/Classes/DataProcessing/GalleryProcessor.php#L372

The inline style get's overwritten by each new call so that only the last one takes effect.
So one option would be to set an id (or id class) for every card deck and add the inline style for each deck separately.
Another (in my opinion more useful) option would be to provide a backend option to set the card size. Furthermore it would be nice to provide an ability to overwrite the size for single cards.

**Comment by t3solution** [comment]
New version 5 - new issues!
