### ISSUE TITLE
header extra class and p as header not working

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#119]
header extra class and p as header not working in frontend output. instead of p the default header will be used as fe output.
![no-header-class](https://user-images.githubusercontent.com/47745128/123259272-957c6b80-d4f4-11eb-957d-e955d8966eac.png)
![no-header-class-be](https://user-images.githubusercontent.com/47745128/123259285-9a411f80-d4f4-11eb-9c09-038d22fc5531.png)
![no-p-header](https://user-images.githubusercontent.com/47745128/123259307-9dd4a680-d4f4-11eb-9c94-072227a27f05.png)

**Comment by t3solution** [comment]
I can't understand that, it works as expected for me!

**Comment by t3solution** [comment]
New version 5 - new issues!
