### ISSUE TITLE
tx_t3sbootstrap_header_class is a bit missleading

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#12]
tx_t3sbootstrap_header_class is applied to tag "hx" in "header" not to .subheader

so you can't use it to have space between the "header" (with header, subheader, date) and bodytext

Just noticed this. No idea how to solve this without breaking existing sites.

**Comment by t3solution** [comment]
I found a better solution for "header class" if using subheader:
https://github.com/t3solution/t3sbootstrap/commit/f7fa5119113b5229a6de18327a9a4e9d2a14f64e

**Comment by t3solution** [comment]
... and: https://github.com/t3solution/t3sbootstrap/commit/88d8b7c21410e13672793018f3aa028c27720aa7

**Comment by t3solution** [comment]
improvement was implemented
