### ISSUE TITLE
images are rendered too small in cards

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#120]
using TYPO3 9.5.x, t3sbootstrap 4.5.3 the images in cards (in card-deck) are rendered far too small - like 99px and scaled up in broweser

did some debugging and found out
- {card.dimensions} in FLUID are both 0
- tx_t3sbootstrap_inTextImgRowWidth is auto (standard for new items)
- images in cards with tx_t3sbootstrap_inTextImgRowWidth other than "auto" are large enough
- "Disable auto row" is 1; switching around does not change anything (for cards)

workaround
- use TCEFORM.tt_content.tx_t3sbootstrap_inTextImgRowWidth.types.t3sbs_card.disabled = 0 to make setting visible
- set value other than "auto" manually

How to get images in cards to a normal size without any tricks?

**Comment by t3solution** [comment]
New version 5 - new issues!
