### ISSUE TITLE
Collapsible not working on translated page

### ISSUE THREAD

**Issue by schnere** [t3solution/t3sbootstrap#121]
The collapsible headers are not clickable on translated pages. The reason is that the header links to the localized uid but in the container itself the main uid is set.

A quick fix for me was to use the localized uid for the container, too:
I replaced `data.uid` with `data._LOCALIZED_UID` if set:
https://github.com/t3solution/t3sbootstrap/blob/dc244f1d908af0166a00e2e81417696dcb992eab/Resources/Private/Templates/Container/CollapsibleContainer.html#L59

```
<div id="accordion-{f:if(condition: '{data._LOCALIZED_UID}', then: '{data._LOCALIZED_UID}', else: '{data.uid}')}" class="collapsible-accordion" role="tablist">
```

**Comment by t3solution** [comment]
New version 5 - new issues!
