### ISSUE TITLE
Image elements do not have explicit width and height

### ISSUE THREAD

**Issue by max951** [t3solution/t3sbootstrap#122]
TYPO3 10.4.18 
t3sbootstrap 4.6.0

No error, but a "should have" request.

Lighthouse keeps telling me that "Image elements do not have explicit width and height"
( https://developers.google.com/speed/pagespeed/insights/ )

Reason: The fallback img tag in picture has only a width but no height value

I think it is possible to get a better ranking in Google search, if the specification of width AND height is explicit specified.

I added two lines in file
Classes/Utility/ResponsiveImagesUtility.php

after line 107
```
107     $referenceWidth = $fallbackImage->getProperty('width');
+       $referenceHeight = $fallbackImage->getProperty('height');
```

and after line
```
160     $fallbackTag->addAttribute('width', $referenceWidth);
+       $fallbackTag->addAttribute('height', $referenceHeight);
```

This worked for me and PageSpeedInsights goes from 78 to 95

**Comment by t3solution** [comment]
New version 5 - new issues!
