### ISSUE TITLE
translate/copy content in containers e.g. four_columns not possible

### ISSUE THREAD

**Issue by ulrich4** [t3solution/t3sbootstrap#124]
I'm not be able to copy content in a container from one language to another.
I click on the button "Translate", choose "Copy", follow the steps and nothing occurres.
Tested with TYPO3 10.4.15 and 10.4.18, t3sbootsrap 4.6.1
![Bildschirmfoto_2021-07-23_14-31-44](https://user-images.githubusercontent.com/87861145/126782231-427900df-45d6-4cd5-99e5-60ca9248a1ac.png)

**Comment by t3solution** [comment]
New version 5 - new issues!
