### ISSUE TITLE
Translating/copying of T3SB containers / wrappers failed.

### ISSUE THREAD

**Issue by joergwiedemann** [t3solution/t3sbootstrap#125]
Trying to translate complete content for another language fails, when boostrap containers on the page. With origin T3 Ce like text its ok. I think it the same issue like #124. "Verarbeitung läuft", but nothings happens. Its a little bit urgent. Or have i to do a downgrade? Jörg

Tested with 10.4.15, ts3bootstrap 4.6.1 and 4.6.0.
![Screenshot 2021-07-25 182210](https://user-images.githubusercontent.com/66782510/126906191-f4234afc-0132-4430-9062-0a7bad13d92d.png)

**Comment by t3solution** [comment]
I will fix it in the next few days (hopefully) ...
As a workaround, you can do the translation in the List module!

**Comment by joergwiedemann** [comment]
Thank you Helmut, the Workaorund is really ok for me. So i  can do my translating job and the customer is happy.

**Comment by t3solution** [comment]
New version 5 - new issues!
