### ISSUE TITLE
Images to small in gridelements

### ISSUE THREAD

**Issue by schmoe-github** [t3solution/t3sbootstrap#126]
Hi Helmut Hackbarth,

If we use Image or Text/Image Element inside a gridelement, for example 4 Columns. Then the image is always to small, that means it is not using the full width of the column.

How can we achieve that the images size is always 100% of the column? I don't want to scale it up with CSS.

Our enviroment:
t3sbootstrap: 4.4.8
gridelements: 9.6.0
TYPO3 9.5.28

Thanks in advance.

Kevin

**Comment by t3solution** [comment]
In my Dev-Installation -> TYPO3 9.5.10 - gridelements 9.6.0 - t3sbootstrap 4.4.8
it works as expected!
What are your settings in the gallery row width?

**Comment by t3solution** [comment]
New version 5 - new issues!

**Comment by slavlee** [comment]
Hi Helmut Hackbarth,

I have to come back to this issue.

We have upgraded t3sbootstrap vom 4 to 5.1.7. I think it went pretty good so far. But we still have the issue, that images without given image sizes in the content element, are not using the full width inside a column element.

We have 2 two column element and the image is not as bride as the column, when window with is bigger than 1200px. The image sizes fits for the breakpoints below perfectly.

Our setting for the two columns element is:

col-md- 6/6
col-* 12/12

Thanks in advance.

Kevin.

**Comment by schmoe-github** [comment]
Hi Helmut Hackbarth,

I have to come back to this issue.

We have upgraded t3sbootstrap vom 4 to 5.1.7. I think it went pretty good so far. But we still have the issue, that images without given image sizes in the content element, are not using the full width inside a column element.

We have 2 two column element and the image is not as bride as the column, when window with is bigger than 1200px. The image sizes fits for the breakpoints below perfectly.

Our setting for the two columns element is:

col-md- 6/6
col-* 12/12

Thanks in advance.

Kevin.
