### ISSUE TITLE
$rootPageId in  ConfigController->writeConstants

### ISSUE THREAD

**Issue by sunfish** [t3solution/t3sbootstrap#127]
Hi Helmut Hackbarth,
this concerns the class ConfigController.php and the method function writeConstants

typo3 rootLine Description: The rootLine (all the way to tree root, not only the current site!).
Therefore $rootPageUid = $rootLineArray[0]['uid']; leads not allways to the "is_siteroot' page uid.
Tested solution is:
$rootPageId = array_search('1', array_column($rootLineArray, 'is_siteroot', 'uid'));

so get $rootpageId first:
$rootLineArray = GeneralUtility::makeInstance(RootlineUtility::class, $config->getPid())->get();
new: $rootPageId = array_search('1', array_column($rootLineArray, 'is_siteroot', 'uid'));

Then replace $rootLineArray[0]['uid'] with $rootPageId

I hope this helps and can be adopted. 
Thanks for your very good work

Ulrich

**Comment by t3solution** [comment]
New version 5 - new issues!
