### ISSUE TITLE
Missing checkboxes in T3SB Config

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#129]
(see attached image)

Using TYPO3 v11.3.3 and t3sbootstrap 4.6.2 on latest Firefox browser. Amongst others, the checkboxes of Expanded Top Content Enable and Content Slide in T3SB Config are not visible and clickable with small code enabled.

Might be caused by bestyles-v11.css line 372.

![image](https://user-images.githubusercontent.com/25581914/130444477-d3ec8d1a-ac9b-4a69-aad5-d3e05b90a4ed.png)

**Comment by t3solution** [comment]
New version 5 - new issues!
