### ISSUE TITLE
prettify template code

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#13]
https://github.com/t3solution/t3sbootstrap/blob/master/Resources/Private/Layouts/Content/Default.html

Please do not double the `<div>` tag, but set the classes itself with a condition. Or define a variable to later set using vhs:variable.set. But then you would need to include EXT:vhs. For me EXT:vhs is in all of my projects.

```
<f:if condition="{container}">
	<div class="{container}">
</f:if>
<f:if condition="{cardSlider}">
	<div class="carousel-item col-md-4">
</f:if>
```

One more:
https://github.com/t3solution/t3sbootstrap/blob/master/Resources/Private/Partials/Content/Header/All.html
You could avoid non-closed tags by using sections.

**Comment by t3solution** [comment]
Thanks for the hint, but I don't need the EXT:vhs, this is also possible with EXT:t3sbootstrap:
https://github.com/t3solution/t3sbootstrap/commit/25d2d93ac43db9b4828e56f2adcf7330593989e5
https://github.com/t3solution/t3sbootstrap/commit/d16e4d3c93f70208737a4ea7e6d87e7deb175d26
https://github.com/t3solution/t3sbootstrap/commit/56b776b2e043ca8bdc034be3f5869398734af06d
https://github.com/t3solution/t3sbootstrap/commit/f34a064365ecf21dea842d38a91b443e24a84b38

**Comment by t3solution** [comment]
Improved
