### ISSUE TITLE
Documentation constants for bootstrap.cdn.enable contains a small error

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#132]
Constants setting bootstrap.cdn.enable

"before CDN can be disabled, run the scheduler task "T3SB CDN to local" to write the required files to fileadmin/T3SB/Resources/_Private_/"

must be "Public"

(and the same also in the Scheduler task command)

'cause that's where they go :-)

![image](https://user-images.githubusercontent.com/25581914/134059788-67a94c67-9ea6-42ff-8a9b-56ae468ce233.png)

![image](https://user-images.githubusercontent.com/25581914/134060637-6039f7b2-dc39-4cf9-981a-35b48a659b44.png)

**Comment by t3solution** [comment]
New version 5 - new issues!
