### ISSUE TITLE
navbarClickableparent doesn't seem to work

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#134]
I'm still working on all the updates because is a big breaking change from b4 to b5
but I've encountered a few issues already, not sure if it's conflicts in my installation, or in your ext.
navbarClickableparent = 1
dropdown appears on hover (as expected)
browser renders the link of the parent as expected (i see it in the bottom left of the window), but when i click it parent, the action closes the dropdown instead of going to link.

**Comment by t3solution** [comment]
Fixed: https://github.com/t3solution/t3sbootstrap/commit/22fa91ba70685ecc0d371ff62ace467de4cd3127
