### ISSUE TITLE
Version 5.0.0 installed, however Bootstrap Version 4.6.0 loaded

### ISSUE THREAD

**Issue by numismae** [t3solution/t3sbootstrap#137]
Fresh install of Typo3 10.4.21 and t3sbootstrap 5.0.0 will not load Bootstrap 5.1.1., instead Bootstrap 4.6.0 is loaded. The Extension Manager also indicates that t3sbootstrap 4.6.2 is installed. Any suggestions? Thank you

**Comment by t3solution** [comment]
The release 5.0.0 is faulty indeed.
Pls use BUGFIX release v5.0.1

**Comment by t3solution** [comment]
I close this issue - should be fixed!
