### ISSUE TITLE
Accordion doesn't integrate the bootstrap context color (with solution)

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#138]
Older versions of extension used the the class sent by appearance tab in content element, you forgot this feature in this version, here is the solution, and i use the opportunity to integrate the animation code.
Just change the first 2 lines of the Accordion section (accordion-item and accordion-header)

```
.
.
.
<f:section name="Accordion">
  <div class="accordion-item"{f:if(condition:'{style}',then:' style="{style}"')}{dataAnimate}{f:if(condition: animationSettings, then: '{animationSettings -> f:format.raw()}')}>
    <h2 class="accordion-header mt-0{f:if(condition:'{class}',then:' {class}')}" id="heading-{data.uid}">
.
.
.
```

it is necessary though to set the button background as transparent in css, i don't know if u want to integrate this yourself, i solve this in sass as follows

```
    .accordion-header {
      &.bg- {
        &primary, &secondary, &info, &warning, &danger, &success, &light, &dark {
          .accordion-button { background-color: transparent; }
        }
      }
    }
```

**Comment by t3solution** [comment]
Should be fixed!
