### ISSUE TITLE
Card-deck has no responsive behaviour

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#140]
There are 2 ways to solve this:
1: Editor has no control over responsive behaviour
--- code for this solution
the flexform selection of **visible cards** should apply a row-cols-md-{selection} and have a row-cols-1 fixed in template
`<div class="card-deck gy-4 row row-cols-1 row-cols-md-{visibleCards}{f:if(condition:'{class}',then:' {class}')}"………`

2: Editor has control over responsive behaviour
--- solution: change flexform to multiple dropdowns
**Visible Cards**
xs: row-cols-{visibleCards.xs}
sm: row-cols-sm-{visibleCards.sm}
md: row-cols-md-{visibleCards.md}
lg: row-cols-lg-{visibleCards.lg}
in this case, when a certain device is not selected, no class of that device should be applied
e.g.:
```
{f:if(condition: visibleCards.xs, then: ' row-cols-{visibleCards.xs}', else: ' row-cols-1')}
{f:if(condition: visibleCards.md, then: ' row-cols-{visibleCards.md}')}
```
etc……

**Comment by t3solution** [comment]
Should be fixed!
