### ISSUE TITLE
Access to change logs of older versions

### ISSUE THREAD

**Issue by schmoe-github** [t3solution/t3sbootstrap#142]
Hi Helmut,

is there any way how to get access to the old change logs and upgrade instructions. For instance for:

https://www.t3sbootstrap.de/version-455
https://www.t3sbootstrap.de/version-454

Thanks in advance.

Kind regards,

Kevin

**Comment by peerlight** [comment]
looks like changelogs of versions 4.3.0 to 4.4.0 on https://www.t3sbootstrap.de/log are messed up

there are all descriptions shonw first, then
4.3.5 - 20.10.2019

4.3.4 - 21.07.2019

4.3.3 - 29.04.2019

4.3.2 - 06.03.2019

4.3.1 - 06.03.2019

4.3.0 - 26.02.2019

**Comment by schmoe-github** [comment]
Thanks, I didn't see the older changelogs on the log page. Now, I got it.

Btw. the link for the v455 changelogs inside the TER is wrong, where it links to https://www.t3sbootstrap.de/version-455, Maybe you want to do a redirect.

**Comment by t3solution** [comment]
Should be working now!
