### ISSUE TITLE
Multidomain Issues

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#144]
Hi helmut,
I updated the site were i had the multidomain problems explained in [issue #130](https://github.com/t3solution/t3sbootstrap/issues/130). Of course i resaved the t3sb configurations (this has to be done during the update anyway)

But the new ts3sb 5 seems to still have this issues. where neither jumbotron nor footer columns are available in the backend

I haven't tried to install a fresh version of t3sb5 and see if the issues also happen there and there's a conflict with other installed extensions in my TYPO3 instance.

Have you tried this?

**Comment by t3solution** [comment]
Hello Henry,
yes, I remember the adjustment. Unfortunately I had problems in my multi-domain installations afterwards.
So I have withdrawn the adjustments.
How did you build your installation?

**Comment by t3solution** [comment]
... or describe the problem to me again in detail.

**Comment by HenryAveMedi** [comment]
Site (id=0):
|
-domain 1 (t3sb config) (id=1, parent = Site)
--sub page (parent = domain 1)
--sub page (parent = domain 1)
|
-domain 2 (t3sb config)  (id=54, parent = Site)
--sub page (parent = domain 2)
--sub page (parent = domain 2)

Both t3sb configs have the exact same t3sb configurations (including jumbotron and footer)
domain 1 and subpages show jumbotron and footer in backend
<img width="564" alt="grafik" src="https://user-images.githubusercontent.com/51093175/136081626-6827aea7-129a-4d92-a32b-3abb20654cdf.png">

domain 2 and subpages don't show jumbotron nor footer in backend
<img width="684" alt="grafik" src="https://user-images.githubusercontent.com/51093175/136081701-7058edeb-acf5-4b83-b2af-a7299231a79f.png">

**Comment by HenryAveMedi** [comment]
omg……… yep, that seems to have been my issue………

:|
