### ISSUE TITLE
Background wrapper doesn't show image when screen width > 2560px

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#145]
The background wrapper element uses JS to add the background image according to screen resolution, but the last given property to add the background-image is `@media (max-width: 2560px)`, which means, that 4k screens (which is what i use) are left out

Proposed solution, change the `@media (max-width: 2560px)` property to `@media (min-width: 1920.02px)` which would start showing this property after the max 1920 finishes, or add a new property `@media (min-width: 2560.02px)`

**Comment by t3solution** [comment]
You can change the max-width with the following constant -e.g.:
bootstrap.image.bgMediaQueries = **2900**, 2560, 1920, 1200, 992, 768, 576
Is that a solution?

**Comment by HenryAveMedi** [comment]
not a proper one though…… nowadays there's any monitors that go to 3400 and 5000 pixels, but they're still a minority, not sure if it's worth rendering such big images as well…… but i'll do that, thnx

**Comment by t3solution** [comment]
This is fixed - I closed this issue!
