### ISSUE TITLE
 Indexed Search Result page [t3sbs 5.1.0/TYPO3 11LTS]

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#147]
Hi,

using the indexed_search templates of t3sbs causes error when search-button of the plugin is clicked

Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\Link\PageViewHelper: noCacheHash. Valid arguments are: additionalAttributes, data, aria, class, dir, id, lang, style, title, accesskey, tabindex, onclick, target, rel, pageUid, pageType, noCache, language, section, linkAccessRestrictedPages, additionalParams, absolute, addQueryString, argumentsToBeExcludedFromQueryString, addQueryStringMethod

The search works as expected when 

plugin.tx_indexedsearch {
	view {
		templateRootPaths {
			#  5 = EXT:t3sbootstrap/Resources/Private/Extensions/indexed_search/Resources/Private/Templates/
		}
		partialRootPaths {
			#  5 = EXT:t3sbootstrap/Resources/Private/Extensions/indexed_search/Resources/Private/Partials/
		}
	}
}

is commented out/the default-templates are used.

Kind regards

wini2

**Comment by wini2** [comment]
Hi,

the bugix helps, but there is a strange behaviour with the results. Using the indexed_search-original templates I get results for incomplete words. t3sbs-templates only show results for complete words e.g. bootstr - no result, bootstrap - results

This behaviour is also on https://www.t3sbootstrap.de/suchen?tx_indexedsearch_pi2%5Baction%5D=search&tx_indexedsearch_pi2%5Bcontroller%5D=Search&cHash=ee6994d91f5adbfe4184897120daff01

Thanks
wini2

**Comment by t3solution** [comment]
Should be working now!
