### ISSUE TITLE
Navbar -> Entry Level: unable to override entry level on subpages

### ISSUE THREAD

**Issue by numismae** [t3solution/t3sbootstrap#149]
The setting of the "Entry Level" at root configuration is working as expected. However any changes to the "Entry Level" or "Levels" setting on a subpage have no effect on the respective menu and may even result in a menu without any menu items at all. Perhaps the setting "T3SB Config on subpages" is not working properly? Please advise, thank you.

**Comment by t3solution** [comment]
Should be working now!
