### ISSUE TITLE
carousel - feedback

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#15]
Got into touch with the carousel functionality after all. Customer had several images in the slider, which all did not allow any header to be displayed above, because of bad visiblity. Every slider should link to somewhere. I could not get this running without changing the code. I dropped the {zoom} stuff and replaced it with a link using {celink} as parameter. I suggest there should be a possibility to make the whole picture clickable/a link.

**Comment by peerlight** [comment]
missed this too in the last days

**Comment by t3solution** [comment]
Solution: https://github.com/t3solution/t3sbootstrap/commit/f56a01b233058207159d43f7b59f188fed73d69e

**Comment by t3solution** [comment]
Fixed: https://github.com/t3solution/t3sbootstrap/commit/f56a01b233058207159d43f7b59f188fed73d69e
