### ISSUE TITLE
BS Toast does not work correctly in v 5.1.1

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#150]
Hi,

in version 5.1.1 BS Toast does not work correctly. 
The toast does not show up.
Unfortunately, I have no idea how to fix it.

Best regards..  steffen

**Comment by liveman1** [comment]
Hi,
in Console it throws an error reading the "clientHeight".
Uncaught TypeError: Cannot read properties of null (reading 'clientHeight')
    at HTMLDocument.<anonymous> (autogenerated-98:205)
I have deactivated the navbar. Activating it does not have any impact. 

function ready(fn) {
	if (document.readyState != 'loading'){
		fn();
	} else {
		document.addEventListener('DOMContentLoaded', fn);
	}
}
ready(() => {
	// Default - Main.html
	const navbar = document.getElementById('main-navbar'),
		  **navbarHeight = navbar.clientHeight,**
		  navbarBreakpointWidth = document.body.getAttribute('data-navbar-breakpointwidth'),
		  viewportWidth = parseFloat(getComputedStyle(document.querySelector('html'), null).width.replace("px", "")),
		  onePageLayout = navbar.classList.contains('sectionMenu');

best regards
steffen

**Comment by t3solution** [comment]
Should be working now!
