### ISSUE TITLE
Enhancement for BS Toast - embed other content elements

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#151]
Hi,

it would be great if one could embed other content elements, like text/images, carousels etc..
This would help to provide short explanations through a gif, or by navigating through the different carousel elements.

Thanks..  steffen

**Comment by t3solution** [comment]
Pls use the modal in this case!

**Comment by liveman1** [comment]
This would be a nice enhancement, that I'd like to fund or donate for.
The use case would be to expose the user of a website to some more comprehensive information, like changes or a brief introduction to the page functionality (using images, swiper etc.). This could be easily realized without further programming using Toasts.
What do you think & what can I do to get it realized?

**Comment by t3solution** [comment]
You can send me a mail with the order to do that.
It will take 1 hour - special flat-rate (80,-€/net)!
Then i will send you an invoice.
