### ISSUE TITLE
v5.1.3 - cards are stacked above each other, when putting a masonry in a modal

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#156]
Hi,
all cards are stacked above each other, when putting a masonry in a modal.
When the page gets resized, all cards are put in a proper layout.
I can't see any JS issues in the console.
Best regards

**Comment by t3solution** [comment]
The problem is "position: absolute" (masonry need this) in the modal-dialog.
I have no solution for this!
