### ISSUE TITLE
Language "Connected Mode" and Animate.css

### ISSUE THREAD

**Issue by hxkxn** [t3solution/t3sbootstrap#159]
I have a fresh installation, TYPO3 11.5.1, and I am using your t3bootstrap V5 template. If I use English as second language "Connected Mode" and use Animate.css just like the default language, the content of the English content column disappears. As soon as I set the animation to "None" the content appears again. With Copy Mode, it works.

**Comment by t3solution** [comment]
I can't understand that, in my test environment (v11.5.2) it works as expected!

**Comment by hxkxn** [comment]
That is strange, I had t3sbootstrap v4 with T3 11.2, and it worked as expected too. Okay, thank you very much for your information.

**Comment by t3solution** [comment]
Closed: problem is fixed!
