### ISSUE TITLE
drop sourceMappingURL=bootstrap.min.js.map

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#16]
https://github.com/t3solution/t3sbootstrap/blob/master/Resources/Public/Contrib/Bootstrap/js/bootstrap.min.js

The file is not provided.  Concatenation/Compression may make it impossible to use a source map file?

**Comment by t3solution** [comment]
Fixed: https://github.com/t3solution/t3sbootstrap/commit/f6c22af94f3358ebda0408058d21bac1011e6cdb
