### ISSUE TITLE
v5.1.3 - Tab Container - first tab not active in OnePage Layout without navbar

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#161]
Hi,
when using OnePage layout without navbar, the first tab in a tab container is inactive / closed.

**Comment by t3solution** [comment]
I have no idea where your problem is.
Can you describe it better?

**Comment by liveman1** [comment]
sorry for the poor description. 
When loading a website , all tabs are closed. Meaning, none of them is active/open. 

"active" is missing in the class of the tab button.

<button id="tab-429" **class="nav-link"** data-bs-target="#tab-content-429" data-bs-toggle="tab" role="tab" aria-controls="tab-content-429" aria-selected="false">
				Tab
			</button>

I do not get any issue reported in the console.  This might be caused by the navbar settings similar to the toast issue #150 .
I am not using the navbar.

**Comment by liveman1** [comment]
Hi,
this issue might be similar to issue 150 https://github.com/t3solution/t3sbootstrap/issues/150, which you could already fix.
In t3sbHelper.js line 222 it tries to get the client height & navbar height in order to set "firstTab.show();"
I do not have a navbar. Thus, all tabs are closed and not active.

It would be great, if you could have a look into this one. 
Thanks

**Comment by liveman1** [comment]
It works for me, when following code is replaced in TabContainer.html line 7-11 by
var tabs = document.querySelectorAll('.nav.nav-tabs, .nav.nav-pills');
		if ( tabs.length ) {
			tabs.forEach( tabcontainer => {
				var firstTabEl = document.querySelector('#'+tabcontainer.id+' li:first-child button');
				var firstTab = new bootstrap.Tab(document.getElementById(firstTabEl.id));
				firstTab.show();
			});
		}

This is similar to the fix that was applied for issue 150.

It would be great if you could take this over.

Thanks & best regards!

**Comment by liveman1** [comment]
[TabContainer.html.txt](https://github.com/t3solution/t3sbootstrap/files/7668411/TabContainer.html.txt)
Enclosed is the file with the fix.

**Comment by t3solution** [comment]
It may be that your solution works but the needed option for "window.location.hash" has disappeared.
You should find another solution. Take a look at the Main.html!

**Comment by t3solution** [comment]
Closed: problem is fixed!
