### ISSUE TITLE
v 5.1.3: Uncaught ReferenceError: t3sbTabs is not defined

### ISSUE THREAD

**Issue by bzgaLindner** [t3solution/t3sbootstrap#163]
Hi,
when using TabContainer, I see an error in error console: "Uncaught ReferenceError: t3sbTabs is not defined". 

This refers to line  of /Resources/Private/Templates/Container/TabContainer.html.

Except from this there is no notable incorrect behaviour.

Best,
Dominik

**Comment by t3solution** [comment]
Closed: problem is fixed!

**Comment by bzgaLindner** [comment]
thx!
