### ISSUE TITLE
Enhancement - enhanced media options in Carousel Element

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#164]
It would be cool to have the "Use original image option" as well in Carousel Element, in order to embed animated GIFs.
In the same way it would be nice to embed movies (mp4) as well.

**Comment by liveman1** [comment]
Thanks a lot for the update!
Adding movies works great. 
However, I can't find the setting to use the original image. I upgraded using the upgrade wizard & enabled the setting in the EM configurator.
Could you please help?

**Comment by t3solution** [comment]
You'll find the option in the "carousel container"!

**Comment by liveman1** [comment]
Thanks a lot! Works great!

**Comment by t3solution** [comment]
Closed: problem is fixed!
