### ISSUE TITLE
Carousel Container - Indicators html output is not valid

### ISSUE THREAD

**Issue by at-ac** [t3solution/t3sbootstrap#165]
hi,
I use a carousel container in the jumbotron. Something is wrong and not valid with the html of the indicators:
`<ol class="carousel-indicators d-none d-md-block">
	<li data-bs-target="#carousel-163" data-bs-slide-to="0" class="active" <="" li="" aria-current="true"></li>
	<li data-bs-target="#carousel-163" data-bs-slide-to="1" <="" li="" class=""></li>
	<li data-bs-target="#carousel-163" data-bs-slide-to="2" <="" li="" class=""></li>
	<li data-bs-target="#carousel-163" data-bs-slide-to="3" <="" li="" class=""></li>
</ol>`
see: https://validator.nu/?doc=https%3A%2F%2Fke.atac-web.de%2F
If I use thumbnails it's ok.

Using t3sbootstrap 5.1.4, TYPO3 11.5.2

any idea?
Markus

**Comment by t3solution** [comment]
Closed: problem is fixed!
