### ISSUE TITLE
Enhancement - login form with Bootstrap styling

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#167]
Hi,
the standard login form does not really comply with bootstrap styling & needs hardcoding to change texts and styling.
It would be great to have a bootstrap login form with the possibility to enter a specific welcome text.
Thanks

**Comment by liveman1** [comment]
Thanks a lot for implementing this! It works great!

**Comment by t3solution** [comment]
Closed: problem is fixed!
