### ISSUE TITLE
5.1.4 - Multiple Mega Menu Nav Items doesn´t work

### ISSUE THREAD

**Issue by Sunusually** [t3solution/t3sbootstrap#169]
When there are multiple Nav Items which are configured as Mega Menu, an opened Mega Menu doesn´t close when you click on another Mega Menu Nav Item.

**Comment by Sunusually** [comment]
I might have found a temporary solution for me:
t3sbootstrap\Partials\Page\Navbar\Assets.html

If I commenting out event.stopPropagation(); everything seems to work but I am too less javascript expert to judge the impact:

	megaDropdown.forEach( md => {
		md.addEventListener('click', (event) => {
			 // event.stopPropagation();
		});
	});

**Comment by t3solution** [comment]
This should be fixed in the version 5.1.5 already!

**Comment by Sunusually** [comment]
Works :)
