### ISSUE TITLE
prevent a-Tag in a-Tag in news "lists"

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#17]
in line 50 of Resources/Private/Extensions/News/Partials/List/Body/Item.html add "-> f:format.stripTags()" to "{newsItem.bodytext ... " 

This prevents a-Tag in a-Tag when there is a link in bodytext and Resources/Private/Extensions/News/Partials/List/ListGroup.html oder Card.html is used. 

They link the whole element with "<n:link newsItem="{newsItem}""

**Comment by t3solution** [comment]
Fixed: https://github.com/t3solution/t3sbootstrap/commit/c9df523724f47eb0f45b4cc1a6bde08295d5d437
