### ISSUE TITLE
Edit Config issue

### ISSUE THREAD

**Issue by numismae** [t3solution/t3sbootstrap#173]
It is possible to display TSB3 Config module to non admin users. Access to edit TSB3 Config on a page with a configuration is not possible though and the following message is displayed: "SORRY, but here you have to outsource yourself the appropriate templates and customize according to your requirements!"

What exactly do you mean by "here you have to outsource yourself the appropriate templates and customize according to your requirements"?

Is there any chance to set permissions to specific tabs in TSB3 Config for non admin users?

**Comment by t3solution** [comment]
You should outsource the following Template and copy the content from Resources/Private/Backend/Partials/Config/Accordion.html to Resources/Private/Backend/Partials/NonAdmin/Accordion.html.
Here you can use conditions e.g.:
...
```
<f:if condition="{field.property} == 'generalRootline' || {field.property} == 'compress'">

	<f:if condition="{isSiteroot}">
		<f:then>
			<f:render partial="Config/{field.type}" arguments="{_all}" />
		</f:then>
		<f:else>
			<f:if condition="{field.property} != 'contentOnlyOnRootpage'">
				<f:render partial="Config/{field.type}" arguments="{_all}" />
			</f:if>
		</f:else>
	</f:if>

</f:if>
```
...
Or in the NESTED ACCORDION below ...
```
<f:if condition="{field.property} == 'bodyExtraClass'">

	<f:render partial="Config/{field.type}" arguments="{_all}" />

</f:if>
```
...

The Options 'generalRootline', 'compress' & 'bodyExtraClass' now can be used by Non-Admins

![grafik](https://user-images.githubusercontent.com/5745943/148052061-8751006c-82a4-4ec0-86ec-dfb6ea9ce0ed.png)

**Comment by numismae** [comment]
perfect!

**Comment by t3solution** [comment]
Closed: problem is fixed!
