### ISSUE TITLE
Class names doubled in CE

### ISSUE THREAD

**Issue by numismae** [t3solution/t3sbootstrap#174]
It appears that class names are entered or doubled on rendering of page. For example:
<div id="c38" class="fsc-default ce-html pt-4 mt-5 fsc-default ce-html pt-4"></div>

This is also refers to additional classes entered via "Bootstrap Utilities -> Extra Class".

**Comment by t3solution** [comment]
Can you give me an example?

**Comment by numismae** [comment]
`<div id="c39" class="fsc-default ce-text mt-5 fsc-default ce-text"><h2>test</h2><p>test</p></div>`

**Comment by numismae** [comment]
also it appears that in some cases class names are merged, because a blanc is missing: `<div id="c406" class="pt-4mt-5 pt-4">...`

**Comment by t3solution** [comment]
Unfortunately I cannot understand the problem.
Can you give me more details how you produced this?

**Comment by numismae** [comment]
Apply basic procedure, like add any type of CE to a page, hit Preview and use Chrome Developer Tools to inspect the rendered page. If "CType in class" is checked in EM or a new class is added via "Bootstrap Utilities -> Extra Class" the class names are doubled.

**Comment by t3solution** [comment]
I know the developer tools :-)
I cannot understand the problem, it works as expected for me!
It could be that you have outsourced templates and not updated them?

**Comment by numismae** [comment]
Typo3 10.4.22, T3SB 5.1.5, various installations and same behaviour, like so: 
<img width="747" alt="Bildschirmfoto 2022-01-04 um 18 05 35" src="https://user-images.githubusercontent.com/25180287/148096555-98d899c0-7f60-4320-b9a2-b1af670e6d3c.png">

for example: missing blanc between pt-3 and mt-5 and 2 x ce-html. 

Perhaps ClassHelper.php may cause the behaviour?

**Comment by t3solution** [comment]
Sorry, but I cannot reproduce the "bug" (TYPO3 10.4.21 & T3SB 5.1.5). 
In my installation it looks like this:

![grafik](https://user-images.githubusercontent.com/5745943/148106008-c5a9ab86-5c64-45bf-bd88-f728b11be5e7.png)

The problem should be in your Installation!
Disable all outsourced templates & test again!

**Comment by numismae** [comment]
I set up a new instance and I confirm that the new system behaves as expected, sorry about the inconvenience! However, where would you possibly locate the mentioned outsourced templates, getting around to reset a running system?

**Comment by t3solution** [comment]
Information on outsourced templates: [T3SB](https://www.t3sbootstrap.de/dokumentation/snippets/template-auslagern)
In the TSOB it should looks like this in order not to have any outsourced templates:
![grafik](https://user-images.githubusercontent.com/5745943/148353630-54baf065-fddc-4610-942e-ca80b03e77f4.png)

**Comment by t3solution** [comment]
Closed: problem is fixed!
