### ISSUE TITLE
no more breadcrumb output / rendering after update to 5.1.7

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#178]
seems, the breadcrumb output is gone in 5.1.7. tested with 3 different t3 systems 10.4.23. tested with no outsourced partials/templates

![image](https://user-images.githubusercontent.com/47745128/151354295-44a14056-2b25-411c-a2c9-bebae7bb2fbc.png)

![image](https://user-images.githubusercontent.com/47745128/151354472-060553eb-b984-460c-896c-5aae16533ce4.png)

**Comment by asche76** [comment]
wao, thank you, that was fast

**Comment by t3solution** [comment]
This issue has been fixed!
