### ISSUE TITLE
No Jumbotron, optional Top-Content and optional Bottom-Content after in Backend

### ISSUE THREAD

**Issue by pekubawue** [t3solution/t3sbootstrap#181]
Hello,
this are my versions: typo3 11.5.5 and t3sbootstrap 5.1.7

Although I activated Jumbotron, optional Top-Content and optional Bottom Content, there are no Content-Fields (only "Normal") in the Backend to edit those fields. (I activated "expanded content" in the EM and in the T3sB-configuration of the template.)

Did I forget a step? Does anyone know, if there is a mistake?
I would be very happy if someone can help me,
thank you very much
Petra

**Comment by t3solution** [comment]
Hello Petra,
you probably didn't select a backend layout!

**Comment by pekubawue** [comment]
Thank you so much! Yes, this solved my problem!
