### ISSUE TITLE
Backend - Page Content - Keep collapsed containers closed, when reloading the page content

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#185]
Hi,

I hope this is the right place & belongs to the t3sbootstrap module.

Is there any way to keep collapsed containers / content elements closed on the backend page content module, when reloading the page? Meaning the small red triangle...
Actually, when reloading collapsed containers are opened again. This is quite annoying if there are many elements, since you have to scroll a lot to find & also in regards of loading times.

Thanks a lot
![collapse container](https://user-images.githubusercontent.com/7196290/155522394-3625df3c-2800-4937-9999-c2a604ab5260.png)
!

**Comment by t3solution** [comment]
Ther is an option in the EM config:

![grafik](https://user-images.githubusercontent.com/5745943/155523775-585d47e1-1685-4888-a852-369fe48d7283.png)

**Comment by liveman1** [comment]
Wow! Thanks a lot for your prompt reply!  :)
