### ISSUE TITLE
TYPO3 9.5 languageNavigation doesn't take query parameters when switching language (e.g. News Detail) using route-enhancer

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#19]
when I'm in the detail view of a news article and when I switch the language, the parameters of the query are not translated, so it basically sends me to an empty detail page

I've been trying for hours to fix this problem but I don't seem to find a solution…… I use route enhancer to translate the detail view URLs query into the news title

the nearest i've found is to add following to the link in the Partials/Page/NavBar.html:
> addQueryString="TRUE" addQueryStringMethod="GET"

you use an < a > but this only seems to work in <f:link.page> and I can't use
> href="{languageNavigation.{iterator.index}.link}"

in <f:link.page>

i've tried with <link.typolink> as well but in both methods i lose the language-switching-goal, even if i use lang={config.lang.hreflang.{lang}} which would translate to en-US or de-DE in the site configuration……… it just renders the link to the detail page in the current language for all links in menu

any help? I think i've reached my cappabilities to solve this
I'd be grateful for any solution

**Comment by TrueType** [comment]
Please give an example. I do not understand on the first read. If you use route enhancers you may want to use language aspects in the site.yaml?

**Comment by HenryAveMedi** [comment]
ok…… so…… lets say i have the following URL:
> https://my.domain/news/detail/alarm

When I go to my language navigation the domains rendered are:
> EN: https://my.domain/news/detail/
> DE: https://my.domain/de/news/detailansicht/

so, the **/alarm** at the end basically gets lost
If I'm navigating only in german site and I'm standing in the news list page:
> https://my.domain/de/news/
from there, all links are rendered correctly, so if i go to the list item of article in question it would send me to:
> DE: https://my.domain/de/news/detailansicht/alarm

So, that's what I mean with the question, the problem only appears when I'm already in the detail view page, and I want to switch the language with the navbarmenu.

**Comment by HenryAveMedi** [comment]
OK, I've solved it……… love you stackoverflow………
it seems in your template you are using MenuProcessor in the setup instead of languageMenuProcessor

I've added the following to my setup and it works:
```
page {
  10.dataProcessing.40 = TYPO3\CMS\Frontend\DataProcessing\LanguageMenuProcessor
  10.dataProcessing.40 {
    languages = auto
    special >
  }
}
```

**Comment by HenryAveMedi** [comment]
Whit this method it's also easier to access the items now, I've got rid of the itereator.index……
my Language navigation doesn't have the fontawesome icon… but here is the code so you get the idea
```
<f:section name="Language">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="language" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <f:for each="{languageNavigation}" as="item">
          <f:if condition="{item.active}">
            <f:then>
              <span>
                <f:if condition="{settings.navbar.langFlags}">
                  <core:icon identifier="{config.lang.flag.{item.languageId}}" size="small" />
                </f:if>
                <span class="nav-label">{item.title}</span>
              </span>
            </f:then>
          </f:if>
      </f:for>
    </a>
    <div class="dropdown-menu dropdown-menu-right mt-0 language-menu">
      <f:for each="{languageNavigation}" as="item">
        <f:if condition="{item.available}">
          <f:then>
            <a
              href="{item.link}"
              class="dropdown-item{f:if(condition: '{item.active}', then: ' active')}" 
              hreflang="{item.hreflang}"
              title="{config.lang.title.{lang}}"
            >
              <span> 
                <f:if condition="{settings.navbar.langFlags}">
                  <core:icon identifier="{config.lang.flag.{item.languageId}}" size="small" />
                </f:if>
                {item.title}
              </span>
            </a>
          </f:then>
          <f:else>
            <span class="dropdown-item text-muted">
              <f:if condition="{settings.navbar.langFlags}">
                <core:icon identifier="{config.lang.flag.{item.languageId}}" size="small" />
              </f:if>
              {item.title}
            </span>
          </f:else>
        </f:if>
      </f:for>
    </div>
  </li>
</f:section>
```

**Comment by HenryAveMedi** [comment]
> t3solution added a commit that referenced this issue 4 days ago
@t3solution
IMPROVEMENT: Language Menu Style #19 

Hey! I saw you commited my fix and no FA template! I feel honored to have contributed a tiny bit to your great extension!
I made a fix on the integration of {settings.langMenuWithFaIcon} in the template to make it shorter and less complicated since the if is only needed inside the <a> tag

Here's the code if you're interested in updating it :)

```
<f:section name="Language">
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="language" href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
      <f:if condition="{settings.langMenuWithFaIcon}">
        <f:then>
          <i class="fa-navlink fas fa-globe"></i>
        </f:then>
        <f:else>
          <f:for each="{languageNavigation}" as="item">
            <f:if condition="{item.active}">
              <f:render section="LanguageFlag" arguments="{_all}" />
              <span class="nav-label">{item.title}</span>
            </f:if>
          </f:for>
        </f:else>
      </f:if>
    </a>
    <div class="dropdown-menu dropdown-menu-right mt-0 language-menu">
      <f:for each="{languageNavigation}" as="item">
        <f:if condition="{item.available}">
          <f:then>
            <a
              href="{item.link}" hreflang="{item.hreflang}" title="{item.title}"
              class="dropdown-item{f:if(condition: '{item.active}', then: ' active')}"
            >
              <f:render section="LanguageFlag" arguments="{_all}" />
              {item.title}
            </a>
          </f:then>
          <f:else>
            <span class="dropdown-item text-muted">
              <f:render section="LanguageFlag" arguments="{_all}" />
              {item.title}
            </span>
          </f:else>
        </f:if>
      </f:for>
    </div>
  </li>
</f:section>

<f:section name="LanguageFlag">
  <f:if condition="{settings.navbar.langFlags}">
    <core:icon identifier="{config.lang.flag.{item.languageId}}" size="small" />
  </f:if>
</f:section>
```

**Comment by t3solution** [comment]
I will take over - the solution is much better 👍

**Comment by t3solution** [comment]
Is integrated!
