### ISSUE TITLE
MediaViewHelper: Unable to create image with srcset

### ISSUE THREAD

**Issue by okmiim** [t3solution/t3sbootstrap#190]
The function `createImageTagWithSrcset` ([ResponsiveImagesUtility](https://github.com/t3solution/t3sbootstrap/blob/06f6a44682e83f98367342edf8d78c56484ed7cc/Classes/Utility/ResponsiveImagesUtility.php)) does not exist since v4.5.0 anymore, however, is still called.
https://github.com/t3solution/t3sbootstrap/blob/06f6a44682e83f98367342edf8d78c56484ed7cc/Classes/ViewHelpers/MediaViewHelper.php#L231

**Comment by t3solution** [comment]
Thanks for the information. Will be fixed in the next version!
