### ISSUE TITLE
T3SB not compatible with Front Editing?

### ISSUE THREAD

**Issue by numismae** [t3solution/t3sbootstrap#194]
Frontend Editing throws error with t3sbootstrap enabled. pls. ref. to Screenshot of console.
Typo3 Version 11.5.8, Bootstrap Components Version 5.1.8, Frontend Editing Version 3.0.16
Please advise, thank you

<img width="1021" alt="Bildschirmfoto 2022-04-07 um 11 15 57" src="https://user-images.githubusercontent.com/25180287/162167122-6ea31eeb-ced1-4cc2-a126-a65dc7043437.png">

**Comment by numismae** [comment]
Any updates on this? It actually used work with version Typo3 10, thank you!

**Comment by t3solution** [comment]
Unfortunately I don't have an installation with frontend-edit :-)
Can you fix this problem and set up a pull request?

**Comment by numismae** [comment]
Fixed with Bootstrap Components Version 5.2.1 and Frontend Editing Version 3.0.27
