### ISSUE TITLE
Outsource custom scss

### ISSUE THREAD

**Issue by Psycho0verload** [t3solution/t3sbootstrap#196]
Hello,
so far in v4 I have outsourced my customSCSS to my extension and set it that way via Extension Configuration:

```
't3sbootstrap' => [
    'customScss' => '1',
    'customScssPath' => 'typo3conf/ext/my_extension/Resources/Public/SCSS/',
],
```

In v5 this is no longer present. How can I implement this in v5?
I have tried to realize it via "Multidomain Setup":
create a custom-1.scss 
create a custom-variables-1.scss

```
page {
	includeCSS {
		bootstrapCustom = typo3conf/ext/my_extension/Resources/Public/SCSS/bootstrap-1.scss
		bootstrapCustom.forceOnTop = 1
	}
}
```

Throws me an error:
```
(1/1) ScssPhp\ScssPhp\Exception\CompilerException
`/var/www/html/public/typo3conf/ext/my_extension/Resources/Public/SCSS/bootstrap-1.scss` file not found for @import: line: 1, column: 0
```

even if I then enter the custom-1.scss there it does not work.
Would it be possible to reintroduce the option to outsource my custom scss to my extension?

**Comment by Cretection** [comment]
I will try this :)
Thanks!

**Comment by Psycho0verload** [comment]
I have now tried different variants. It has worked. For the documentation: After setting the constants the scheduler must run once with customscss.

The option Custom-SCSS.editScss does not work in this case. Is for my need but then also no longer necessary

**Comment by t3solution** [comment]
The option Custom-SCSS.editScss should work with v5.1.11
