### ISSUE TITLE
Log full of: Undefined array key "cookieconsent_status" warnings

### ISSUE THREAD

**Issue by createdwithlove** [t3solution/t3sbootstrap#198]
On a TYPO3 v11.5.9 with EXT:t3sbootstrap v5.1.8 following error is logged on every action in the backend:

```PHP Warning
Core: Error handler (BE): PHP Warning: Undefined array key "cookieconsent_status" in /www/htdocs/xyz.de/vendor/symfony/expression-language/Node/GetAttrNode.php line 97```

**Comment by createdwithlove** [comment]
Thank you for your fast reply, but upgrading to 5.10 didn't help.

**Comment by t3solution** [comment]
... you should use an FTP-Client to move the "Controller" directory from "Classes/Backend" to "Classes"!

**Comment by createdwithlove** [comment]
Seems that `Controller` already was in the right directory:
<img width="222" alt="Bildschirmfoto 2022-04-29 um 10 35 04" src="https://user-images.githubusercontent.com/1146811/165911100-2333e3e0-65b0-4556-ac54-4eb2e86b5efc.png">

But warning is still shown:
<img width="879" alt="Bildschirmfoto 2022-04-29 um 10 39 03" src="https://user-images.githubusercontent.com/1146811/165911664-2d95f828-a6c6-454e-b4ff-b12a38e67a72.png">

I'll try a fresh installation next week and test if I can reproduce it.

**Comment by t3solution** [comment]
Did you clear the cache and Rebuild PHP Autoload?

**Comment by createdwithlove** [comment]
@t3solution I've cleared all caches i know including: deleted `./var/` and `./public/typo3temp/`, run `composer dumpautoload`, clicked all colors of flash icons, used all possibilites the maintenance module has to offer for clearing, removing and flushing … didn't help

Just tried a fresh and empty installation with just `typo3/cms-base-distribution:^11.5` and `t3sbs\t3sbootstrap:^5.1` which resulted in the same warning.

**Comment by t3solution** [comment]
Try commenting out lines 109 - 129 in the file "t3sbootstrap/Configuration/TypoScript/setup.typoscript"!

**Comment by createdwithlove** [comment]
I commented out the lines and as expected, the error no longer appears.

**Comment by vmans** [comment]
This same issue goes for doktype (Core: Error handler (BE): PHP Warning: Undefined array key "doktype"...).

Hide the errors/warnings by commenting out lines 16 - 20 in the file "t3sbootstrap/Configuration/TSConfig/Page.tsconfig" (latest t3sbootstrap).
