### ISSUE TITLE
Is it possible to have a modal active on pageload? preferably with a timeout?

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#20]
Hi, thank you very much for your typo3 extension, works wonders and easy to handle.
I'm working on a project where I need a modal more or less behaving like a pop-up, somewhat similar to cookie consent, but I want my own content in the modal…

Is it possible to have a modal activate itself on pageload? preferably with a timeout?

**Comment by t3solution** [comment]
Hi Henry,
you can try the following TS/JS (untested):

page.jsFooterInline.11 = TEXT
page.jsFooterInline.11.value (
	$('#myModal').modal('show');
	setTimeout("$('#myModal').modal('hide');",5000);
)

**Comment by HenryAveMedi** [comment]
yeah i did already, was just windering if there was a way to do it without adding a script of my own and i just wasnt able to find it…
thank you very much though
