### ISSUE TITLE
Boostrap Card > class ="card" missing

### ISSUE THREAD

**Issue by hanwa11** [t3solution/t3sbootstrap#201]
After the update to 5.1.11, class = "card"  is missing in the DIV container. In version 5.1.8 it worked.
![Screenshot 2022-04-30 112958](https://user-images.githubusercontent.com/78408636/166100211-9aa0407c-1480-42b8-8e0d-5aa0416f0c41.png)
.

**Comment by t3solution** [comment]
BUGFIX: https://github.com/t3solution/t3sbootstrap/commit/94544e9e85c07874f99f7475bd0e0c2729304c2c
