### ISSUE TITLE
equalHeight setting is removed but still has effect in version < v5.1.5

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#205]
The flexform setting "equalHeight" has been removed from the colums container elements since v5.1.5. (why?)

Now if I have a card element without a card wrapper, but inside one of these container elements (say, fourcolumns) with equalHeight = 1 in the flexform, and I have it as a legacy from before v5.1.5, the parent element has a height 100% that I cannot change anymore (only on database level).

See Card.php, line 117, which now is supposed to work only on card-deck wrappers, still works on legacy settings:
`$cardClass .= !empty($parentflexconf['equalHeight']) ? ' h-100' : '';`

This behaviour should be changed somehow I think.

I solved it like this, for the time being:
`
        if ($parentFlexformData['CType'] = "card-wrapper") {
            $cardClass .= !empty($parentflexconf['equalHeight']) ? ' h-100' : '';
        }
`

**Comment by t3solution** [comment]
Isn't it easier to put the following in "Extra Class":
![grafik](https://user-images.githubusercontent.com/5745943/168065700-1678bb01-8421-4239-9081-cbb58249971a.png)

**Comment by vmans** [comment]
Thanks for your reply. No it isn't because in this case it goes over 1400 content elements. I don't think I can instruct my client to do that ;-)

But I have to describe the point of the issue better:
In the past, the setting equalHeight = 1 could be applied to the twocolumn, threecolumn and fourcolumn container elements.
After upgrading t3sbootstrap, since v5.1.5, this field is not available anymore in the backend in the card element (except if the wrapping container is a card-wrapper). This setting however is still stored in the flexform field in the database, so it still has its - unwanted - effect.

**Comment by t3solution** [comment]
I will restore the option with the next version (coming soon)

**Comment by vmans** [comment]
Many thanks.

I'm not sure if simply restoring and using h-100 is the best solution within the newest Bootstrap environment, but it will be manageable then.

For a mass update of flexform fields, perhaps you can provide an example query in the documentation, or a script, or refer to a source? I'm not sure how to do that.

**Comment by t3solution** [comment]
You won't need an update script because i'm using the old notation "equalHeight" in the flexform!

**Comment by MV-1** [comment]
v5.2.0 equal height doesn't work on cards with "Link the entire Content Element" enabled. 

card.php line 177:

 $cardClass .= ' h-100'; instead of $cardClass .= ' w-100'; seems to solve this issue.
