### ISSUE TITLE
How to change fonts?

### ISSUE THREAD

**Issue by fxp66** [t3solution/t3sbootstrap#208]
How can I change the font for the whole installation?
Could it be managed via the t3sbootstrap variables or the custom scss?
Thank you for advise
fxp

**Comment by t3solution** [comment]
If you use custom-scss then choose a Bootswatch theme (e.g. Cosmo). 
Then you have an example of how to implement it!

**Comment by fxp66** [comment]
Thank you, works for me.
fxp
