### ISSUE TITLE
Compability to T3v10

### ISSUE THREAD

**Issue by bucheggerOnline** [t3solution/t3sbootstrap#21]
It would be nice to have a version for T3v10. Is there already something planned?

**Comment by t3solution** [comment]
... it's not just planned, it's in the drawer!

**Comment by bucheggerOnline** [comment]
Is there any timeframe for a release? (Next Month, Summer, This Year)...
Just wanna know if it makes sense to wait for that. ;)

**Comment by t3solution** [comment]
... ask for a dev-version at info@t3solution.de
or wait max. 10 days for the release.

**Comment by bucheggerOnline** [comment]
Great. Thx for the fast reply ;)

**Comment by schnere** [comment]
As it might help, here my changes for a basically running version in Typo3 10 (Patch for commit f6696161d760c6e1067828fbf9a4db3ba817c507):

[0001-Changes-for-Typo3-10.txt](https://github.com/t3solution/t3sbootstrap/files/4475067/0001-Changes-for-Typo3-10.txt)

**Comment by t3solution** [comment]
Support for TYPO3 v10 is available!
