### ISSUE TITLE
Grid-Cards - EqualHeight does not work  and Card-width differs

### ISSUE THREAD

**Issue by mbsued** [t3solution/t3sbootstrap#210]
After updating to 5.1.13 EqualHeight does not work for Card-wrapper "Grid-Cards" and with adding "d-flex align-items-stretch" to div there is no equal width for the cards anymore.

**Comment by t3solution** [comment]
In my installation it works as expected: https://www.t3sbootstrap.de/dokumentation/komponenten/card-layout/card-decks
You probably outsourced a template and didn't update it. Is that possible?

**Comment by mbsued** [comment]
I do not use own templates.
i put some screenshots here. you can see the difference before update and after update.
before update it looks like this: 
![faecher_vorupdate](https://user-images.githubusercontent.com/5165597/170010074-4b306e9f-697a-465d-82dc-a17dd5d77964.png)
![startseite_vorupdate](https://user-images.githubusercontent.com/5165597/170010082-0ee012d7-13d4-4b98-baca-98ed5257ee4b.png)
and after update:
![faecher_nachupdate](https://user-images.githubusercontent.com/5165597/170010187-612a3efc-75cc-479a-8699-177c2e4deca2.png)
![startseite_nachupdate](https://user-images.githubusercontent.com/5165597/170010188-65e98abd-9a6c-42d8-b17f-7df58ea3912f.png)

**Comment by t3solution** [comment]
The problem is not "equal height". The problem is the missing imagewidth in t3sbs_card. 
If you set this to 576 it will leven ook good on mobile.

**Comment by t3solution** [comment]
OK - in this case you have to add "w-100" to "tx_t3sbootstrap_extra_class" or the css-style: .card-deck .card (width: 100%)

**Comment by mbsued** [comment]
i tried this but did not work. maybe the "link entire element" causes the problem, because it wraps around the div class="col d-flex align-items-stretch"? 
<div class="card-deck gallery g-4 row row-cols-1 row-cols-md-4">
	<div class="col d-flex align-items-stretch">
		<a href="/unterricht/allgemeinbildende-faecher/deutsch" title="Interner Link: Fachinformationen Deutsch" class="ce-link">
			<div id="c1089" class="bg-body fach-card w-100 card bg-body above ce-link-content">
				<div class="card-body">
					<div class="card-text">
						<p class="text-center"><i aria-hidden="true" class="fas fa-book-reader fa-3x"></i></p>
						<h5 class="text-center">Deutsch</h5>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>

**Comment by mbsued** [comment]
`<div class="card-deck gallery g-4 row row-cols-1 row-cols-md-4">
	<div class="col d-flex align-items-stretch">
		<a href="/unterricht/allgemeinbildende-faecher/deutsch" title="Interner Link: Fachinformationen Deutsch" class="ce-link">
			<div id="c1089" class="bg-body fach-card w-100 card bg-body above ce-link-content">
				<div class="card-body">
					<div class="card-text">
						<p class="text-center"><i aria-hidden="true" class="fas fa-book-reader fa-3x"></i></p>
						<h5 class="text-center">Deutsch</h5>
					</div>
				</div>
			</div>
		</a>
	</div>
</div>`

**Comment by mbsued** [comment]
sorry trie to add the source-code does not work

**Comment by t3solution** [comment]
Why do you use the CE t3sbs_card and a wrapper? Here I would use a container (e.g.: three_columns) and inside the columns you can use CType:textmedia or text. Or you try stretched-link https://getbootstrap.com/docs/5.1/helpers/stretched-link/

**Comment by t3solution** [comment]
... if it's a lot of work for you, i'll look again for a solution. come back to it later (today)!

**Comment by mbsued** [comment]
thank you its not urgent i tried it out with 4 columns and Ctype:text, same problem if i use link-entire-element.

**Comment by mbsued** [comment]
thanks!!! works fine.
