### ISSUE TITLE
T3SB Config only compare Root Config

### ISSUE THREAD

**Issue by schmoe-github** [t3solution/t3sbootstrap#213]
Hello Helmut,

we have the situation that the T3SB Config on subpages writes only the config parameter which have different values than the rootConfig. For example breadcrumb (but this affects all config parameters)

- Root -> breadcrumb enable = 0
- - Subpage1 -> breadcrumb enable = 1
- - - Subpage 2 -> breadcrumb enable = 0

The breadcrumb will be shown on Subpage 2 even though it is disabled in the T3SB Config for this page. We have enabled on every T3SB Config -> on subpages: 1.

So far I understand the code of ConfigController->getConstants it only compares the value of the rootConfig. And only if there are changes compared to the rootConfig, the current setting will be written in the file. So, it is not possible to overwrite settings like in the example above for sub pages.

Is this a bug or feature?

Kind regards,

Kevin

**Comment by t3solution** [comment]
Hello Kevin,
In this case and for a better overview in your code you should work with conditions in your constants.
Let's assume your pages have the following id's:
Root = 1
Subpage1 = 2
Subpage2 = 3
You can achieve the desired result with the following snippet:
[page["uid"] == 2]
bootstrap.config.breadcrumbEnable = 1
[END]

chears
Helmut

**Comment by t3solution** [comment]
One more thing: If you deactivate "T3SB Config on subpages" in the BE Modul, you also have the desired result!

**Comment by schmoe-github** [comment]
Thanks Hemut,

your last tip only works, when all pages have their own T3SB Config. Then only when you enable "T3SB Config on subpages" the configuration is inheritable from child pages otherwise the condition in t3sbconstants.typoscript is related to 1 page only.

I'm aware of your first tip, but we would prefer to let our customer handle the configuraiton without using TypoScript.

So I guess, there is no option in t3sbootstrap where the T3SB Config is compared to the next previous one rather than the root config yet?

Thanks in advance.

**Comment by schmoe-github** [comment]
Hi Helmut,

this don't solve the problem either and I don't know if we are on the same page. I try to explain it one more time.

We have this structure:

- Root
  - Page 1
    - Page 2
      - Page 3

Root => Breadcrumb disabled and "T3SB Config option on subpages" enabled.
Page 1 => Breadcrumb enabled and "T3SB Config option on subpages" enabled, because we need to inherit this setting to all subpages
Page 2 => Has no config and takes Root Config Settings + Difference to Page 1 Settings, because T3SB Config only set TypoScript settings from values that differs to the root config. But that is ok for this page
Page 3 => Breadcrumb disabled and "T3SB Config option on subpages" disabled. On this page the breadcrumb is still enabled, because there is no TypoScript setting: bootstrap.config.breadcrumbEnable = 0 in the condition for this page. Becuase the root config has breadcrumb disabled as well. What we need would be, that the Script compares the closes T3SB Config, which is here Page 1.

And that's the basic problem that only values are written inside t3sbconstants.typoscript, when they are differ from the root config. But in our project we would need it to compare the closest T3SB Config values. 
A solution like to write all constants, despite the root config, when "T3SB Config option on subpages" is set would fix it.

Kind regards,

Kevin.

**Comment by t3solution** [comment]
... I have another idea to solve the problem:
Root => Breadcrumb enable, "T3SB Config option on subpages" enabled and "Not on rootpage" enable.
The rest remains unchanged.

That should work!

Chears
Helmut

**Comment by schmoe-github** [comment]
Hi Helmut,

thanks, but this does not work unfortunately.

The root config contains all constants with values regarding my settings in T3SB Config.

The T3SB Config of Page 1 contains only constants that differed from root config. Example:

[4 in tree.rootLineIds]
bootstrap.config.uid = 506
bootstrap.config.generalRootline = 1
bootstrap.config.jumbotronClass = m-0 p-0 text-white
bootstrap.config.breadcrumbEnable = 1
bootstrap.config.breadcrumbContainer = container
bootstrap.config.footerContainer = none
[END]

The setting for Page 3 has only settings that also differs from the root config:
[page["uid"] == 2294]
bootstrap.config.uid = 520
bootstrap.config.breadcrumbContainer = container
bootstrap.config.footerContainer = none
[END]

But in Page 3 we also have breadcrumb disabled in the T3SB Config, but this setting will not be written in the file, because the decision if the value will be written on the file is based on the comparison to the root config, where the breadcrumb is disabled too.
T3sbootstrap should check which contants are active and make a decision based on that. So, in this example the Breadcrumb setting should be written on Page 3, because it was changed on Page 2.

This procedure is unchanged regardless, if I enable or disable the setting "T3SB Config option on subpages". I think all what this setting does is that it change the type of condition, like:

[X in tree.rootLineIds] or [page["uid"] == X]

Kind regards

Kevin

**Comment by t3solution** [comment]
I have created a test with the following settings:

ROOT
bootstrap.config.generalRootline = 1
bootstrap.config.breadcrumbEnable = 1
bootstrap.config.breadcrumbNotonrootpage = 1

Page 1 (subpage of root)
bootstrap.config.generalRootline = 1
bootstrap.config.breadcrumbEnable = 1
bootstrap.config.breadcrumbNotonrootpage = 0

Page 2 (subpage of 1)
NO CONFIG

Page 3 (subpage of 2)
bootstrap.config.generalRootline = 0
bootstrap.config.breadcrumbEnable = 0
bootstrap.config.breadcrumbNotonrootpage = 0

... and it works as expected!

Chears
Helmut

**Comment by schmoe-github** [comment]
To verify our situation you have to have the settings in the ROOT the following:

bootstrap.config.breadcrumbEnable = 0

Then in our enviroment the bootstrap.config.breadcrumbEnable setting will not be included on Page 3.

And breadcrumb setting is just an example. It's the same with other settings.

**Comment by schmoe-github** [comment]
thank you.

**Comment by t3solution** [comment]
There will be a solution with the next release!

**Comment by schmoe-github** [comment]
Sound awesome!

Do you know, when the next release will be released?

**Comment by t3solution** [comment]
... maybe today but not later than tomorrow :-)
INFO: https://www.t3sbootstrap.de/log

**Comment by t3solution** [comment]
If the solution works for you, we can close the issue!?

**Comment by schmoe-github** [comment]
Yes, it did.

Thank you very much and we can close this issue.
