### ISSUE TITLE
Error in ConfigProcessor.php

### ISSUE THREAD

**Issue by mbsued** [t3solution/t3sbootstrap#215]
After update to Version 5.1.14 the following error occurs 
Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1476107295: PHP Warning: Invalid argument supplied for foreach() in /html/typo3/typo3conf/ext/t3sbootstrap/Classes/DataProcessing/ConfigProcessor.php line 92 | TYPO3\CMS\Core\Error\Exception thrown in file /html/typo3/typo3_src-10.4.28/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 134. Requested URL: https://neu.bfbn.de/

Typo3- Version: 10.4.28

**Comment by schmoe-github** [comment]
I got exactly the same issue. We use 5.1.14 and 10.4.27.

We also have 5.1.14 and 10.4.28 on another page and there we don't have this issue.

**Comment by t3solution** [comment]
Which PHP version are you using?

**Comment by schmoe-github** [comment]
PHP Version 7.4.30 in both enviroments and in only one the error occures. 

I upgraded to 10.4.28 where we have this issue, but there we still have the problem there without the workaround.

**Comment by mbsued** [comment]
After upgrading to 10.4.30 error still remains
