### ISSUE TITLE
Enhancement - Support nesting of button groups to create dropdown menus

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#218]
Hi,

it would be great if nesting of button groups could be supported in order to enable dropdown menus within a button group as described here: https://getbootstrap.com/docs/4.0/components/button-group/#nesting

Thanks!

**Comment by t3solution** [comment]
You can implement this feature and set up a pull request or you support this feature with a donation.

**Comment by liveman1** [comment]
Hi, thanks!  I will send you a PM.
