### ISSUE TITLE
$bootstrap.config.jumbotronContainerposition} does not exist

### ISSUE THREAD

**Issue by juergen1964** [t3solution/t3sbootstrap#222]
Hi there,
on my new TYPO3 (11.5.12) installation i got this message:

503 "Oops, an error occurred!" 
Section "{$bootstrap.config.jumbotronContainerposition}" does not exist.

Is there a bug or did i miss something? I use the t3sbootstrap version 5.1.16 from the ter.

And also there is a problem with deactivate the CDN. I did run the scheduler task "T3SB CDN to local" and find the files in fileadmin/T3SB/Resources/Public/ folder.
But, i can not remove the "1" in the Enable CDN option in the constant editor.

Thx for a helping hand and have a nice day!

**Comment by juergen1964** [comment]
Update:

by deactivate jumbotron at all ((bootstrap.config.jumbotronEnable=0), next error message shown:


Section "{$bootstrap.config.footerContainerposition}" does not exist

by deactivate footer at all (bootstrap.config.footerEnable=0), next error message shown:

`../../fileadmin/T3SB/Resources/Public/SCSS/custom-variables` file not found for @import: /home/..../tx_t3sbootstrap bootstrap.scss on line 2, at column 1 Call Stack: #0 import /home/.../uploads/tx_t3sbootstrap/bootstrap.scss (unknown file) on line 1

Deactivation of the CDN (bootstrap.cdn.enable=0) in the constants field does not work.

It seems this issue is simular to: #219 no custom scss is being created 

Thx

**Comment by t3solution** [comment]
I can't understand all that, it works for me as expected.

**Comment by juergen1964** [comment]
Hello and thanks for the replay.
So then probably i did something wrong. I will set up a new installation on the weekend and let You know the results.

Have a nice day!

**Comment by t3solution** [comment]
... can i get access to your new website?

**Comment by juergen1964** [comment]
Hi,
of sure - i replayed your mail, i hope you received it? i created a admin user for you and put the link to the backend into this mail, i hope you got that?
Thx

**Comment by t3solution** [comment]
... I haven't received any mail yet!

... use this mail: typo3@t3solution.de

**Comment by juergen1964** [comment]
I have send You a mail with the user data. Feel free to do in the backend what ever You want. Thx!

**Comment by juergen1964** [comment]
Hello Helmut,
this issue can be closed.

Thank You again for your help!

What i did to solve the issue: I took another TYPO3 source file to made a new installation. Everything then worked just fine.. 
One more hint: Make sure your site-configuration got no missconfiguration (i used a subdomain for my installation and with a not well configured site-configuration the site was shown also on my main domain.
