### ISSUE TITLE
Collapsible Container loads only original Media file

### ISSUE THREAD

**Issue by bcd99** [t3solution/t3sbootstrap#223]
The Collapsible Template calls for the original file but I need the edited file from the backendeditor. don't know how to get it. can anyone help?

 `<h2 class="accordion-header" id="heading-{data.uid}">
		<button class="accordion-button{collapsed}{f:if(condition: '{media.originalFile}', then: ' p-0 accordion-img')}{f:if(condition: '{class}',then: ' {class}')}{f:if(condition: '{header.hClass}',then: ' {header.hClass}')}"{f:if(condition:'{style}',then:' style="{style}"')} type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{data.uid}" aria-expanded="{expanded}" aria-controls="collapse-{data.uid}">
			<f:if condition="{media.originalFile}">
				<f:image image="{media.originalFile}" alt="{media.alt}" title="{media.title}" width="200c" height="200c" class="float-left me-3" />
			</f:if>
			{f:if(condition: '{data.tx_t3sbootstrap_header_fontawesome}', then: '<i class="{data.tx_t3sbootstrap_header_fontawesome} me-1"></i> ')}
			{f:if(condition: '{data.header}', then: '{data.header -> f:format.raw()}', else: 'Accordion-{data.uid}')}
			<f:if condition="{data.subheader}">
				<small class="ms-3">
					> {data.subheader -> f:format.raw()}
				</small>
			</f:if>
        <div class="backgroundcord"><i class="fa-regular fa-chevron-up"></i></div>
		</button>
	</h2>`

**Comment by t3solution** [comment]
Can you make the question a little more specific. 
I don't know what you mean exactly.

**Comment by bcd99** [comment]
sorry, I´ll try to do it better. 

i am cropping/edititng some images in the backend editor. But the template loads the original file. Means all my editing is ignored. I don't know how to call the edited file in the fluid template.

Templatepath: …/Resources/Private/Templates/Container/Collapsible.html

there is a condition "media.OriginalFile" and  `<f:image image="{media.originalFile}" alt="{media.alt}" title="{media.title}" width="60c" height="60c" class="float-left me-3" />` this calls the unedited File and crops it. but I want to use my editing from the backend. so the question is, how can I call the edited file in this template?
