### ISSUE TITLE
Colorscheme bg-color results in js error and prevents shrinking navbar to work

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#224]
If you use the option of bg-color it ends in empty data handlers and therefor in a javascript error and the shrinking navbar fails.

![t3sbootstrap-issue](https://user-images.githubusercontent.com/25581914/176757615-a5afe9be-28f6-4120-9472-808be4e6d6ae.png)

**Comment by t3solution** [comment]
You probably haven't read the corresponding information to use the shrinking navbar: 
**Does not work with "Background color" only with "Color schemes".**
![grafik](https://user-images.githubusercontent.com/5745943/176837384-88f402e8-0293-4279-93bb-bc7f99fb4724.png)

**Comment by vmans** [comment]
That wasn't clear anymore to me as soon as I went into the background settings. Thanks!
