### ISSUE TITLE
Breadcrumb & Sidebar sumbenu not working in 11.5.12

### ISSUE THREAD

**Issue by ness2828** [t3solution/t3sbootstrap#228]
Hi there,

unfortunately I am not able to include the breadcrumb and sidebar submenu into the template. Even though "enable" is clicked within the T3SB Configuration, the breadcrumb and even the sidebar submenu won't be rendered. Everything else seems to be working fine - the nav, the title, the footer etc.

Can you please check this? The Main.html Template is used, the correct typoscript is included.

Kind regards,
ness

**Comment by t3solution** [comment]
I can not understand the problem - for me it works as expected!
