### ISSUE TITLE
Media adjustments are missing in Bootstrap Carousel Item

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#234]
Hi,

I have just recognized, that the media adjustments (use original image etc.) for Bootstrap Carousel Items are missing again in v5.1.18. 
I am not sure until which version it was in.
https://github.com/t3solution/t3sbootstrap/issues/164

It would be great if you could enable this again.

Thanks & best regards

**Comment by t3solution** [comment]
You can find these settings in the carousel container not in the carousel item.

**Comment by liveman1** [comment]
Ah ok, thanks!
Is there any chance to get the "use original image" also in Swiper Container?   This would be useful to embed animated gifs.
Thanks
