### ISSUE TITLE
How to open specific modal through url?

### ISSUE THREAD

**Issue by liveman1** [t3solution/t3sbootstrap#238]
Hi,
I am using a registration form (sf_register extension) in a modal. When submitting the form the page is reloaded not showing the modal.
Is there any way to load the website with a specific modal opened?

Thanks a lot!

**Comment by liveman1** [comment]
Hi,
following JS added to the footer should do the job to open a modal with a specific id:

`
document.addEventListener("DOMContentLoaded", function() {
        if (window.location.href.indexOf("#modal-6") > -1) {
                var myModal = new bootstrap.Modal(document.getElementById('modal-6'));
                myModal.show();
        }
});
`

You should then be able to open the website and showing the modal by entering http://www.website.com/#modal-6.

In my case it does not really work. It shows the modal-backdrop, however not the modal itself.

Is there anything special that I have to consider?

Thanks

**Comment by t3solution** [comment]
You can try the following scipt:

```
<script type="text/javascript">
    window.onload = function () {
        OpenBootstrapPopup();
    };
    function OpenBootstrapPopup() {
        $("#myModal").modal('show');
    }
</script>
```

**Comment by liveman1** [comment]
Hi ,

thanks. Just checked again. My script above works pretty well.

document.addEventListener("DOMContentLoaded", function() {          //adds listener
      if (window.location.href.indexOf("#modal-6") > -1) {                      //if url consists of "#modal-6", e.g. www.domain.de/#modal-6
      var myModal = new bootstrap.Modal(document.getElementById('modal-6'));   //identifies modal with id=modal-6 
      myModal.show();                                                                              //shows modal
      } 
});


It would be great, if the t3sbootstrap framework could provide a more generic solution ootb, that works for all modals.
I am not sure, however as far as I can remember it was already possible to open a modal by adding #modal-id in the url a year ago or so. However, not sure at all.
