### ISSUE TITLE
creating scss - zip creation failed

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#239]
Hi, is this a server or an extension issue?

Execution of task "Execute console commands (scheduler)" failed with the following message: Sorry ZIP creation failed at this time!

![image](https://user-images.githubusercontent.com/47745128/183678235-e25aae47-9ffb-4ddd-bce9-42ec02cd6966.png)

**Comment by t3solution** [comment]
In the extension log under 5.1.18 is the following:
"REQUIREMENT: Your PHP version should support the unzip functionality"

**Comment by asche76** [comment]
thanks a lot)

**Comment by asche76** [comment]
sorry, it's me again. 
all php zip packages are enabled, tried it on 4 different servers, php 7.4 and php 8.1 - no chance - ZIP creation is still not working.

![image](https://user-images.githubusercontent.com/47745128/183932877-1675bb35-7e3d-4c87-8a1f-4a2fd46148eb.png)

**Comment by SNMVGlobaltech** [comment]
Hi,

In Classes/Command/CustomScss.php

Change ligne 294 :

> ` if ($zip->open($localZipPath) === TRUE) { `

to

>  if ($zip->open($localZipFile) === TRUE) {

**Comment by asche76** [comment]
thx, the error is gone, but still no files has been created:

![image](https://user-images.githubusercontent.com/47745128/184088316-86c05b6a-f7fc-495e-8e69-3457e4179c97.png)

**Comment by asche76** [comment]
zip error avoidable trought constants settings. thank you.
