### ISSUE TITLE
Here is a container expected! ... you can disable this error message in the constant editor!

### ISSUE THREAD

**Issue by ProWebs** [t3solution/t3sbootstrap#240]
Where can this be disabled? Maybe the error message could deliver a hint to the right constants.

**Comment by t3solution** [comment]
You probably use outsourced templates with the outdated note: "Here is a container expected! ... you can disable this error message in the constant editor!"
Here is the current notice: "Here is a container expected! ... you can disable this error message in the BE Modul!"

The following constant can also be set: bootstrap.config.containerError=0

**Comment by ProWebs** [comment]
Thanks for support. This solved the problem.
