### ISSUE TITLE
custom SCSS - SCSS folder are not created

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#243]
sorry for this follow-up issue. the zip-error is gone, but no SCSS folder with variables scss content are being created

![image](https://user-images.githubusercontent.com/47745128/184604650-89bfdb39-e463-41aa-93f5-3afe9741c300.png)

![image](https://user-images.githubusercontent.com/47745128/184604691-7aa378f5-9329-41be-b923-d274f5a10cec.png)

- all directories are writable by everyone (test) - chmod
- no errors in log

**Comment by t3solution** [comment]
... did you set the following constant: bootstrap.customScssPath

**Comment by asche76** [comment]
i did not set this, the settings is:

![image](https://user-images.githubusercontent.com/47745128/184870168-ae2ec3a5-180a-457a-aca2-6334366f65cd.png)

**Comment by asche76** [comment]
tested it on an older system - with T3 10.4.31 + T3SB 4.6.3 it worked as aspected

![image](https://user-images.githubusercontent.com/47745128/185092110-5ba0b51d-ab27-4d26-b5a6-6d6e006f61a1.png)

**Comment by t3solution** [comment]
You have a multidomain setup.
Did you check and set the bootstrap version in the constants editor on the root-pages?
Otherwise I can not understand the problem!

**Comment by asche76** [comment]
- single domain setup
- bootstrap 5.2.0 in constants
- 5.2.0 css in source code
too bad it seemed to work in 4.x t3sb versions...
