### ISSUE TITLE
Using background-wrapper without an image throws an error

### ISSUE THREAD

**Issue by joergwiedemann** [t3solution/t3sbootstrap#244]
T3 11.5.14, PHP  8.0, T3SB 5.2 
Inserting an background-wrapper and trying to save it without an image, an error was thrown. 
PHP Warning: Undefined array key 0 in /....../typo3conf/ext/t3sbootstrap/Classes/UserFunction/TcaMatcher.php line 356
Adding an image everything is fine und i can save the background-wrapper.

Jörg

**Comment by kunoFM** [comment]
Same error in 
line 168 " if ( $arguments['record']['CType'][0] == 'parallax_wrapper' ) "
and 
line 252 "if ($arguments['record']['CType'][0]) "
resulting in "Core: Error handler (BE): PHP Warning: Undefined array key 0"
