### ISSUE TITLE
containerError is always TRUE

### ISSUE THREAD

**Issue by us14v** [t3solution/t3sbootstrap#25]
First of all: many thanks for this great extension!

After upgrading to version 4.4.5, i now see some "Here is a container expected!" alerts here and there.  
Setting bootstrap.config.containerError = 0 in constants has no effect in my case.  
If i f.debug containerError in Layouts/Content/Default.html it always returns TRUE.

For debugging i deactivated all custom Templates, the alert still shows up.  

TYPO3 9.5.15  
gridelements 9.5.0  
t3sbootstrap 4.4.5

**Comment by t3solution** [comment]
I can't understand that!
How is your configuration?
- You have a "OneCol-Page"!?
- Container settings in page?
- Container settings in content elements?
If no container is set, you should do this!
BTW: The condition is in Layout/Content/Default.html. 
You can remove them if necessary!

**Comment by us14v** [comment]
Yes - Page is OneCol  
tx_t3sbootstrap_container in Page = no container  

But i get this alert in the footer for example.  
My config in BackendModule:  
Footer - enable  
Container - container  
Container position - inside  
Content  - 26 (where my Footercontent lives. This a 3 Col Element, that has NO container)  

Generated HTML Markup of Footer:  
footer#page-footer > div.footer > div.container > div.alert.alert-danger + div#c1

**Comment by us14v** [comment]
Forgot to mention, if set container to container in the content element (above footer example), then the generated markup is:  

footer#page-footer > div.footer > div.container > div.container > div#c1

**Comment by t3solution** [comment]
Bugfix is done: https://github.com/t3solution/t3sbootstrap/commit/e60457a0bb6924f7c1592a614f3414e27c370593

**Comment by t3solution** [comment]
Is fixed!
