### ISSUE TITLE
css classes missing, if using own path for Partials

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#255]
if yout set your own path for Partials, t3sb css classes not redendered:

![image](https://user-images.githubusercontent.com/47745128/187234378-0ea6b352-112a-44ab-9e31-08eeb534afda.png)

![image](https://user-images.githubusercontent.com/47745128/187234789-ad7090b3-218e-483a-823a-3f60c07ebb72.png)

textmedia with bootstrap carousel:
default path Partials:
![image](https://user-images.githubusercontent.com/47745128/187235600-dcd4800e-3132-494e-a2bf-9d61b9d76c61.png)

own path for Partials, all the carousel-stuff is missing:
![image](https://user-images.githubusercontent.com/47745128/187236701-7c4f7822-70c5-426f-9f5f-dadc42a03463.png)

**Comment by t3solution** [comment]
I do not understand your problem, for me it works as expected!
