### ISSUE TITLE
Can not get thumbnail from pdf file when linked in FileLinks. 

### ISSUE THREAD

**Issue by sebastiangaertner** [t3solution/t3sbootstrap#257]
Tried everything here. PDF generating mechanism is working in the install tool and when used directly such as 

```
page.20 = IMAGE
page.20.file = fileadmin/intro.pdf
page.20.file.width = 240m
page.20.file.height = 240m
page.20.file.noScale = 1
```
When using the t3sbootrap template the thumbnails do not show up and instead there is a direct link to the pdf file in the img tag. Here the html rendered... 

`<li class="list-group-item"><a href="/fileadmin/intro.pdf"><img src="/fileadmin/intro.pdf" width="720" height="405" alt=""></a><a class="me-2" href="/fileadmin/intro.pdf"><span class="ce-uploads-fileName">intro.pdf</span></a></li>`

using typo3 11.5

**Comment by sebastiangaertner** [comment]
Is that a problem of the TYPO3\CMS\Frontend\DataProcessing\FilesProcessor ??

**Comment by t3solution** [comment]
I tested your snippet with the current version of t3sbootstrap: it works as expected.
The problem must be in your installation!

**Comment by t3solution** [comment]
... the icons are displayed for me - it works as expected!

**Comment by t3solution** [comment]
... the icons are displayed for me - it works as expected!
