### ISSUE TITLE
T3SB Config Module too big

### ISSUE THREAD

**Issue by jantofw** [t3solution/t3sbootstrap#258]
After upgrading to 5.2.1 the content of the frame for T3SB Config Module is so big (and without option for scrolling), that it is not usable in the backend of typo3. Only workaround is to load the frame in a new window to reach all buttons.
System: typo3 10.4.32, php 7.4

**Comment by CarstenHager** [comment]
Sorry, mein Englisch ist nicht gut genug, daher auf Deutsch.

Ich hatte das Problem gestern auch.
Nachdem ich im Install Tool den Debug Modus aktiviert hatte, war das Problem gelöst.
Evtl. hilft dir das auch weiter.

**Comment by jantofw** [comment]
CarstenHager suggests to activate the debug mode in install tool.
Did it, and then the T3SB Config Module is in the right size and usable.
But if switch back to production mode, the problem with T3SB Config Module is back, too.

**Comment by jantofw** [comment]
the upgrade to t3sbootstrap 5.2.3 solves the problem, thanks to the maintainer.
