### ISSUE TITLE
PHP 8 Warning undefined array key "srcset" 

### ISSUE THREAD

**Issue by joergwiedemann** [t3solution/t3sbootstrap#263]
Hello Hemut, setting an image (PHP8, T3SB 5.2.2) throws an error: 
PHP Warning: Undefined array key "srcset" in /typo3conf/ext/t3sbootstrap/Classes/ViewHelpers/MediaViewHelper.php line 162. Am i wrong with configuration? i dont have this issue in another installation, but its T3SB 5.2.1 and another hoster.

**Comment by t3solution** [comment]
... try the version 5.2.3

**Comment by joergwiedemann** [comment]
Thank you. Solved.
