### ISSUE TITLE
configuration of rte_cekditor in cards and mediaObjects 

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#27]
thanks for the v10-compatible version so promtly to the release of TYPO3 10 LTS - great job!

i found an issue (verion 4.4.5) - after some configuration i made. i use my on ckeditor preset, which works fine on text with media and other ce-types. i realized that its not working with cards an mediaObjects. these ce-types show up an very 'minimal' configuration. i have another instance running with t3sbs 4.3.5 and TYPO3 9.5 where my rte is the same as it is in text with media.

can you reproduce it? is it a bug, feautre or my fault?

**Comment by t3solution** [comment]
.. not your fault, that was a bug - here is the bugfix: https://github.com/t3solution/t3sbootstrap/commit/359433e1865631197fb8ac84aabb529546295643

**Comment by wini2** [comment]
thanks for reply. your bugfix works for media objects, but not for cards. strangely the following line 
RTE.config.tt_content.bodytext.types.t3sbs_card.preset = my-own-defaults
is not respected but
RTE.config.tt_content.bodytext.types.t3sbs_carousel.preset =  my-own-defaults
has been respected before your patch.
