### ISSUE TITLE
Update t3sbootrap from to :unexpected 'ModuleTemplateFactory' on BE & FE

### ISSUE THREAD

**Issue by ProWebs** [t3solution/t3sbootstrap#273]
By updating our typo3 10.4.32 installation from t3sbootstrap_5.1.17 to 5.1.18 and above we got this error directly afters updating on backend and also on our frontend.

syntax error, unexpected 'ModuleTemplateFactory' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

`
in /var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/Classes/Controller/AbstractCompatibilityController.php line 28

 // TYPO3 v11
 abstract class AbstractCompatibilityController extends AbstractController
 {
  protected ModuleTemplateFactory $moduleTemplateFactory;

  public function __construct(
   ConfigRepository $configRepository,
   PersistenceManager $persistenceManager,

at Composer\Autoload\includeFile('/var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/Classes/Controller/AbstractCompatibilityController.php')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/composer/ClassLoader.php line 428

     */
    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);

            return true;
        }

at Composer\Autoload\ClassLoader->loadClass('T3SBS\\T3sbootstrap\\Controller\\AbstractCompatibilityController')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/typo3/class-alias-loader/src/ClassAliasLoader.php line 135

     * @return bool|null
     */
    public function loadClass($className)
    {
        $classFound = $this->composerClassLoader->loadClass($className);
        if (!$classFound && !$this->caseSensitiveClassLoading) {
            $classFound = $this->composerClassLoader->loadClass(strtolower($className));
        }
        return $classFound;

at TYPO3\ClassAliasLoader\ClassAliasLoader->loadClass('T3SBS\\T3sbootstrap\\Controller\\AbstractCompatibilityController')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/typo3/class-alias-loader/src/ClassAliasLoader.php line 123

    public function loadClassWithAlias($className)
    {
        $originalClassName = $this->getOriginalClassName($className);

        return $originalClassName ? $this->loadOriginalClassAndSetAliases($originalClassName) : $this->loadClass($className);
    }

    /**
     * Load class with the option to respect case insensitivity

at TYPO3\ClassAliasLoader\ClassAliasLoader->loadClassWithAlias('T3SBS\\T3sbootstrap\\Controller\\AbstractCompatibilityController')
at spl_autoload_call('T3SBS\\T3sbootstrap\\Controller\\AbstractCompatibilityController')
in /var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/Classes/Controller/ConfigController.php line 12

 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */
class ConfigController extends AbstractCompatibilityController
{

 public function initializeAction()
 {

at include('/var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/Classes/Controller/ConfigController.php')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/composer/ClassLoader.php line 571

 * @private
 */
function includeFile($file)
{
    include $file;
}

at Composer\Autoload\includeFile('/var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/Classes/Controller/ConfigController.php')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/composer/ClassLoader.php line 428

     */
    public function loadClass($class)
    {
        if ($file = $this->findFile($class)) {
            includeFile($file);

            return true;
        }

at Composer\Autoload\ClassLoader->loadClass('T3SBS\\T3sbootstrap\\Controller\\ConfigController')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/typo3/class-alias-loader/src/ClassAliasLoader.php line 135

     * @return bool|null
     */
    public function loadClass($className)
    {
        $classFound = $this->composerClassLoader->loadClass($className);
        if (!$classFound && !$this->caseSensitiveClassLoading) {
            $classFound = $this->composerClassLoader->loadClass(strtolower($className));
        }
        return $classFound;

at TYPO3\ClassAliasLoader\ClassAliasLoader->loadClass('T3SBS\\T3sbootstrap\\Controller\\ConfigController')
in /var/customers/webs/klimek/typo3_src-10.4.32/vendor/typo3/class-alias-loader/src/ClassAliasLoader.php line 123

    public function loadClassWithAlias($className)
    {
        $originalClassName = $this->getOriginalClassName($className);

        return $originalClassName ? $this->loadOriginalClassAndSetAliases($originalClassName) : $this->loadClass($className);
    }

    /**
     * Load class with the option to respect case insensitivity

at TYPO3\ClassAliasLoader\ClassAliasLoader->loadClassWithAlias('T3SBS\\T3sbootstrap\\Controller\\ConfigController')
at spl_autoload_call('T3SBS\\T3sbootstrap\\Controller\\ConfigController')
at class_exists('T3SBS\\T3sbootstrap\\Controller\\ConfigController')
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/extbase/Classes/Utility/ExtensionUtility.php line 256

        if (!is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['extbase']['extensions'][$extensionName]['modules'][$moduleSignature] ?? false)) {
            $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['extbase']['extensions'][$extensionName]['modules'][$moduleSignature] = [];
        }
        foreach ($controllerActions as $controllerClassName => $actionsList) {
            if (class_exists($controllerClassName)) {
                $controllerAlias = self::resolveControllerAliasFromControllerClassName($controllerClassName);
                $vendorName = self::resolveVendorFromExtensionAndControllerClassName($extensionName, $controllerClassName);
                if (!empty($vendorName)) {
                    self::checkVendorNameFormat($vendorName, $extensionName);

at TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule('T3sbootstrap', 'web', 'T3sbootstrapM1', '', array('T3SBS\T3sbootstrap\Controller\ConfigController' => 'list, new, create, edit, update, delete, dashboard, constants '), array('access' => 'user,group', 'icon' => 'EXT:t3sbootstrap/Resources/Public/Images/bootstrap-solid.svg', 'labels' => 'LLL:EXT:t3sbootstrap/Resources/Private/Language/locallang_m1.xlf', 'navigationComponentId' => 'TYPO3/CMS/Backend/PageTree/PageTreeElement', 'name' => 'web_T3sbootstrapM1', 'extensionName' => 'T3sbootstrap', 'routeTarget' => 'TYPO3\\CMS\\Extbase\\Core\\Bootstrap::handleBackendRequest'))
in /var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/ext_tables.php line 15

  [
   \T3SBS\T3sbootstrap\Controller\ConfigController::class => 'list, new, create, edit, update, delete, dashboard, constants ',
  ],
  [
   'access' => 'user,group',
   'icon'   => 'EXT:t3sbootstrap/Resources/Public/Images/bootstrap-solid.svg',
   'labels' => 'LLL:EXT:t3sbootstrap/Resources/Private/Language/locallang_m1.xlf',
  ]
 );

at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::{closure}()
in /var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/ext_tables.php line 24

 \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addLLrefForTCAdescr('tx_t3sbootstrap_domain_model_config', 'EXT:t3sbootstrap/Resources/Private/Language/locallang_csh_tx_t3sbootstrap_domain_model_config.xlf');
 \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_t3sbootstrap_domain_model_config');

})();

at require('/var/customers/webs/klimek/df/typo3conf/ext/t3sbootstrap/ext_tables.php')
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1803

        // Load each ext_tables.php file of loaded extensions
        foreach (static::$packageManager->getActivePackages() as $package) {
            $extTablesPath = $package->getPackagePath() . 'ext_tables.php';
            if (@file_exists($extTablesPath)) {
                require $extTablesPath;
            }
        }
    }

at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadSingleExtTablesFiles()
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 1786

            /** @var \TYPO3\CMS\Core\Cache\Frontend\FrontendInterface $codeCache */
            $codeCache = self::getCacheManager()->getCache('core');
            $hasCache = $codeCache->require($cacheIdentifier) !== false;
            if (!$hasCache) {
                self::loadSingleExtTablesFiles();
                self::createExtTablesCacheEntry();
            }
        } else {
            self::loadSingleExtTablesFiles();

at TYPO3\CMS\Core\Utility\ExtensionManagementUtility::loadExtTables(true)
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Core/Bootstrap.php line 548

     * @internal This is not a public API method, do not use in own extensions
     */
    public static function loadExtTables(bool $allowCaching = true)
    {
        ExtensionManagementUtility::loadExtTables($allowCaching);
        static::runExtTablesPostProcessingHooks();
    }

    /**

at TYPO3\CMS\Core\Core\Bootstrap::loadExtTables()
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php line 53

        $pathToRoute = $request->getQueryParams()['route'] ?? $request->getParsedBody()['route'] ?? '/login';

        // Backend Routes from Configuration/Backend/{,Ajax}Routes.php will be implicitly loaded thanks to DI.
        // Load ext_tables.php files to add routes from ExtensionManagementUtility::addModule() calls.
        Bootstrap::loadExtTables();

        // Add the route path to the request
        $request = $request->withAttribute('routePath', $pathToRoute);

at TYPO3\CMS\Backend\Middleware\BackendRouteInitialization->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172

                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php line 55

            [$server, $address] = explode('/', $url, 2);
            return new RedirectResponse('https://' . $server . $sslPortSuffix . '/' . $address);
        }

        return $handler->handle($request);
    }
}

at TYPO3\CMS\Backend\Middleware\ForcedHttpsBackendRedirector->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172

                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php line 75

            $request->getAttribute('normalizedParams')->getRemoteAddress(),
            trim((string)$GLOBALS['TYPO3_CONF_VARS']['BE']['IPmaskList'])
        );

        return $handler->handle($request);
    }

    /**
     * Check adminOnly configuration variable and redirects to an URL in file typo3conf/LOCK_BACKEND

at TYPO3\CMS\Backend\Middleware\LockedBackendGuard->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172

                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php line 45

     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $request = $request->withAttribute('normalizedParams', NormalizedParams::createFromRequest($request));
        return $handler->handle($request);
    }
}

at TYPO3\CMS\Core\Middleware\NormalizedParamsAttribute->process(object(TYPO3\CMS\Core\Http\ServerRequest), object(class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 172

                if (!$middleware instanceof MiddlewareInterface) {
                    throw new \InvalidArgumentException(get_class($middleware) . ' does not implement ' . MiddlewareInterface::class, 1516821342);
                }
                return $middleware->process($request, $this->next);
            }
        };
    }
}

at class@anonymous/var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php0x7f088ebec41b->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php line 78

     * @return ResponseInterface
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->tip->handle($request);
    }

    /**
     * Seed the middleware stack with the inner request handler

at TYPO3\CMS\Core\Http\MiddlewareDispatcher->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/AbstractApplication.php line 85

     * @return ResponseInterface
     */
    protected function handle(ServerRequestInterface $request): ResponseInterface
    {
        return $this->requestHandler->handle($request);
    }

    /**
     * Set up the application and shut it down afterwards

at TYPO3\CMS\Core\Http\AbstractApplication->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/backend/Classes/Http/Application.php line 72

        $request = $request->withAttribute('applicationType', $applicationType);

        // Set up the initial context
        $this->initializeContext();
        return parent::handle($request);
    }

    /**
     * Check if LocalConfiguration.php and PackageStates.php exist

at TYPO3\CMS\Backend\Http\Application->handle(object(TYPO3\CMS\Core\Http\ServerRequest))
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Http/AbstractApplication.php line 97

    final public function run(callable $execute = null)
    {
        try {
            $response = $this->handle(
                ServerRequestFactory::fromGlobals()
            );
            if ($execute !== null) {
                call_user_func($execute);
            }

at TYPO3\CMS\Core\Http\AbstractApplication->run()
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/index.php line 25

// Set up the application for the backend
call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});

at {closure}()
in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/index.php line 26

call_user_func(function () {
    $classLoader = require dirname(__DIR__).'/vendor/autoload.php';
    \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::run(1, \TYPO3\CMS\Core\Core\SystemEnvironmentBuilder::REQUESTTYPE_BE);
    \TYPO3\CMS\Core\Core\Bootstrap::init($classLoader)->get(\TYPO3\CMS\Backend\Http\Application::class)->run();
});

`

Clearing the cache is no longer possible: Clearing caches failed
Clearing caches went wrong on the server side. Check the system for broken extensions or missing database tables and try again.

Running Database Analyser fails and Update Wizzard fails, too.

Its only possible to deactivate the extension and upload a lower version von t3sbootrap.

**Comment by ProWebs** [comment]
This error is gone since changing php7.2 to 7.4 but in fact typo3 10.4.x requirements are matched by using php 7.2.x


TYPO3 10 LTS

The old version with Long Term Support (LTS). It will receive security bugfixes until April 2023.

    Dashboard for editors
    Additional security features for editors and website users
    Improved Site setup and URL handling

System requirements

    PHP 7.2, 7.3 or 7.4
    MySQL 5.5+ / MariaDB / Postgres / SQLite support
    Modern Browsers

**Comment by t3solution** [comment]
... I know that - but what speaks against PHP v7.4 or v8?

**Comment by ProWebs** [comment]
Nothing. But a hint on your change log would be welcome :)
