### ISSUE TITLE
Goolefont Typo?

### ISSUE THREAD

**Issue by peterschoene** [t3solution/t3sbootstrap#280]
I'm getting several Warnings in my log-file like:
 [WARNING] request="65b43f5cdff0b" component="TYPO3.CMS.Core.TypoScript.Parser.TypoScriptParser": No file or folder found for importing TypoScript on "fileadmin/T3SB/Configuration/TypoScript/preloadGooleFonts.typoscript". 
 
 Just checked the git and asked myself if preloadGooleFonts is a typo... but at all the file is not being generated.
 
 Manually generating the file preloadGooleFonts.typoscript(sic!) in the folder above resolves the problem for me.

**Comment by t3solution** [comment]
If you set the constant "bootstrap.preloadGooleFonts" after running the task "CDN to local", you must run that task again.
You should also check if the values ​​of the constant "bootstrap.gooleFontsWeights" are available for that font.
