### ISSUE TITLE
Elements inside a container are not in de correct sorting order

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#282]
T3BS 5.2.6 and Container 2.1.0.

A newly created element or a dragged element does not keep the desired sorting order inside a masonry container.
I can fix it with a work around in List view (cut & paste).

The layout is this:
- masonry container
- containers inside this masonry container
- these containers have content
The containers inside the masonry container keep the position of last added gets the bottom position.

It worked in an earlier stage, a few versions back.

**Comment by t3solution** [comment]
I don't get it - it works as expected for me. 
Is the website with the "problem" online?

**Comment by vmans** [comment]
Sorry, I haven't registered the site+page correctly. Let's leave it for now. In another setup with 5.2.7 and container 2.1.1 I have tested it and the issue is gone. Perhaps it was something else.
