### ISSUE TITLE
PHP8 - Warnings

### ISSUE THREAD

**Issue by MaSa759** [t3solution/t3sbootstrap#283]
Hello,

**PHP** 8.1.12
**Typo3** 11.5.16  & 11.5.17
**t3sbootstrap** 5.2.6

Core: Error handler (FE): PHP  Warning: Undefined array key 1 in  /home/customer/project/htmldocs/typo3conf/ext/t3sbootstrap/Classes/DataProcessing/ConfigProcessor.php  line 389

Core: Error handler (BE): PHP Warning: Undefined array key "cookieconsent_status" in .../vendor/symfony/expression-language/Node/GetAttrNode.php line 97 

Core: Error handler (BE): PHP Warning: Undefined array key "doktype" in /usr/local/www/typo3_src-11.5.17.bak/vendor/symfony/expression-language/Node/GetAttrNode.php line 97 

Any ideas? Thanks!

**Comment by t3solution** [comment]
BUGFIX: https://github.com/t3solution/t3sbootstrap/commit/94e0cee814f43bf0143d9c2631e29e708c7fad64
... GetAttrNode.php line 97 is a Core Bug: https://forge.typo3.org/issues/95781

**Comment by rimmeh8** [comment]
thanks that error is gone, but now a new one appeared.


(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception

PHP Warning: Undefined array key "rowwidth" in /var/customers/webs/XXX/typo3conf/ext/t3sbootstrap/Classes/Helper/GalleryHelper.php line 112

**Comment by t3solution** [comment]
BUGFIX: https://github.com/t3solution/t3sbootstrap/commit/6b1bec7527f78d3cc4994bfc685c45d7ae1f5595
... have you already read the docu? Currently the ext is only ready for php v8.0
but if you like it, you are welcome to send the error messages.

**Comment by peterschoene** [comment]
> BUGFIX: [94e0cee](https://github.com/t3solution/t3sbootstrap/commit/94e0cee814f43bf0143d9c2631e29e708c7fad64) ... GetAttrNode.php line 97 is a Core Bug: https://forge.typo3.org/issues/95781

> Core: Error handler (BE): PHP Warning: Undefined array key "cookieconsent_status" in .../vendor/symfony/expression-language/Node/GetAttrNode.php line 97

Can be fixed with Line 139 in setup.typoscript
[(traverse(request.getCookieParams())['cookieconsent_status']) == 'allow']

and 

> Core: Error handler (BE): PHP Warning: Undefined array key "doktype" in /usr/local/www/typo3_src-11.5.17.bak/vendor/symfony/expression-language/Node/GetAttrNode.php line 97

Line 16 in page.tsconfig
[(traverse(page)["doktype"]) == 198]

According to this solution https://forge.typo3.org/issues/98515#note-6
