### ISSUE TITLE
subheader in Collapsible Element isn´t editable anymore

### ISSUE THREAD

**Issue by ReneFichtner** [t3solution/t3sbootstrap#284]
Typo3 V11.8.18
PHP Version 7.4.32
t3sbootstrap dev-master

The subheader was edited some time (and updates) before and now I just can reach and edit it though sql.
The subheader makes a nice small additonal information in the list of container elements, so it would be nice if it will come back :)

![subheader_field__Frontend](https://user-images.githubusercontent.com/22471935/200970205-ddb75ba5-5d95-41b4-bd23-6752d2191de1.JPG)
![subheader_field_missing](https://user-images.githubusercontent.com/22471935/200968902-74ca8ca9-c320-4690-bdb5-fa07da854454.JPG)
But it is in the database:
![subheader_field_in_DB_existing](https://user-images.githubusercontent.com/22471935/200969136-66865791-8e48-468e-b32a-b9b0a058e955.JPG)

**Comment by t3solution** [comment]
BUGFIX: https://github.com/t3solution/t3sbootstrap/commit/db3942d8481eeda3b37087f87624ff41d403c608

**Comment by ReneFichtner** [comment]
Thanks 4 your help! It´s working again 👍
