### ISSUE TITLE
Video: Poster-tag is empty

### ISSUE THREAD

**Issue by mbsued** [t3solution/t3sbootstrap#285]
I have my png-files with the same name as the video in the directory, but the poster-tag stays empty.
Typo3-Version: 11.5.18

**Comment by mbsued** [comment]
Still doesn't work in 11.5.21 and 5.2.8. Seems the viewhelper splitfileRef has been removed and is no longer called in Resources\Private\Partials\Content\Media\Rendering\Video.html

**Comment by t3solution** [comment]
Did you read in the changelog that some templates - if outsourced - have to be adjusted accordingly?

**Comment by mbsued** [comment]
I did not outsource this template

**Comment by mbsued** [comment]
If i use the splitFileRef-Viewhelper you corrected and call it in Resources\Private\Partials\Content\Media\Rendering\Video.html it works.
`<f:variable name="poster"></f:variable>
<t3sb:splitFileRef file="{file}">
	<f:if condition="{fileParts}">
		<f:variable name="poster">{fileParts.path}{fileParts.filebody}.{fileParts.imgext}</f:variable>
	</f:if>
</t3sb:splitFileRef>`

**Comment by t3solution** [comment]
This is not possible? The view helper has been removed!

**Comment by mbsued** [comment]
You corrected the Viewhelper a few weeks ago i loaded it down from github on 6.12. an used it with 5.2.7. it worked fine.

**Comment by t3solution** [comment]
The viewhelper is no longer needed. However, the posters for the local videos will continue to be provided.
E.g. here: https://www.t3sbootstrap.de/snippets/video-poster

**Comment by mbsued** [comment]
i tested it out it does not work for me with 5.2.8 poster-attribute in video-tag shows only "/"

**Comment by mbsued** [comment]
i think the problem is using the video in Text-pic. If you use it in gallery it seems to work.

**Comment by mbsued** [comment]
Sorry i do not use it with textpic i use it with textmedia but it does not work. i get only the "/" in poster-attribute. This `<f:variable name="poster">/{posters.{rowiterator.index}.poster}</f:variable>` in Resources\Private\Partials\Content\Media\Gallery.html seems not to work

**Comment by t3solution** [comment]
The viewhelper "variable" is not used anymore in the template!
The variable is generated in the "DataProcessor.php" from now.

**Comment by mbsued** [comment]
but you have this in the Resources\Private\Partials\Content\Media\Gallery.html of the Extension: 
`<f:section name="Media">
		<f:for each="{gallery.rows}" as="row" iteration="rowiterator">
			<div class="row">
				<f:for each="{row.columns}" as="column" iteration="iterator">
					<f:if condition="{column.media}">
						<f:variable name="poster">/{posters.{rowiterator.index}.poster}</f:variable>
						<div class="col-sm text-center{f:if(condition: iterator.isFirst, then: ' first-figure')}{f:if(condition: iterator.isLast, then: ' last-figure')}">
							<f:render partial="Media/Type" arguments="{
								file: column.media,
								dimensions: column.dimensions,
								addmedia: addmedia,
								celink: celink,
								poster: poster}" />
						</div>
					</f:if>
				</f:for>
			</div>
		</f:for>
</f:section>
`

**Comment by t3solution** [comment]
... yes, but not in textmedia anymore!
Can I get access to your site?

**Comment by mbsued** [comment]
if i make my own template gallery.html without the variable it works
