### ISSUE TITLE
Link Hover Effect does not work anymore

### ISSUE THREAD

**Issue by tkempf** [t3solution/t3sbootstrap#287]
After migrating from 
TYPO3 CMS 9.5.37 using t3bootstrap 4.5.4 
to
TYPO3 CMS 10.4.32 using t3bootstrap 5.2.6 
and finally
TYPO3 CMS11.5.19 using t3bootstrap 5.2.7 
the link hover effects do not work anymore, 
In the frontend, the migrated css effects which were already present in 9.x still work, but the link on the image is deactivated by class text-hide, which changed from 
.text-hide {
  font: 0/0 a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}
to 
.text-hide {
  display:none;
}
which disables the link itself.
In the backend, there is no dropdown visible which allows selecting the desired hover effect. 
I double checked the corresponding setting in EM config it it is activated, and yes it is, but the dropdown is still not visible.

**Comment by t3solution** [comment]
Hi Thomas,
I can't understand that, for me it works as expected. The option is displayed in the FAL! 
Did you clear the cache after activating the option in the EMconf?

**Comment by tkempf** [comment]
Yes, multiple times, I checked the settings (see the following screenshot).
![Screenshot (25)](https://user-images.githubusercontent.com/2909428/203301150-fe65df62-95c4-459b-877d-835a176d77a3.png)
Migrated Effectes still work and the DB-Field is there. But i can't find the dropdown any longer. Sorry for asking a stupid question, but what do you mean by displayed in the FAL?  I am looking for it where it used to be ...

Here is a Screenshot of one page in original T3 9.x 
![Screenshot (23)](https://user-images.githubusercontent.com/2909428/203301612-3ee1b585-6b08-4ccf-b3cf-8b3fb89183ca.png)

Whereas here is a Screenshot of the same page in migrated T3 11,x 
![Screenshot (22)](https://user-images.githubusercontent.com/2909428/203301412-eb957379-4386-4d06-bd13-e86a74239d8c.png)

**Comment by t3solution** [comment]
... that is strange - this is how it looks to me:
![grafik](https://user-images.githubusercontent.com/5745943/203323287-6c80bd3e-2c3d-4da3-8adc-a9cd8a935d1e.png)
... did you set a TSConfig to hide this option?
Which cType are you using here?

**Comment by tkempf** [comment]
cType is textpic (Text und Bilder).
I did not mess with TSConfig (at least not intentionally). Just did this rather tricky migration from t3 v9 to t3 v10 and then to t3 v11 .
Which TSConfig is it that you mean ?

**Comment by SNMVGlobaltech** [comment]
If you use "Text and images" it does not work, you have to use "Text and Media".

On the other hand, for my part, the links do not work, when I pass the mouse on the image, the animation is done well, but no link possible to the desired page.

**Comment by tkempf** [comment]
I will try it with "Text and Media" (Allthough i think i tested this already)
What you see (working animation with disabled links) could be the result of changing text-hide css class. (See my first post) This was fixed by Helmut in master already
