### ISSUE TITLE
JS conflicts when using shrinking navbar

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#288]
If shrinking navbar is activated in the bootstrap config settings, swiper, lightbox and so on stop working

**Comment by t3solution** [comment]
I cannot confirm this behavior. It is probably due to a JS conflict in your installation.

**Comment by HenryAveMedi** [comment]
I thought that could be the problem, but then i did a complete clean installation with only ur extension. Im running typo3 11.5.17 on php 8.

**Comment by jeino19** [comment]
This is not a problem with conflicting javascript. It's a problem with a missing configuration for the shrinking nav (bootstrap.config.shrinkingNavPadding). If that value is not set, you see an error in the console (Uncaught ReferenceError: x is not defined) which is related to the function t3sbShrinkingNavbar(i,x). See t3sbootstrap/Resources/Private/Partials/Page/Navbar/Assets.html in line 104.

I had the same error just now when I upgraded an Installation from TYPO3 10.4.36 to 11.5.23 and t3sbootstrap from 4.6.3 to 5.2.8.
The constant exists in the version 4.6.3 too, but the padding/offset is calculated in a different way.

**Comment by HenryAveMedi** [comment]
Yes, this was helpfull, it works when i changed py-x to py-1 or something else, thank you
