### ISSUE TITLE
Parallax wrapper not working properly

### ISSUE THREAD

**Issue by codeparts** [t3solution/t3sbootstrap#29]
Hi all,
after updating from some v3 version to 4.4.7 (TYPO3 9.5.15) parallax wrappers are not functioning properly anymore. Is this a known behaviour?
Also in mobile view, parallax isn't working at all, but this already happened in v3.

Kind regards,
Dirk Müller

**Comment by t3solution** [comment]
Hello Dirk,
a test with 9.5.17 and 4.4.7 works as expected for me.
Maybe you have a JS conflict in your installation. Have a look at the console.
BTW: This simple parallax script never worked on mobile.

**Comment by t3solution** [comment]
This should be fixed - if not, you can reactivate this issue.
Beset Regards
Helmut
