### ISSUE TITLE
Modify Flexforms: Modal.xml results in error:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by max951** [t3solution/t3sbootstrap#290]
I tried to modify a flexform field in modal.xml as described in https://www.t3sbootstrap.de/snippets/flexforms/modify-flexforms
`plugin.tx_t3sbootstrap.flexform.modal.fixedPosition.add = dings, bums`

This result in an error message
`PHP Warning: Invalid argument supplied for foreach() in /html/typo3/typo3conf/ext/t3sbootstrap/Classes/Backend/FormDataProvider/FlexFormManipulation.php line 116`

After some debugging i found the problems are the following parts in Modal.xml
`				<type>array</type>
				<TCEforms>
					<sheetTitle>LLL:EXT:t3sbootstrap/Resources/Private/Language/locallang_be.xlf:flexforms.settings</sheetTitle>
				</TCEforms>
`

These values result not in an array in line 116 of file \Classes\Backend\FormDataProvider\FlexFormManipulation.php

I changes line 115 from
`if (!empty($fieldName)) {`
to
`if (is_array($fieldName) && !empty($fieldName)) {`

This fixed the error for me

Used versions:
TYPO3 11.5.19
t3sbootstrap 5.2.7
PHP 7.4.33

**Comment by digitalWorker** [comment]
Same issue here with Bootstrap.xml.

provided fix as pull request.

**Comment by max951** [comment]
Thank you both for sharing the quick solution.
