### ISSUE TITLE
Migrate Card text fields

### ISSUE THREAD

**Issue by jantofw** [t3solution/t3sbootstrap#296]
Typo3 10.4.34, PHP 7.4.33
After updating from t3sbootstrap 5.2.7 to 5.2.8 the wizard "T3SBootstrap - Migrate Card text fields" is not shown under Upgrade Wizard. Instead it says "100%".
Flush all did not make any difference.
Changelog says, the wizard is important and it should be made.

**Comment by t3solution** [comment]
Sorry for my late reply.
You can activate the wizard by clicking on "Mark undone"!

**Comment by jantofw** [comment]
Well, would like to mark it as undone, but it is also there not shown.

**Comment by t3solution** [comment]
Maybe it's already done!?
Search in the DB table tt_content for CType= t3sbs_card.
If you don't have any, everthing is fine!
If you have some and have content in the field "bodytext", everything is fine.
Otherwise you can ask me again!

**Comment by jantofw** [comment]
yep, thanks.
Did not expect to have not any t3sbs_card on this site...
