### ISSUE TITLE
CDN-local TYPO3-installation in subfolder

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#297]
hi,

not a bug but a stumbeling stone.

I installed TYPO3 in a subfolder - https://mysite.de/cms.

After I localized cdn-assets

bootstrap.cdn.enable = 0

the generated js/css-pathes lack of the segment cms
/fileadmin/T3SB/Resources/Public/CSS/bootstrap.min.css     instead of
/cms/fileadmin/T3SB/Resources/Public/CSS/bootstrap.min.css

Is there another way to fix this beside to outsource the includes
@import 'EXT:t3sbootstrap/Configuration/TypoScript/Page/_main.typoscript'
@import 'EXT:t3sbootstrap/Configuration/TypoScript/Lib/_main.typoscript'
@import 'EXT:t3sbootstrap/Configuration/TypoScript/Content/_main.typoscript'
@import 'EXT:t3sbootstrap/Configuration/TypoScript/ContentElement/_main.typoscript'

and to adjust it everywhere (e.g. in IncludeLocal.typoscript)?
bootstrapCSS = /fileadmin/T3SB/Resources/Public/CSS/bootstrap.min.css ==>
bootstrapCSS = fileadmin/T3SB/Resources/Public/CSS/bootstrap.min.css

I don't understand for what the leading slash in needed in that context, because the storage location of the T3SB-folder is fixed to the fileadmin-folder.

Thanks in advance for your hint

**Comment by t3solution** [comment]
Have you set the "base path" in the "fileadmin" file store to "cms/fileadmin/"?

**Comment by wini2** [comment]
No, I haven't (fresh installation with TYPO3 11/t3sbs 5.2.8). Should I? If yes, where can I find the setting it or what I have to?

**Comment by t3solution** [comment]
... you can find it here on page uid =0:
![grafik](https://user-images.githubusercontent.com/5745943/219967872-31dfafdb-3cac-4746-a7ef-cb9ee97e7d29.png)

**Comment by wini2** [comment]
I doesn't help. I toyed around with basePath, baseUri and processingfolder. Beside that I added the path segment to [BE][fileadminDir in the InstallTool and cleared/flushed Cache after every change.

Only output in FE is "503... You are trying to use a method on the inaccessible folder "_processed_"."

**Comment by t3solution** [comment]
... did you set config.absRefPrefix = /cms/
or why is that the path to your fileadmin

**Comment by wini2** [comment]
No I didn't. It's an installation on my developement-environment. I simply use folders to seperate different TYPO3-instances (e.g. mysite.de/cms01, mysite.de/cms02, ...). The typical folders - typo3conf, typo3temp and fileadmin - are subfolders of the respective cms##-folder. I didn't have many disadvantages using this method in the past.

By the way: The installations are symlink-based, not composer installations. In the sites-module configuration I use 'https://mysite.de/cms02/' or just '/' as Entry Point[base].
