### ISSUE TITLE
Fontawesome FA6Pro not loaded

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#299]
I want to replace FA6 Free with FA6Pro. After following all of the steps (https://www.t3sbootstrap.de/extend-t3sbootstrap/font-awesome-pro) and several atempts (on multiple websites), the FA6 Free buttons disappear and leaves a blank spot. No styles and scripts are loaded for FA6Pro.

So I decided to use the FA kit solution (js + svg). That worked, but it shows broken characters in a flash first before the real character is loaded. So I went back to try it all again, following all the steps again, acurately.

Now it changed, so I suspect some caching. But the result is this (I have set it to Pro, really!):

![image](https://user-images.githubusercontent.com/25581914/216322011-219694bd-269f-4adb-88f3-9668d722f0b7.png)

![image](https://user-images.githubusercontent.com/25581914/216321550-f74e54f9-e807-4897-9f65-04eb9933a9b0.png)

As the code inspector tells me, the Fontawesome Free set is still called, the Fontawesome Pro is not.

(Now I could set this up completely by hand but that's not the purpose and that doesn't make it work in the backend editor.)

Latest versions 11LTS and T3SB. No composer in this case (legacy).

By the way, I always hve the broken characters in de editor as well.

**Comment by t3solution** [comment]
Did you also put the required files here: "fileadmin/T3SB/FA6Pro/"?
Otherwise I can not understand it - it works for me as expected.
