### ISSUE TITLE
 Gallery row width auto forces image col width to 25% on imageorient = 26

### ISSUE THREAD

**Issue by schnere** [t3solution/t3sbootstrap#3]
The referenced code line causes the image / text col widths to be forced to 25% / 75% when having the image position set to beside when having the gallery row width set to auto.
This is not what I would expect when setting the value to 'auto' and it's even causing problems when in some cases the width should not be set to a specific percentage.

https://github.com/t3solution/t3sbootstrap/blob/5fffe51e4bd103e681006cb5ddc52ef8117c8790/Classes/Helper/GalleryHelper.php#L41

**Comment by t3solution** [comment]
The "Gallery row width in%" is optional. You can select the option "none" in the select field to prevent the percentage width.

**Comment by schnere** [comment]
Ah, I see, thank you very much. 
It was a bit confusing as it was on 'auto' before the update of the extension and didn't set the width.
