### ISSUE TITLE
Content Consent does not work

### ISSUE THREAD

**Issue by alpin3rocker** [t3solution/t3sbootstrap#30]
Hi,
t3sbootstrap: 4.4.7
TYPO3: 10.4.2
Frontend Error: Class T3sbootstrap\Controller\ConsentController does not exist. Reflection failed.
Also the thumbnail background area in the Plugin offers only SYS, FILE as allowed relations and it's not possible to choose a element as background-image
Thank You

**Comment by t3solution** [comment]
Here is the bugfix: https://github.com/t3solution/t3sbootstrap/commit/ff63d20c240613479f238eea6bf472cebf4e20d3

**Comment by alpin3rocker** [comment]
Hi,
thank you! The content load correct now, but how can i choose a background Image for the Content? You got a donation
![content-consent](https://user-images.githubusercontent.com/5285315/82979734-1c0c0400-9fe8-11ea-8473-d6c74df533b9.png)
Thank You

**Comment by t3solution** [comment]
Docu for YouTube videos: https://www.t3sbootstrap.de/dokumentation/snippets/extend-t3sbootstrap/contentconsent
Docu for local videos: https://www.t3sbootstrap.de/dokumentation/video-poster
Is that a solution for you?

**Comment by alpin3rocker** [comment]
no sorry, it is a youtube video link not a local hosted one. I know the Docs for t3sbootstrap content consent. The section for the background image offers only SYS and FILE but this is only in TYPO3 10.x.x in TYPO3 9.5.x it is working fine... You know what i mean?
![csm_Bildschirmfoto_2019-04-26_um_20 03 58_6be5f3d459](https://user-images.githubusercontent.com/5285315/82996750-bc245600-a005-11ea-98f4-b2ef8e0a9812.png)

**Comment by t3solution** [comment]
This should fix the problem: https://github.com/t3solution/t3sbootstrap/commit/872f73958395022c37f737722f8aab0a776795cc

**Comment by alpin3rocker** [comment]
Yes, now it works! Thank you for your awesome work and for sharing.
Stay healthy!
