### ISSUE TITLE
For latest fontawesome use, .fa-solid,.fa-regular,.fa-light,.fa-thin,fa-duotone,.fa-sharp

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#300]
Suggestion:

change
`.fa,.fab,.fal,.far,.fas{line-height:inherit}`
into
`.fa,.fab,.fal,.far,.fas,.fa-solid,.fa-regular,.fa-light,.fa-thin,fa-duotone,.fa-sharp{line-height:inherit}`
in t3sbootstrap.css

since ".fa-solid" and so is what you get when you copy an icon from the fontawesome website.

**Comment by t3solution** [comment]
… did you try the new option „Downloadable Kits“ from Fontawesome?

https://blog.fontawesome.com/downloadable-kits-are-here/ <https://blog.fontawesome.com/downloadable-kits-are-here/>

Better/faster loading and no „flash“ before loading!

Best Regards
Helmut

**Comment by t3solution** [comment]
BUGFIX is done: https://github.com/t3solution/t3sbootstrap/commit/0505542d46d6bc473db899ba3e816bd9a576eeb5
