### ISSUE TITLE
HTML Validation fails

### ISSUE THREAD

**Issue by claude27** [t3solution/t3sbootstrap#301]
Hi, 

the validation problem as described in [#172](url) still exists. At the end there is a 0 value "0w".
Check for example the t3sbootstrap website:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.t3sbootstrap.de%2Fdemo%2Ftextmedia

Error: Bad value for attribute srcset on element [source](https://html.spec.whatwg.org/multipage/#the-source-element): Expected number greater than zero but found 0 at …pie.JPG.webp 0w.
Error: Bad value for attribute srcset on element [source](https://html.spec.whatwg.org/multipage/#the-source-element): Expected number greater than zero but found 0 at …pie.JPG.webp 0w.
...

**Comment by t3solution** [comment]
This workaround should fix the problem: https://github.com/t3solution/t3sbootstrap/commit/cf5958cda4c07a6e8957677e528283f61bfe0015

**Comment by claude27** [comment]
Thanks, it's better, but now I still get one validation error on one whole page:
Error: Bad value for attribute srcset on element source: Must contain one or more image candidate strings.
From line 33, column 30216; to line 33, column 30318
 100vw" /><source srcset="" media="(min-width: 576px)" sizes="(min-width: 99px) 99px, 100vw" type="image/webp" /><source>

I solved this now by changing the line 426 of ResponsiveImageUtility.php from
if ($srcsetMode === 'w' && $processedWidth !== $candidateWidth) {
to
if ($srcsetMode === 'w' && $processedWidth !== $candidateWidth && ($processedWidth > 0)) {

It seems that your bugfix is then not extra needed.

**Comment by claude27** [comment]
PS: Your bugfix is also needed, I detected today.
