### ISSUE TITLE
When page is hidden from menu, section menu is also hidden on that page

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#305]
When page is hidden from navigation, section menu is also hidden on that page. I think that is not the way it should be.
And when I set the page to nav_hide = 0, the section menu shows up.

I'm not sure if this is an effect of T3BS. Now I see this, I also suspect that it occurs on pages after a log in for page menus and section menus.

(11LTS and T3BS 5.2.8)

**Comment by t3solution** [comment]
You can fix this behavior with the following line of TypoScript:
page.10.dataProcessing.60.special.value.override >
