### ISSUE TITLE
Undefined array key "theadClass"

### ISSUE THREAD

**Issue by jantofw** [t3solution/t3sbootstrap#306]
typo3 11.5.25
php 8.1
when using contentelement table and showing it in frontend the backend log shows:

Core: Error handler (FE): PHP Warning: Undefined array key "theadClass" in pathxyz/typo3conf/ext/t3sbootstrap/Classes/ContentElements/Table.php line 37

the line in Table.php codse is
$processedData['theadclass'] = $flexconf['theadClass'];

So $flexconf['theadClass'] is not set?

**Comment by jantofw** [comment]
forgot to mention:
t3sbootstrap 5.2.8

**Comment by t3solution** [comment]
Here is the BUGFIX - https://github.com/t3solution/t3sbootstrap/commit/8a02bbd7526f8ce07b88c253d8526a3e0bf03cdc
