### ISSUE TITLE
503 Oops, an error occurred! Incorrect integer value: '' for column 'navbar_dark_mode' at row 1

### ISSUE THREAD

**Issue by hanwa11** [t3solution/t3sbootstrap#308]
when creating a new main configuration this error appears:
503
Oops, an error occurred!
Incorrect integer value: '' for column 'navbar_dark_mode' at row 1
t3 11.5.25
t3s 5.2.9

**Comment by t3solution** [comment]
Did you update the DB under "Maintenance" - "Analyze Database"?

**Comment by hanwa11** [comment]
The error was with a new installation. I installed 5.2.8 first and then updated to 5.2.9. Here the error no longer occurs.
