### ISSUE TITLE
Mistake in the "Multidomain Setup"-documentation

### ISSUE THREAD

**Issue by Cretection** [t3solution/t3sbootstrap#31]
There is an mistake in the documentation under Multidomain Setup (https://www.t3sbootstrap.de/dokumentation/snippets/css-scss/custom-scss).

In the documentation:
```
page {
	includeCSS {
		customBootstrap = uploads/tx_t3sbootstrap/bootstrap-88.scss
		customBootstrap.forceOnTop = 1
	}
}
```

Corrected documentation:
```
page {
	includeCSS {
		bootstrapCustom = uploads/tx_t3sbootstrap/bootstrap-88.scss
		bootstrapCustom.forceOnTop = 1
	}
}
```

Regards,
Jonathan

**Comment by t3solution** [comment]
Hello Jonathan,
thanks for the info - I corrected it!
Beste regards
Helmut
