### ISSUE TITLE
wrong image size calculated in small_column

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#32]
line 523 in GalleryProcessor.php calculates wrong image size in this case because `pages.override.smallColumns` is not taken into account:

- pages.override.smallColumns = 4 is set in constants
- field tx_t3sbootstrap_smallColumns = 1 in page record
- t3sbootstrap 4.4.7 (was ok until 4.4.2)

Background: We set pages.override.smallColumns = 4 and hide field tx_t3sbootstrap_smallColumns from editors to keep it simple and clean. Additionally TCAdefaults.pages.tx_t3sbootstrap_smallColumns = 4 is set. But this does not ensure that field tx_t3sbootstrap_smallColumns is always set to 4 because sometimes there are old pages or pages are created in an way where TCAdefaults are not applied (e.g. changing BE Layout).

Workaround: Set field tx_t3sbootstrap_smallColumns to desired value by DB update

**Comment by t3solution** [comment]
This bugfix should fix your problem: https://github.com/t3solution/t3sbootstrap/commit/8cc7a2b6a3b3f6922b843c9c49e6c4d7a6ccef20

**Comment by peerlight** [comment]
Thanks, additionally it solves the problem with calculation in calculateMediaWidthsAndHeights()

In line 501 you only rely on TCAdefaults. Isn't pages.override.smallColumns set in constants respected in any way? This should supersede TCAdefaults or am I wrong?

**Comment by t3solution** [comment]
You're right! The following will fix it:
https://github.com/t3solution/t3sbootstrap/commit/2573fe56654726f67d0b7d127785583746ecec66
https://github.com/t3solution/t3sbootstrap/commit/c2773e74acfd86e90720026b82bd1bc9cffa5624
https://github.com/t3solution/t3sbootstrap/commit/e18ef24056b3e10dac6466bf3dbae68471520381
