### ISSUE TITLE
Paginator ommits first page in every array

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#334]
t3sb 5.2.20 / 12LTS / PHP8.1

In any setup that I try, the first page in an array of pages that should be as a link in the pagebrowser, is not there.

I have the same setup in other older versions where it runs perfectly. I have tried to sort it out without success, and I cannot imagine that this is a t3sbootstrap issue, but is it a TYPO3 bug then?

**Comment by t3solution** [comment]
Can you be more specific about the problem?

**Comment by vmans** [comment]
https://github.com/t3solution/t3sbootstrap/assets/25581914/573c91f9-4059-4ad6-8fc9-36acad139db1

**Comment by t3solution** [comment]
Upgrade to TYPO3 v12.4.3 should help
