### ISSUE TITLE
Scheduler, cdnToLocal, results in 503: fwrite(): Argument #2 ($data) must be of type string, bool given

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#337]
TYPO3 12LTS / T3SB 5.2.20 / PHP8.1

When trying cdnToLocal in Scheduler.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: fwrite(): Argument #2 ($data) must be of type string, bool given | TypeError thrown in file /var/www/.../web/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php in line 1579. Requested URL: https://.../typo3/module/scheduler?token=--AnonymizedToken--

**Comment by t3solution** [comment]
Here is the bugfix: https://github.com/t3solution/t3sbootstrap/commit/7dfe9022650f01961788839507d4359f11c726ec
