### ISSUE TITLE
PHP Warning: Undefined variable $flexconfOut

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#341]
12LTS / T3SB 5.2.20 / PHP8.1

PHP Warning: Undefined variable $flexconfOut in /../vendor/t3sbs/t3sbootstrap/Classes/Backend/Preview/DefaultPreviewRenderer.php line 121

```
   if ( !empty($flexconf['bgOverlay']) ) {
    $flexconfOut .= 'bgOverlay=1, ';
   }
```

It seems to be in a Bootstrap Carousel Item with image in the background. I assume you know it when you see it. But if you need more info, I can test to be sure of the details.

**Comment by t3solution** [comment]
Bugfix is here: https://github.com/t3solution/t3sbootstrap/commit/d8f62ba40b28d2394a110dd6f38eca09bf1f6a24
