### ISSUE TITLE
text/media element rendering in 2 ways - srcset missing

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#343]
2 systems, each 11.5.29 / t3sb 5.2.13, both same config, both using text/media element.
system 1 is rendered as it should be, with source/srcset images, gallery class and respects the extra class in e.g. figure.
 
![image](https://github.com/t3solution/t3sbootstrap/assets/47745128/9737b77c-9b23-4298-9354-c01e843c0109)

system 2 is also using text/media but is rendering withput sorce/srcset, uses teh ce-gallery class and do not respect the extra classes, set in figure or img-tag.

![image](https://github.com/t3solution/t3sbootstrap/assets/47745128/44525e73-3ba8-4c62-9f11-79f6d15fdd11)

i don't know why?

**Comment by t3solution** [comment]
... the class="image-embed-item" does not come from t3sbootstrap!
The "problem" is somewhere in your installation

**Comment by asche76** [comment]
thanks for the reply. i downed the whole site and searched it and the DB, can't find anything. then it should be so :D

**Comment by asche76** [comment]
this problem is caused bei media2click ext. if you are using this ext, text/media content will be rendered with the core fluid_styled_content ext. if you remove fluid_styled_content from include TS, then a error occures -> no rendering definition.
therefore i'm now using content_consent.
