### ISSUE TITLE
Wrong CSS generated when using Font "Source Sans 3"

### ISSUE THREAD

**Issue by tkempf** [t3solution/t3sbootstrap#346]
By Compiling SCSS in the backend with a bs-variable as follows

$font-family-base:            "Source Sans 3";

the quotation marks get stripped at compiling which leads to the following entry in the .css file

--bs-body-font-family: Source Sans 3;

This does not work without qutoation marks, so the Standard Font is used.

**Comment by momostafas** [comment]
By using unquote() around the variable, the generated CSS will include the quotation marks, and the --bs-body-font-family variable will be correctly set to "Source Sans 3". 

`
$font-family-base: "Source Sans 3";

:root {
  --bs-body-font-family: unquote($font-family-base);
}

`

**Comment by tkempf** [comment]
Hello Mohamed,
unquote did not work for me, but you brought me to the right direction. I found the followin comment in bootstraps "_root.scss" file:
  // Note: Use `inspect` for lists so that quoted items keep the quotes.
  // See https://github.com/sass/sass/issues/2383#issuecomment-336349172
So using:
:root {
  --#{$prefix}body-font-family: #{inspect($font-family-base)};
}
worked for my case
