### ISSUE TITLE
cropvariants and lightbox

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#358]
Not a bug but maybe worthy of consideration.

It seems the Desktop-variant is used for the lightbox. This means that if the Desktop-Image is cropped, the complete image never shows up, even if the variants for tablet or mobile are not cropped. For tt_news (independent from t3sbs) I managed to shop up the full-image by the useage of 
src="{f:uri.image(image: mediaElement, cropVariant: 'default')}"  in a cropvariant adopted MediaImage.html-Template.

I couldn't find something similar in the t3sbs-templates, so I would be thankfull for a hint.

Beside that, I think it would be solution to add a checkbox in the backend so editors can control if the full or the cropped image should be used for the lightbox.

**Comment by t3solution** [comment]
As a workaround, you can adjust the following in the template Partials/Content/Media/Type/Image.html:
From:
<ce:link.clickEnlarge image="{**file**}" configuration="{settings.media.popup}">
To:
<ce:link.clickEnlarge image="{**file.originalFile**}" configuration="{settings.media.popup}">

**Comment by wini2** [comment]
Thanks a lot. Simple, but effective!
