### ISSUE TITLE
Card Slide issue

### ISSUE THREAD

**Issue by rincewind0803** [t3solution/t3sbootstrap#37]
Hi,
I set up a Card Slider with 4 images, exactly as shown on you demo site, but it looks like there are 2 empty slides at the end before it starts over with slide 1.
I cant find any documentation on this, is there any place i have to adjust the number of images.
Update: The actual number of images does not make a difference, if i put in 6 images two more empty Cards are shown before it starts over.

Greetings 
Marcus

**Comment by rincewind0803** [comment]
Typo3 10.4.4 
t3sbootstrap 4.4.7 
Demo https://mittler.garnichts.com/github

**Comment by t3solution** [comment]
Hello Marcus,
... bugfix here: https://github.com/t3solution/t3sbootstrap/commit/eaeb1ddea25e5df2c019b5ef5ffe781d3ba54b68

Best regards
Helmut

**Comment by rincewind0803** [comment]
Unfortunately this fix will pull down header slides at the d of the card slides ...
Demo https://mittler.garnichts.com/github

**Comment by t3solution** [comment]
Hello Marcus,
try this bugfix https://github.com/t3solution/t3sbootstrap/commit/0423a1408d65309300bdb34315e3cf4dfd6c69e4
This should fix the problem with multiple sliders on one page

**Comment by rincewind0803** [comment]
Dear Helmut,
Excellent ! 
This also fixes an additional bug when theres only one slide in the Jumbotron. Originally these also were pulled down after each Cycle.

Thank you so much !
