### ISSUE TITLE
Issue connector to in2code-de/luxletter "Javascript in mail markup t3sbootstrap"

### ISSUE THREAD

**Issue by PittRo** [t3solution/t3sbootstrap#377]
I'd like to connect this issue with https://github.com/in2code-de/luxletter/issues/206
Would you please so kind and take a stand on this?
Thx

**Comment by t3solution** [comment]
Hi Pitt,
you can try the following:

In the file IsInline.php insert the following after line 33:

```
        $request = $GLOBALS['TYPO3_REQUEST'];
        $frontendController = $request->getAttribute('frontend.controller');
        if ($frontendController->page['doktype'] !== 1) {
            return;
        }
```

and test the E-Mail posting again!

If it works for you I will add it to the script - need your reply!

**Comment by t3solution** [comment]
... maybe here is a better solution:

... in the file IsInline.php insert the following after line 40:

```
        if (!empty($settings['disableInlineJs'])) {
            return;
        }
```

Now you can set the following setting:
`
plugin.tx_t3sbootstrap.settings.disableInlineJs = 1`

**Comment by t3solution** [comment]
... I have just realised that you are using the bootstrap_package and not t3sbootstrap.
So I will close this issue here!

**Comment by PittRo** [comment]
@t3solution perfect, this was the solution, would you please merge it in main?

**Comment by t3solution** [comment]
... is done!
