### ISSUE TITLE
Cookie Consent not working

### ISSUE THREAD

**Issue by fxp66** [t3solution/t3sbootstrap#38]
I have an issue to put in the Matomo tracking code into Cookie Consent.
What is the wright syntax?

`[T3SBS\T3sbootstrap\UserFunction\CookieCondition Opt-In-Allow]
enable cookies (var _paq = window._paq || [];_paq.push(['trackPageView']);_paq.push(['enableLinkTracking']);(function() {var u="https://statistic.com/";_paq.push(['setTrackerUrl', u+'matomo.php']);_paq.push(['setSiteId', '1']);var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);})();) - type: opt-in, status: allow

[global]
[T3SBS\T3sbootstrap\UserFunction\CookieCondition Opt-Out-Deny]
disable cookies () - type: opt-out, status: deny
[global]`

I think this wrong, the cookie is testet and working. Please help to note the script correctly

THX fxp

**Comment by t3solution** [comment]
Hello fxp,
you should use typoscript within the condition.
Something like:
[T3SBS\T3sbootstrap\UserFunction\CookieCondition Opt-In-Allow]
page.jsInline {
    10 = TEXT
    10.value (
	    // your js code
    )
}
[global]

**Comment by fxp66** [comment]
Hello Helmut,
thank you, this was an absolute stupid question, but I'm not so familiar with TS.
Everything is working well now.

regards fxp
