### ISSUE TITLE
Content Type Image does not center image subscription and misalignes copyright note

### ISSUE THREAD

**Issue by Shotte** [t3solution/t3sbootstrap#381]
TYPO3 V12.4.11
T3SB V5.3.4

After migrating from Typo 11.5 to 12.4 inc. T3SB upgrade to 5.3.4 I got in trouble with content element picture. After adding single picture incl. center alingnment for picture subscription and picture positioning at "top center", the subscription isn't centered.

In addition I added a copyright note which disappears, because it is positioned to the very right side of the page. 

Using previous Typo version with related T3SB version, everything was fine.

Here some pictures for more illustation what happened:

![page-positioning](https://github.com/t3solution/t3sbootstrap/assets/6080354/11330c40-05e2-434c-b0fc-e4949484359d)
![settings](https://github.com/t3solution/t3sbootstrap/assets/6080354/e19e118a-7259-4ffd-952d-608386420b21)
![settings2](https://github.com/t3solution/t3sbootstrap/assets/6080354/53ab11ef-0da8-4cec-92f7-3e929e7ee3a1)
![content](https://github.com/t3solution/t3sbootstrap/assets/6080354/a16c6295-09bb-4f4a-9f0c-30cfd40bfc1d)
![copyright](https://github.com/t3solution/t3sbootstrap/assets/6080354/92d02a96-2044-4bf7-9235-7eadccf9a175)
![figure-caption](https://github.com/t3solution/t3sbootstrap/assets/6080354/dbb1e82c-1833-4f10-a3e0-5846a3d8340d)

**Comment by t3solution** [comment]
There is a new version 5.3.4 (BUGFIX release)

**Comment by Shotte** [comment]
@t3solution 
Thank you for your quick response and lightnig fast patch, but how to get it via composer? Or do I need to fetch it via git?

**Comment by Shotte** [comment]
@t3solution 
Thank you very much for your quick r4esponse and lightning fast patch. It looks now very good again. Issue seems to me solved.
