### ISSUE TITLE
Container in Footer should be independent of Page tx_t3sbootstrap_container

### ISSUE THREAD

**Issue by us14v** [t3solution/t3sbootstrap#39]
Hi,
t3sbootstrap is set up to use content from a page (id=13) in BE-Module. Container ist set to none.  Slide is true.
The content on page id=13 is as follows  
```html
<section class="ge ge_background_wrapper">
    <!-- content element BG Wrapper with tx_t3sbootstrap_container = no container -->
    <div class="container">
        <div class="fsc-default">
            <!-- content element with tx_t3sbootstrap_container = container -->
        </div>
    </div>
</section>
```
Then i create a new page and set `Container (for the whole page)[tx_t3sbootstrap_container] = container` which results all content elements in `#page-footer` lose their container on that page. Even though `#page-footer` is outside of `#page-wrapper` and should render independent of Page settings.  

How would i go on to have Footer always render the same, regardless of what `Container (for the whole page)[tx_t3sbootstrap_container]` is set to?

**Comment by us14v** [comment]
Forgot to mention: the same goes for containers in Megamenues!

**Comment by t3solution** [comment]
The new version should fix your problem!?

**Comment by t3solution** [comment]
... did you still have the problem or can I close this issue?

**Comment by us14v** [comment]
Sorry for the late replay... was on vacation.
Yes, the issue is gone and can be closed now. Thanks again for this amazing Extension!
