### ISSUE TITLE
Warning: Undefined array key "menudirection"

### ISSUE THREAD

**Issue by Hobokens** [t3solution/t3sbootstrap#399]
TYPO3 12.4.17
t3sbootstrap 5.3.12

I get the following warning several times in my log:

`Core: Error handler (FE): PHP Warning: Undefined array key "menudirection" in /www/htdocs/w0144cf7/my-domain.de/typo3conf/ext/t3sbootstrap/Classes/ContentElements/Menu.php line 23`

**Comment by t3solution** [comment]
what kind of menu did you use on the page?

**Comment by Hobokens** [comment]
The website is a onepager  with some subpages.
The Landing Page has a section menu. The subpages have a submenu (class menusubpages).

**Comment by t3solution** [comment]
Is fixed with v5.3.13

**Comment by Hobokens** [comment]
Thanks for the fix.
