### ISSUE TITLE
migrate gridelements tt_content.tx_t3sbootstrap_flexform from v3.3.2 to v.4.41 

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#4]
Hi,
is there a way to get this done automatically? Right now I open and save the content elements. But well, there are lots of them.

**Comment by TrueType** [comment]
Possibly, if the values are not set, take the same default values, which are set in new grid elements?

**Comment by TrueType** [comment]
php72 ./vendor/bin/typo3 cleanup:flexforms does not help

**Comment by t3solution** [comment]
If you should have kept your installation up to date, you would not have this problem now. Up to version 3.2.43 I offered an update script ...
Sorry, but you cannot expect a free support here!

**Comment by TrueType** [comment]
I don't expect anything. But I may be able to contribute. I checked the update scripts. I could not see they cover the tt_content.tx_t3sbootstrap_flexform and the "appearance" value. I suggested to programmatically use the standard value "accordion", if the value is not set. Or write an update script. Please let me know, if one of these approaches makes sense. I may then provide a PR.

**Comment by TrueType** [comment]
done manually. Some parts could just copy complete flexform column on database.
