### ISSUE TITLE
parent element link in dropdown navbar not working properly

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#40]
t3sbootstrap 4.4.8
typo3 10.4.5

parent element link in navigation menu is not rendered properly, it just renders the page you are ON at the moment

I havent researched were the problem lays if on the templates or on the setup

**Comment by t3solution** [comment]
Hello Henry,
can you explain that in more details?

**Comment by HenryAveMedi** [comment]
I upgraded to typo3 10.4.5 and gridelements and bootstrap, and at the first glance everything looks great, and then i realized that the navigation isnt working properly.
I use the dropdown menu navigation in my site…
when navbar template comes to this part:
`<f:if condition="{navbarItem.children} && {config.navbar.enable} != 'slide'">
              <f:then>
                <f:render section="Dropdown" arguments="{_all}" />
              </f:then>
              <f:else>
                <f:link.typolink class="nav-link" parameter="{navbarItem.link}"
                    title="{f:if(condition:'{navbarItem.data.tx_t3sbootstrap_icon_only}',then:'{navbarItem.title}',else:'')}"
                    target="{f:if(condition: '{navbarItem.target}',then: '{navbarItem.target}', else: '_self')}">
                  <f:render section="Title" arguments="{item: navbarItem}" />
                </f:link.typolink>
              </f:else>
            </f:if>`
a menu item without children, renders the link to the proper page… but when it goes to render dropdown section, something there in the link is wrong…… because it renders the link of the page you're on in FE instead of the page in page tree

`<a class="nav-link dropdown-toggle" id="dropdown-menu-{navbarItem.data.uid}" href="{f:uri.page(pageUid: navbarItem.data.uid)}" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="{f:if(condition:'{navbarItem.data.tx_t3sbootstrap_icon_only}',then:'{navbarItem.title}',else:'')}">`

**Comment by HenryAveMedi** [comment]
ok, i solved it, it was a template problem indeed

*Note: in my site i removed some parts that just dont make sense…… in the link title u build a condition for the fontawesome icon, this makes no sense, since the link title is hidden and for SEO or usability purposes, i removed that condition…… and being so i reduced the code. It allows me to just make 1 dropdownlink instead of 2 different ones if icont is wanted or not.
And then render the inside of the link with the section="Title" which makes more sense

so, to the bug => {f:uri.page(pageUid: navbarItem.data.uid)}
it seems this has another behavior in typo3 10… so i replaced it with {navbarItem.link}
Works perfectly, with open on hover, open on click, and open parent if dropdown is open

all that being said these are my new sections in template… i changed the title section as well, because I build a span class="nav-label" in my navi when icons are present so i can hide the text via css in tablets and leave the icons visible

`
<f:section name="Dropdown">
  <a class="nav-link dropdown-toggle" id="dropdown-menu-{navbarItem.data.uid}" href="{navbarItem.link}" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="{navbarItem.title}">
    <f:render section="Title" arguments="{item: navbarItem}" />
  </a>
  <f:if condition="{config.navbar.megamenu} && {navbarItem.data.tx_t3sbootstrap_megamenu} && {navbarItem.data.doktype}==4 && {navbarItem.children}">
      <f:then>
      <f:comment> removed by JS if narrower than navbarBreakpoint :: page.jsFooterInline.5.151 ff :: don't remove remove-{navbarBreakpoint} </f:comment>
      <div class="dropdown-menu mega-dropdown-menu remove-{navbarBreakpoint}" aria-labelledby="dropdown-menu-{navbarItem.data.uid}">
        <f:cObject typoscriptObjectPath="lib.dynamicContent" data="{pageUid: '{navbarItem.data.uid}', colPos: '0'}"/>
      </div>
      <f:comment> removed by JS if wider than navbarBreakpoint :: page.jsFooterInline.5.151 ff :: don't remove show-{navbarBreakpoint} </f:comment>
      <div class="dropdown-menu{f:if(condition: navbarItem.data.tx_t3sbootstrap_dropdownRight, then:' dropdown-menu-right')} show-{navbarBreakpoint}" aria-labelledby="dropdown-menu-{navbarItem.data.uid}">
        <f:render section="DropdownItem" arguments="{_all}" />
      </div>
      </f:then>
      <f:else>
      <div class="dropdown-menu{config.navbar.dropdownAnimate}{f:if(condition: navbarItem.data.tx_t3sbootstrap_dropdownRight, then:' dropdown-menu-right')}" aria-labelledby="dropdown-menu-{navbarItem.data.uid}">
        <f:render section="DropdownItem" arguments="{_all}" />
      </div>
      </f:else>
  </f:if>
</f:section>

<f:section name="Title">
  <f:if condition="{item.data.tx_t3sbootstrap_fontawesome_icon}">
    <f:then>
      <f:if condition="{item.data.tx_t3sbootstrap_icon_only}">
        <f:then>
          <i class="{item.data.tx_t3sbootstrap_fontawesome_icon}"></i>
        </f:then>
        <f:else>
          <i class="{item.data.tx_t3sbootstrap_fontawesome_icon}"></i>
          <span class="nav-label">{item.title}</span>
        </f:else>
      </f:if>
    </f:then>
    <f:else>
      {item.title}
    </f:else>
  </f:if>
</f:section>
`

**Comment by t3solution** [comment]
Hi Henry,
you have probably outsourced a template and not updated it - for me it works as expected.
Best regards
Helmut
