### ISSUE TITLE
carousel button with link doesn't work anymore

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#41]
I honestly didn't realized in which update this bug happened, but it used to work…… now no button gets rendered when that option is selected in the carousel container
<img width="211" alt="image" src="https://user-images.githubusercontent.com/51093175/88228219-20af0a80-cc6f-11ea-8bf1-145364f7fbc4.png">

**Comment by t3solution** [comment]
Hi Henry,
you have to enter a header and a header-link in the carousel (t3sbs_carousel), then it works!
Best regards
Helmut
