### ISSUE TITLE
Profile cards do not consider left alignment on mobile

### ISSUE THREAD

**Issue by Shotte** [t3solution/t3sbootstrap#418]
t2sb 5.3.18, Typo 12.4.22
Profile cards do not consider left alignment on mobile devices. On PC (Firefox, Opera, Chrome) everything looks good but on mobile devices (Samsung, Huawaei) is the text and the rounded picture centered centered, even though the setting is explicitly set to left alignment.

**Comment by t3solution** [comment]
You have probably set “Card Alignment” to “center”!

**Comment by Shotte** [comment]
@t3solution Thank you for your quick response. 

I need to change the setting "Card Alignment" from "Standard" to "Left". Standard leeds for PC usage to still left alignment but for mobile devices (based on other resolution I guess) to a centered alignment.

However, this solved my issue. Thank you.
