### ISSUE TITLE
HTML-Validation fails because of missing src-attribute for images

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#42]
hi,

using https://validator.w3.org shows lots of  "Error: Element img is missing required attribute src."

the output looks like (for example)

```
<figure>
	<picture>
		<source srcset="
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_903f616409.jpg 1200w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_188a49bef5.jpg 1360w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_36d4d6cc45.jpg 1600w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_bf112221ff.jpg 1920w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_d32ac2f89c.jpg 2560w" 
		media="(min-width: 1200px)" 
		sizes="(min-width: 2560px) 2560px, 100vw" 
		/>

		<source srcset="
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_a68268938d.jpg 576w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_7129c69100.jpg 992w, 
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_c3508bd8aa.jpg 1199w" 
		media="(min-width: 576px)" 
		sizes="(min-width: 2560px) 2560px, 100vw" 
		/>

		<source srcset="
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_fc17b8f41b.jpg 575w" 
		media="(max-width: 575px)" 
		sizes="(min-width: 2560px) 2560px, 100vw" 
		/>

		<img class="img-fluid orig-img" srcset="
		/cms37/fileadmin/_processed_/2/e/csm_KONTAKT_d32ac2f89c.jpg" width="2560" alt="" 
		/>
	</picture>
</figure>
```

it seem that the fallback/default-image ist not set in Partials/Content/Media/RenderingImage.html or the in MediaViewHelper.php

t3sbs 4.4.7/TYPO3 10.4.4

**Comment by t3solution** [comment]
Hello,
this should be fixed with the new Version 4.5.0!

**Comment by wini2** [comment]
Hi Helmut,
thank you for fixing. would you please be so kind to tell me, if it is possible to make it work with 4.4.7 because i can't update at the moment.

**Comment by t3solution** [comment]
... in the file "/Classes/Utility/ResponsiveImagesUtility.php" you have to comment out the line 
"$attributePrefix = $lazyload ? 'data-' : '';" 
in the method "createPictureSourceTag" and "createSimpleImageTag" 
remain the line in "createPictureTag".
That should work!

**Comment by wini2** [comment]
there are 4 occurances of $attributePrefix = $lazyload ? 'data-' : '';   (in Line 96, 195, 302 and 349). The expression 'createPictureTag' only occurs in public function createPictureTag (Line 158).  So i commented out Line 96, 302 and 349 - but without success.

btw. cache is cleared (of course).

**Comment by t3solution** [comment]
... you can compare with this file: https://github.com/t3solution/t3sbootstrap/blob/master/Classes/Utility/ResponsiveImagesUtility.php
The commented lines are still in the file!

**Comment by wini2** [comment]
sorry, but that does not work.

comparing 4.4.7 with 4.5.0 it is obvious that old occurance in line 96 does not extist anymore. old 195/ new 101 is in use. old 302 and 349 are commented out (like in 4.5.0). nothing changes, no matter if 96 is commented or not.

cache ist cleared and, as a precaution, processed images are deleted.

**Comment by t3solution** [comment]
Did you still have a problem or can we close the issue?

**Comment by wini2** [comment]
the problem persists. i tried a lot of setting by commenting or uncommenting $attributePrefix = $lazyload ? 'data-' : ''; - without success. the 4.4.7 version i use is the one with the patches you offer here. can this be responsible for the unexcpected behaviour?

**Comment by t3solution** [comment]
... maybe you have to upgrade your lazyload-script - Constant:
bootstrap.cdn.lazyload = 17.1.0

**Comment by wini2** [comment]
lazyload is not the source of trouble, it's picturefill. the patched version of ResponsiveImagesUtility.php works when deactivating 
bootstrap.image.picturefill = 0

i tried to use picturefill only in conjunction with ie using a condition

[request.getHttpUserAgent(Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko) == 1]
bootstrap.image.picturefill =1
[end]

but it isn't working. is my idea wrong?

**Comment by t3solution** [comment]
... there is a new condition (since 4.5.1) to detect a browser name:
https://www.t3sbootstrap.de/dokumentation/conditions

**Comment by wini2** [comment]
thanks for your instant help!

i added 
[browser('Internet Explorer')]
bootstrap.image.picturefill =1
[END]
to my constants, but it seems that picturefill isn't working in ie.

by the way: the 'missing src-problem' is also present in 4.5.0 if picturefill is activated.
