### ISSUE TITLE
FA6-Kit not working because it's not copied into _assets

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#425]
When I use the t3sb-package, and everything is installed as supposed, and I want to implement the FontAwesome kit in the CKEditor (I use the Pro version), my final step is this action:

`cp -r vendor/t3sbs/t3sb-package/T3SB/Resources/Public/FA6-Kit public/_assets/81d415137a1f642a138f8273fcd813ac
`

That shouldn't be necessary, so what am I missing / isn't documented?

**Comment by t3solution** [comment]
Unfortunately I have to tell you the following:
The EXT:**rte_ckeditor_fontawesome** will not be developed further and will not be provided for TYPO3 v13.
The next update of EXT:t3sbootstrap will be provided for TYPO3 **v12 & v13**. 
So with the next update I will completely abandon Fontawesome support.
As a replacement the **EXT:iconpack** should be installed here.
An upgrade wizard will be available in the next update.

**Comment by vmans** [comment]
Thank you for the heads-up, sounds marvelous!
