### ISSUE TITLE
bootstrap.config.compress creates huge amount of identical "t3sbProject-..." files in /typo3temp/assets/compressed

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#43]
When TS setup config.compressCss and / or config.concatenateCss is on then a huge amount of identical "t3sbProject-..." files are created in /typo3temp/assets/compressed 

TYPO3 9.5.19
t3sbootstrap 4.4.8 (upgraded from 4.2.2, no problem there)

What else do you need to know?

**Comment by t3solution** [comment]
INFO: https://www.t3sbootstrap.de/dokumentation/installation
& https://www.t3sbootstrap.de/dokumentation/snippets/css-scss/cdn-local
... did you take this information into account?
Maybe here is your problem!?

**Comment by peerlight** [comment]
bootstrap.cdn.enable = 0 is set in constants

all CSS is "localized" in /fileadmin/T3SB/Resources/Public/CSS

t3sbProject.css in this folder seems to be "updated" with every page hit; other files in this folder have timestamp of the date they were downloaded

didn't get the point of your note: I don't want bootstrap.config.disableDefaultCss = 0 but t3sbProject.css should just stay as it is (and dont't initiate new compress/concat because of new timestamp)

**Comment by t3solution** [comment]
... you are right, here the bugfix:
https://github.com/t3solution/t3sbootstrap/commit/a96a92869cee9e3eeb4c9033b625bf4096a484d7

**Comment by t3solution** [comment]
... and here a better solution:
https://github.com/t3solution/t3sbootstrap/commit/11a151322224e1068e0dca2aea1ee4fa35566c5c

**Comment by peerlight** [comment]
works for me, thank you
