### ISSUE TITLE
Dropdowns do not work

### ISSUE THREAD

**Issue by Psycho0verload** [t3solution/t3sbootstrap#44]
I had the same error as described here
https://stackoverflow.com/questions/60837918/dropdown-js186-uncaught-typeerror-u-is-not-a-constructor-returning-when-i-clic

As it currently looks, specially created DropDown does not work with Popper 2.
In the documentation of bootstrap itself, version 1.16.0 of Popper is used.

So there are two possibilities:
1. change from Popper 2 to 1.16.0
2. switch to the bootstrap.bundle.min.js

**Comment by HenryAveMedi** [comment]
Yes I had the same problem and had to switch to bootstrap.bundle
