### ISSUE TITLE
Breadcrumb background color transparent

### ISSUE THREAD

**Issue by okmiim** [t3solution/t3sbootstrap#46]
`.breadcrumb{background-color:transparent}` was added to the file [Resources/Public/Styles/t3sbootstrap.css](https://github.com/t3solution/t3sbootstrap/blob/d7ac28b555d07f1b33bd11c8b2bd554de34b59f3/Resources/Public/Styles/t3sbootstrap.css#L4) in commit d7ac28b.

I think this should not be part of this file, because it changes the visual appearance and and overwrites the bootstrap default.
This does not fit for all pages and should rather be part of custom styling (e.g. t3sbootstrap.de, where it also seems to be part of additional styling).

**Comment by t3solution** [comment]
You are right, I removed the style from the file in version 4.5.1
