### ISSUE TITLE
Carousel pictures are blurred on desktop displays

### ISSUE THREAD

**Issue by MV-1** [t3solution/t3sbootstrap#47]
Refer to the html page source of https://www.t3sbootstrap.de/dokumentation/komponenten/carousel

Only low resolution images are listed in the <source> tags for the carousel picture gallery. With this a processed max. resolution 1200w blurred image is used on large screens. The <img> tag after that is ignored.

<source srcset="/fileadmin/_processed_/9/b/csm_IMG_0265_f2d22848b9.jpg.webp 125w, 
... 
/fileadmin/_processed_/9/b/csm_IMG_0265_7daccbf4ce.jpg.webp 1200w" media="(min-width: 1200px)" sizes="(min-width: 2600px) 2600px, 100vw" type="image/webp">
<img class="img-fluid lazy loaded" alt="IMG_0265" src="/fileadmin/_processed_/9/b/csm_IMG_0265_5ae5fe0f9a.jpg" data-ll-status="loaded" width="2600">

**Comment by t3solution** [comment]
Maybe you have outsourced a template and have not updated it !?

**Comment by MV-1** [comment]
I'm talking about your page. An upscaled 1200w picture is showed instead of using the original high-resulution picture.

Left as it is, right as it should be:

![carousel](https://user-images.githubusercontent.com/24458448/89384620-9cdd2f80-d6fe-11ea-8c37-716b57356fb5.png)

**Comment by t3solution** [comment]
Thanks for the info, you are right!
I was able to fix the problem by adjusting the following constant:
bootstrap.image.srcsetDesktop = 125, 255, 385, 576, 768, 992, 1200, 1440, 1920, 2650
I will set this setting as default in the next version!
Have a nice day
Beste regards
Helmut
