### ISSUE TITLE
Missing stable version v4.5.* on packagist

### ISSUE THREAD

**Issue by okmiim** [t3solution/t3sbootstrap#49]
The current version on **[packagist](https://packagist.org/packages/t3sbs/t3sbootstrap)** is only available as a dev version (`4.5.0.x-dev`, `4.5.1.x-dev`).

**Comment by t3solution** [comment]
Thanks for the information - I fixed this!

**Comment by okmiim** [comment]
Note: You use multiple naming-conventions for the versions (e.g. `4.4.8`, `v4.5.1` (with **v** prefix)).

**Comment by t3solution** [comment]
I removed the v prefix - should be working now!
