### ISSUE TITLE
.thead-dark in <table> does not go away

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#5]
Hi there.

Why is there a cedille in the code? I guess this statement is never true? 

https://github.com/t3solution/t3sbootstrap/blob/8060b624bc11876c7d4c626c82ba1dc5c5709c92/Classes/DataProcessing/CommaSeparatedValueProcessor.php#L103

I do not see several tables in $processedData['table'] but only one. Iteration will work on rows.

**Comment by t3solution** [comment]
This is just a workaround to use the bootstrap contextual classes in tables.
Info: https://www.t3sbootstrap.de/demo/tabellen

**Comment by TrueType** [comment]
Ah. I did search for some docuvon tables but couldn't find it. That makes it clear.
