### ISSUE TITLE
Multidomain-Multisite Setup

### ISSUE THREAD

**Issue by csguevara** [t3solution/t3sbootstrap#51]
Hello,
is there a way to disable the plugin in a multisite installation on certain root pages in the backend? The specially created backend forms will be overwritten or changed by the t3sboostrap plugin. It also overwrites pages / backend forms where it is not included!

Kind regards!
Chris

**Comment by t3solution** [comment]
Hello Chris,
the following should work:
plugin.tx_t3sbootstrap >
module.tx_t3sbootstrap >
tt_content.list.20.t3sbootstrap_pi1 >
tt_content.module.20.tx_t3sbootstrap >

Cheers
Helmut

**Comment by csguevara** [comment]
Hello Helmut,
thank you very much for your quick answer. Unfortunately the plugin cannot be deactivated with the snipets. It is still loaded in the backend forms.

Kind regards!
Chris
