### ISSUE TITLE
Using forms + scrolling to form doesn't work

### ISSUE THREAD

**Issue by crookoo** [t3solution/t3sbootstrap#52]
Hello Mr. Hackbarth,

I am using TYPO3 10.4.6 and t3sbootstrap 4.5.1 together with the core extension forms.
When I add a simple contact form and press the submit button, after the server validation the page doesn't scroll back to the form.

Here is an example of what I mean: http://p564141.mittwaldserver.info/
Just scroll down to the contact form, fill in some values and press the "Nächter Schritt" button. The page scrolls back to the top and doesn't scroll to the hash in the url (#test-3).

Can you help me with that or is it a bug?

Best regards
Michael

**Comment by t3solution** [comment]
Is fixed!
