### ISSUE TITLE
Lazy load in safari Images not showing when not using webp due to css

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#53]
I've been tinkering for 2 days with a problem i have that lazy images where not being loaded in safari… i don't have webp installed, so i was trying to compare what was happening. when i dectivated the defaultCSS suddenly all pictures where there…… because in safari u use the no-webp class and u set the lazy opacity to 1 eventhough the class loaded is not in the tag……
since i don't have webp EXT installed or configured in my installation, i don't get that class and therefore all my images are set to opacity 0 in safari and other browsers……

any idea how i can solve this preserving the opacity effects but without installing webp? because i'm not yet sure even why the class loaded in safari is not working.

i analyzed this in your https://www.t3sbootstrap.de/dokumentation/komponenten/carousel page in safari, and you have the exact same problem, safari only delivers the class loaded to the 1st slide in carousel, all the others get stuck with class loading, and then no class at all. but because u have the no-webp class on safari, you're not able to see this bug

**Comment by HenryAveMedi** [comment]
For now I basically made a general safari css fix:
``
@media screen and (min-color-index:0) and(-webkit-min-device-pixel-ratio:0) { 
  @media all {
    body img.lazy { opacity: 1 !important;}
  }
}
``

but it is not the best solution because the problem in safari remains in which the js never acknowledges that the img src has been downloaded and therefore never inserts the "loaded" class into the <img>

**Comment by t3solution** [comment]
Hello Henry,
sorry, I'm a bit late but

**Comment by t3solution** [comment]
.. upps - do you know the following:
you can disable it!
# Bugfix for Safari browser if using webp with lazyload
[browser('Safari') && {$bootstrap.extconf.webp} == 1 && {$bootstrap.extconf.lazyLoad} > 0]
page.cssInline {
	124 = TEXT
	124.value = picture img.lazy {opacity:1 !important;}
}
[GLOBAL]

**Comment by t3solution** [comment]
New version 5 - new issues!
