### ISSUE TITLE
Loading ext_tables.php of extension "t3sbootstrap" failed

### ISSUE THREAD

**Issue by notacoder-ui** [t3solution/t3sbootstrap#54]
While checking of Broken Extensions in my typo3 backend it shows :
**Loading ext_tables.php of extension "t3sbootstrap" failed**

Please let me know what is making this error. !

Thanks in advance

**Comment by t3solution** [comment]
... an old version is making this error.
With the current version this issue is fixed!
Cheers
Helmut
