### ISSUE TITLE
Wrong css for equal height columns with more than one element per column

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#55]
When "Equal height" on columns is set, the second element (second div) inside one column is not visible,

This line in the default css
`.row-eq-height .col > div, .row-eq-height [class*="col-"] > div {height:100%!important;}
`
should be changed into this
`.row-eq-height .col, .row-eq-height [class*="col-"]{height:100%!important;}
`
to prevent that (not checked for further consequences).

**Comment by t3solution** [comment]
... which version do you use?
I can't find the "default css"!

**Comment by t3solution** [comment]
... I could find the css in t3sbootstrap.css
https://github.com/t3solution/t3sbootstrap/commit/990836d2b62bd29de559cd3af6e83d0050b22587

**Comment by t3solution** [comment]
New version 5 - new issues!
