### ISSUE TITLE
Console Commands are not compatible with TYPO3 9.5

### ISSUE THREAD

**Issue by okmiim** [t3solution/t3sbootstrap#57]
## Current Behavior
```bash
$ typo3cms t3sbootstrap:cdnToLocal
[ Symfony\Component\Console\Exception\NamespaceNotFoundException ]  
There are no commands defined in the "t3sbootstrap" namespace.
```
Unable use `cdnToLocal` or `customScss` (since they are not available as task anymore).
## Context
- php: 7.2
- typo3: 9.5.21
- t3sbootstrap: 4.5.1

## Reason
The console commands added in 4.5.1 are **not compatible** with TYPO3 9.5.
The command configuration in `Configuration/Services.yaml` was added in v10 (see [feature in changelog](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-89139-AddDependencyInjectionSupportForConsoleCommands.html))

## Possible Solutions

- use `Configuration/Commands.php` (However is deprecated since v10 and will be removed in v11)
- some workaround solution
- raise required typo3 version

**Comment by t3solution** [comment]
Bugfix: 
https://github.com/t3solution/t3sbootstrap/commit/80ab4c26e9eef8e32af372b46c48067c00005e3b
https://github.com/t3solution/t3sbootstrap/commit/d1daa9a52d09fd4fdaef3a059c38797e4ceb12ab
https://github.com/t3solution/t3sbootstrap/commit/5aca9cb496080fb0b5e16698ecdfe96864e2710f
