### ISSUE TITLE
PHP Warning on: Classes/Command/CdnToLocal.php

### ISSUE THREAD

**Issue by Cretection** [t3solution/t3sbootstrap#61]
I get the following error when running the cronjob:

> Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /htdocs/typo3conf/ext/t3sbootstrap/Classes/Command/CdnToLocal.php line 62 

The folder: fileadmin/T3SB/Resources/Public is created and writable.

I have set the following
bootstrap.cdn.enable = 0
bootstrap.cdn.viewportchecker = 1.8.8
bootstrap.cdn.ytPlayer = 3.3.4

Setup:

PHP version: 7.3.8 & 7.4.3
TYPO3 10.4.9

**Comment by t3solution** [comment]
I can't understand that, it works as expected for me!

**Comment by Cretection** [comment]
Mmmmh okay! Then I have to see if I can debug it better

**Comment by Cretection** [comment]
I haven't been able to locate the error yet but on my newly created test system it works without problems
