### ISSUE TITLE
ws_scss causes broken frontend

### ISSUE THREAD

**Issue by Alma1919** [t3solution/t3sbootstrap#62]
Ext. ws_scss causes broken FE if loaded and activated.
Furthermore no scheduler tasks of t3sb can be seen.

Screenshot 1: 
t3 v. 10.4.9 update t3sb v.4.5.0  to 4.5.3 (4.5.0 was working well)

Screenshot 2:
t3 v. 10.4.9 and t3sb v. 4.5.3: WITH activated ws_scss and all options activited in Custom-SCSS (Cerulean -without "Roll your own")

Screenshot 3:
t3 v. 10.4.9 and t3sb v. 4.5.3: WITHOUT ws_scss (deleted) 
![T3SB_4 5 3_Scheduler-Problem](https://user-images.githubusercontent.com/72558119/95466214-64ff9c00-097c-11eb-9ab9-766c998e12e0.png)
![ws_scss_NACH-Aktivierung](https://user-images.githubusercontent.com/72558119/95466268-734db800-097c-11eb-8029-8165e9e7c9d1.png)
![ws_scss_DEAKTIVIERT](https://user-images.githubusercontent.com/72558119/95466306-7f397a00-097c-11eb-95d6-5780ff9119c3.png)

and NONE of all options in Custom-SCSS

**Comment by t3solution** [comment]
As of TYPO3 v10, tasks are located under "Execute console commands".
This information must also be observed: https://www.t3sbootstrap.de/log

**Comment by Alma1919** [comment]
> 
> 
> As of TYPO3 v10, tasks are located under "Execute console commands".
> This information must also be observed: https://www.t3sbootstrap.de/log

Thanks for your answer,
but could you specify this more detailed, please:
1. "Execute console commands".
2. What kind of information in your log? - It's really huge!

**Comment by t3solution** [comment]
1.)
![grafik](https://user-images.githubusercontent.com/5745943/95475169-3b4b7280-0986-11eb-95b8-1d7fab93093b.png)
... task is in the lower selection field
2.)
Wrong versions in constants:
bootstrap.cdn.viewportchecker = 2.0.0
bootstrap.cdn.ytPlayer = 3.4.3
... change to:
bootstrap.cdn.viewportchecker = 1.8.8
bootstrap.cdn.ytPlayer = 3.3.4

**Comment by Alma1919** [comment]
at 1. => I didn't know! Thanks for info!
at 2. => I've read and considered.

Now all is looking well. Thanks!
