### ISSUE TITLE
Bug Viewportchecker

### ISSUE THREAD

**Issue by rimmeh** [t3solution/t3sbootstrap#63]
Hi,
I found a bug with the viewport checker.

***********************************************
```
// viewportChecker for animate.css - page.jsFooterInline.5.3
$ ('.animated') .each (function () {
$ (this) .viewportChecker ({classToAdd: 'bt_visible', classToRemove: 'bt_hidden', offset: 0});
});
```
************************************************** ************

The class "animated SlideInLeft" automatically generates the SlideInLeft running.

Then the animation has already started outside of the viewport and is therefore already ended when you enter the viewport.

It therefore does not work to bind the initialization to the "animated" class.

My temporary Workaround:

```
// viewportChecker for animate.css - page.jsFooterInline.5.3
$ ('.viewMeLeft') .each (function () {
$ (this) .viewportChecker ({classToAdd: 'animated FadeInleft bt_visible', classToRemove: 'opa0', offset: 0});
});
```

Then access this element:
`<div id = "c219" class = "fsc-default ce-textmedia layout-140 viewMeLeft opa0">`

Versions:

T3s: 4.5.3
Viewportchecker: 1.8.8
Animate.css: 3.7.2
Typo3 Core: 10.4.9

Setup TS.
```
## Fix for Viewport Checker with animation
page.jsFooterInline.5.3.value (
    // viewportChecker for animate.css - page.jsFooterInline.5.3
    $ ('.viewMeLeft') .each (function () {
    $ (this) .viewportChecker ({classToAdd: 'animated fadeInLeft', classToRemove: 'opa0', offset: 0});
});
$ ('.viewMeRight') .each (function () {
    $ (this) .viewportChecker ({classToAdd: 'animated fadeInRight', classToRemove: 'opa0', offset: 0});
});
)
```

My suggestion ist to implement a new checkbox in the "apperance" tab of Content Elements like "watch viewport yes/no" and then a new class to which the vc initialisation is binded to.

**Comment by t3solution** [comment]
New version 5 - new issues!
