### ISSUE TITLE
Expression could not be parsed. - {"expression":"page|doktype = 198"}

### ISSUE THREAD

**Issue by bihor** [t3solution/t3sbootstrap#64]
In Version 4.5.3 is an TypoScript expression that does not work:
Tue, 13 Oct 2020 11:57:31 +0200 [ERROR] request="78c8fae94d139" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"page|doktype = 198"}

It is in 
typo3conf/ext/t3sbootstrap/Configuration/TSConfig/Page.tsconfig
Maybe it should be this way:
[page["doktype"] == 198]

May

**Comment by t3solution** [comment]
New version 5 - new issues!
