### ISSUE TITLE
Classes aren't appended

### ISSUE THREAD

**Issue by baenschplus** [t3solution/t3sbootstrap#67]
So i am in an blank Typo3 10.4.9 trying to add "container" in "Appearance" Section or an Fontawesome icon to the menu. But none of that ist appended to the frontend.

Back in my Typo3 9 Pages everything worked well, so I don't know where my the fault could be. 

is it mandatory to do the t3sb config to use the components? in typo3 9 I didn't do this as well but everything worked fine.

only other extension used ist grid elements

**Comment by t3solution** [comment]
For me it works as expected!
... can you explain what you exactly mean by:
is it mandatory to do the t3sb config to use the components?

**Comment by t3solution** [comment]
New version 5 - new issues!
