### ISSUE TITLE
Error after running task to localize Cdn-Files (v4.5.3)

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#68]
with a fresh instants of TYPO3 10.4.9/t3sbootstrap 4.5.3 i get the message  **trpos() expects parameter 1 to be string, boolean given**  from scheduler
constants adopted to 
bootstrap.cdn.viewportchecker = 1.8.8,  
bootstrap.cdn.ytPlayer = 3.3.4
as described.

after running the task, i found these files in fileadmin/T3SB/Resources/Public/

- CSS
animate.min.css
baguetteBox.min.css
bootstrap.min.css
cookieconsent.min.css
ekko-lightbox.css
highlight.a11y-light.min.css
highlight.default.min.css
lightcase.css
t3sbProject.css

- fonts
lightcase.eot
lightcase.svg
lightcase.ttf
lightcase.woff

- JS
baguetteBox.min.js
bootstrap.min.js
cookieconsent.min.js
ekko-lightbox.min.js
fontawesome.min.js
highlight.min.js
highlight.php.min.js
jquery.easing.min.js
jquery.min.js
jquery.viewportchecker.min.js
lazyload.min.js
lightcase.min.js
picturefill.min.js
popper.js

**Comment by t3solution** [comment]
Here is the bugfix: https://github.com/t3solution/t3sbootstrap/commit/964b2760d8c1956f94a936515098a69bf9a4aeb6
and here the Info:https://www.t3sbootstrap.de/log

**Comment by wini2** [comment]
thanks a lot for your hint,

but that's what i thought i did. 

interestingly i commentent the original version 
	# cat=bootstrap-cdn/b-version/47; type=small; label=YouTube player - jquery.mb.YTPlayer:		
        #vgl. github.com/t3solution/t3sbootstrap/commit/964b2760d8c1956f94a936515098a69bf9a4aeb6
	#ytPlayer = 3.4.3
       ytPlayer = 3.4.3

and it didn't work. after the deletion of my comments it works.

disturbing thing.
