### ISSUE TITLE
Lazy load not working properly

### ISSUE THREAD

**Issue by HenryAveMedi** [t3solution/t3sbootstrap#69]
according to google speed test, images are not being lazy loaded
<img width="745" alt="image" src="https://user-images.githubusercontent.com/51093175/96928503-e85ed880-14b8-11eb-9002-2061293d7951.png">

so, I was researching a little bit, because since a few updates ago i had the safari problem I posted about, and was reading the lazy load documentation.

according to them, in the current version (17.1.0) which is the one you are using in the current t3sbootstrap, the html attributes being used have a `data-` preppend
<img width="561" alt="image" src="https://user-images.githubusercontent.com/51093175/96928711-47bce880-14b9-11eb-8726-f37031777099.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/51093175/96929264-26a8c780-14ba-11eb-8154-52f8a86d06fb.png">
`data-srcset`, `data-src` and in webp additional `data-sizes`
in your extension you use only srcset and media attributes
I was trying to find a template were to change the build up of your tags and test this, but was unable to find it.

Maybe taking a look at this could solve some of the lazyload problems including the safari one?

**Comment by t3solution** [comment]
Hello Henry,
maybe I found a solution for this problem!?
You can try to uncomment the line 226 in ResponsiveImagesUtility.php

**Comment by HenryAveMedi** [comment]
the html rendering doesn't seem to have changed, but the google speedtest doesn't seem to scream anymore

**Comment by HenryAveMedi** [comment]
and it seems to have solved the safari problem as well, so, i can get rid of the fix and get the fading effect back on

**Comment by t3solution** [comment]
New version 5 - new issues!
