### ISSUE TITLE
about Extensions sources handling

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#7]
hi,
the configuration in EXT:t3sbootstrap resembles pretty much what would be done within a site package extension. Of course. For us, we found the convention to have a single 
```
/ext/t3sbootstrap/
      /Extensions/
```
folder within the site package.
And within - followed by the conventions regarding non-capital extension names - the extensions:
```
/Extensions/
    /news/
    /form/
```
And within such the known extension folder conventions
```/news/
     /Configuration/
          /TCA/
     /Resources/
     /...
```
This has the advantage to find all adjustments in a single place and to make comparisons with the original values easier.

**Comment by t3solution** [comment]
For the next TYPO3 v10 compatible version I will consider your suggestion.

**Comment by t3solution** [comment]
Is done with v4.4.5
