### ISSUE TITLE
Flexforms get overwritten by "Modify Flexform" if there is no Modification specified yet.

### ISSUE THREAD

**Issue by Salandora** [t3solution/t3sbootstrap#71]
As stated in the title if you enable "Modify Flexform" but have no Flexform modifications just yet and edit e.g. a button you won't get the options under "Appearance".

After looking into that issue further I found out that in https://github.com/t3solution/t3sbootstrap/blob/6203d36cf56d7628c04369bf0b5e4b6e93265a81/Classes/Backend/FormDataProvider/FlexFormManipulation.php#L172
Is erasing the 'ds' entry if line number 42 is false, because $dataStructure is never set in that case.
To fix this issue line 172 needs to be moved into the if block.

**Comment by t3solution** [comment]
New version 5 - new issues!
