### ISSUE TITLE
Unnecessary DB request for each main menu item

### ISSUE THREAD

**Issue by okmiim** [t3solution/t3sbootstrap#72]
## Problem
Many database request to the `tx_t3sbootstrap_domain_model_config` table, `count > 2 * amount of pages`.
```SQL
SELECT * FROM `tx_t3sbootstrap_domain_model_config` WHERE `uid` = :dcValue1 
```
You can find this information in the `admin panel` under `Debug` and `Query Information` (Note: with `No caching` enabled or first page load).

## Cause
The main MenuProcessor uses configurations fields from the database.

https://github.com/t3solution/t3sbootstrap/blob/d2ab42c30dfb0c9cbabf8b05d2c0dfd76b57f543/Configuration/TypoScript/Page/Template.typoscript#L80-L100

The two options `entryLevel` and `excludeUidList` seem to be requested for each menu entry.
So this creates a ton of unnessesary / duplicate database requests, especially for bigger websites.

## Testes on 
- Typo3 10.4.9
- t3sboostrap 4.5.3

**Comment by t3solution** [comment]
I could fixed this problem with the new version 4.5.4
More info: https://www.t3sbootstrap.de/log

**Comment by peerlight** [comment]
We have an own site package extension and some sites in one TYPO3 installation.

We use TS to ensure same values for sites without having to click each fiedl in DB-Config by  
```
#-------------------------------------------------------------------------------
#	override values of T3SB Config records
#-------------------------------------------------------------------------------
bootstrap.config { ...
```
Afterwards this is partially modified using `[site("identifier") == "..."]` conditions

Now I see TS using `{$bootstrap.db. ...`

How does this influence config overrides by TS and whats the way to go in future setups?

**Comment by t3solution** [comment]
The configuration in the BE module (db) results in outsourced constants (t3sbconstants-x.typoscript).
Path: fileadmin/T3SB/Configuration/TypoScript/t3sbconstants-x.typoscript
This file is imported into the constants:
@import 'fileadmin/T3SB/Configuration/TypoScript/t3sbconstants-x.typoscript'

After this line you can overwrite the constants if necessary.
Example: 
bootstrap.db.navbar_enable = dark
bootstrap.db.navbar_color = info

To do: Update documentation

**Comment by t3solution** [comment]
Should be fixed with the current version!?
