### ISSUE TITLE
'backgroundImageSlide' does not work

### ISSUE THREAD

**Issue by Cretection** [t3solution/t3sbootstrap#73]
I can reproduce this problem on several pages. If I set the variable in the constants, or directly in the Typoscipt, the image is not inherited.

On the bottom page (without a set image) is no image in the background.

**Comment by t3solution** [comment]
Here is the bugfix: https://github.com/t3solution/t3sbootstrap/commit/9996405fc882793743fb3121d2a51eceac73d078

**Comment by Psycho0verload** [comment]
Perfect, I'll test it later

**Comment by Cretection** [comment]
Thank you - I will test it later
