### ISSUE TITLE
Copying a Card element gives an error and weird result

### ISSUE THREAD

**Issue by vmans** [t3solution/t3sbootstrap#74]
I wanted to copy & paste a card element (within a gridelements Card Wrapper).

Two things.

First, an "Ooops":
Data structure file /../typo3conf/ext/t3sbootstrap/Configuration/FlexForms/Grid.xml could not be resolved to an existing file  | RuntimeException thrown in file /../typo3/sysext/core/Classes/Configuration/FlexForm/FlexFormTools.php in line 688.

Second:
The card to copy contains one image (mediafile). After the error the original card contains three copies of this image.

**Comment by t3solution** [comment]
I can not comprehend that and there is no Grid.xml file.
The problem must be found in your installation.

**Comment by vmans** [comment]
The Grid.xml doesn't exist in the master either here on Github.
