### ISSUE TITLE
error executing scheduler task cdnlocal

### ISSUE THREAD

**Issue by joka123** [t3solution/t3sbootstrap#79]
trying to execute the scheduler task for cdnlocal throws the error
Execution of task "Execute console commands (scheduler)" failed with the following message: PHP Warning: Invalid argument supplied for foreach() in xxxx/typo3conf/ext/t3sbootstrap/Classes/Command/CdnToLocal.php line 62
this means the settings are empty but why?
it's an typo3 10 composer installation

**Comment by t3solution** [comment]
You should check whether the following values ​​are set in the constant editor:
bootstrap.cdn.viewportchecker = 1.8.8
bootstrap.cdn.ytPlayer = 3.3.4
Which version is in use?

**Comment by joka123** [comment]
my constants are correct
i use version 4.5.4

**Comment by t3solution** [comment]
On my installation (same config) it works as expected!
Sorry, but you have to look for the bug in your installation.
Maybe you overwrite the constants somewhere?

**Comment by joka123** [comment]
I have found the problem. i had create the scheduler entry before the last update of t3sbootstrap but never executed. after i have deleted the task and create a new one every thing is fine. sorry for wasting your time.
