### ISSUE TITLE
3 Bugs in Version 4.5.4

### ISSUE THREAD

**Issue by bihor** [t3solution/t3sbootstrap#83]
Die Version 4.4.8 läuft bei mir ohne Probleme, aber bei Version 4.5.4 läuft bei mir folgendes nicht:
- bei "Edit Config" ist der oberste Punkt "General settings" falsch verlinkt! Es geht immer das Tab "Meta Navigation" auf.
- im Partial Sub.html schlägt die if-condition item.children immer fehl. Es werden keine tieferen Menüebenen mehr angezeigt.
- im Partial Jumbotron.html wird kein Bild mehr angezeigt.
Nichts im Changelog kann diese Punkt erklären, oder?

**Comment by t3solution** [comment]
The current version is 4.5.5 - please use this one!

**Comment by bihor** [comment]
Version 4.5.5 does not run anymore with TYPO3 9 thats why I can't use it...

**Comment by t3solution** [comment]
... change href="#collapseMeta"
to: href="#collapseGeneral"

**Comment by bihor** [comment]
Thanks for the hint.
I don't need a bugfix, because I will stay at version 4.4.8.
I am very happy with that version...
I only wanted to inform you about the 3 problems.
