### ISSUE TITLE
Issues with container

### ISSUE THREAD

**Issue by wayheyha** [t3solution/t3sbootstrap#85]
Hello t3sb-team,

i fresh installed  v 4.5.5 today.. followed the instructions and everything seems to be working fine, exept the container.
Odd things happen with them in my installation:

- flexContainer-Settings are ignored (no css class indicating d-flex / d-inline-flex are added)
- div with configuration is wrapped inside a div with same configuration:
- example container-configuration: tx_t3sbootstrap_container=[container], tx_t3sbootstrap_padding_sides = [y], tx_t3sbootstrap_padding_size= [3], tx_t3sbootstrap_contextcolor = [warning]
results in: 
`<div class="container"><div id="c15" class="py-3 bg-warning"><div class="py-3 bg-warning"></div></div></div>`

I am not sure if i am the only one that encounters this behavior.

Best regards,
Chris

**Comment by t3solution** [comment]
I cannot reproduce the problem and have never heard of it.
Probably the problem is with your installation!
