### ISSUE TITLE
Error when disableing language glov fav icon

### ISSUE THREAD

**Issue by millemedia** [t3solution/t3sbootstrap#86]
When I want to disable the globe fav icon in config I get an error: 
An exception occurred while executing 'UPDATE `tx_t3sbootstrap_domain_model_config` SET `navbar_langmenu` = ?, `lang_menu_with_fa_icon` = ?, `tstamp` = ? WHERE `uid` = ?' with params [1, "", 1613465799, 1]: Incorrect integer value: '' for column `dev_skyfld`.`tx_t3sbootstrap_domain_model_config`.`lang_menu_with_fa_icon` at row 1

Best regards
Andreas

**Comment by t3solution** [comment]
I cannot reproduce the bug!
BTW: The column dev_skyfld is not from t3sbootstrap
