### ISSUE TITLE
add style everywhere tx_t3sbootstrap_extra_class is used

### ISSUE THREAD

**Issue by wini2** [t3solution/t3sbootstrap#87]
hello,

I need a little help to solve the following problem: 

I heavily use the Bootstrap Utilities - Extra Class field (realy helpfull although i'm abusing it for non-bs classes).  In many cases it's a little laborious to create classe only used once, so I made a little extension (my first one) for additional style-attributes. Because the tx_t3sbootstrap_extra_class field is widely used, I need a hint how to add it without modifiying each template/partial. 

It would be easy for an additional class by modifiying the ClassHelper.php-file ($class .= $data['tx_myExtField'] ? ' '.$data['tx_myExtField'] : '';), but I could not find a way for my style in the StyleHelper.php. 

Thanks for your help

**Comment by t3solution** [comment]
You will find the a new option in the EM config to activate "Add Style" to any CE.

**Comment by wini2** [comment]
At a first glance - it seems to work as wanted.  Helmut, you're a real hero ;-) 

Thanx a million
