### ISSUE TITLE
bootstrap.config.navbarHover and bootstrap.config.navbarClickableparent do not work anymore?

### ISSUE THREAD

**Issue by FinMike** [t3solution/t3sbootstrap#88]
I have seen both of them running as expected last in version 4.3.4 - is this intentional? Why?

It was then possible to hover over a nav-item with a dropdown to show the dropdown. On a click on the nav-item, the page it represents would have opened. Nowadays, one has to click on the nav-item to open the dropdown, but it's not possible to open the page of the nav-item itself anymore. 

However, both options are still offered in the panel "Navbar - Various Settings" of the backend module. 

If this change is intentional, there would be ramifications for the page structure of the sites using the extension. 

Best regards, 

Michael

**Comment by t3solution** [comment]
I can't confirm the behavior you describe here. For me it works as expected..
Probably there is a JS conflict in your installation.

**Comment by FinMike** [comment]
Sorry for the delay, and thanks for the confirmation that it should work.  I needed some time to check for JS conflicts in my installation, and I made sure there are none. Nevertheless, the problem is still on.

In my last working installation, I had TYPO3 v9.5.11 with
- t3sbootstrap v 4.3.4 
- jQuery 3.4.1
- bootstrap 4.3.1

generating HTML code for a dropdown Menu item like 
```
<li id="nav-item-8" class="nav-item dropdown">
<a class="nav-link dropdown-toggle" id="dropdown-menu-8" href="/lieferprogramm.html" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		Lieferprogramm
</a>
<div class="dropdown-menu" aria-labelledby="dropdown-menu-8" style="display: none;">
       <a href="/lieferprogramm/agco-power-sisu-diesel-valmet.html" target="_self" class="dropdown-item dropdown-item-24">
	 	AGCO Power | Sisu Diesel | Valmet
       </a>
       <a href="/lieferprogramm/scania-saab-scania-scania-vabis.html" target="_self" class="dropdown-item dropdown-item-23">
		SCANIA | Saab-Scania | Scania-Vabis
	</a>
</div>
</li>
```
DOM2 and jQuery events for mouseover and mouseout were linked to <li class="nav-item dropdown">.


The problem occurs using TYPO3 10.4.13 with
- t3sbootstrap v 4.5.5
- jQuery v3.4.1
- bootstrap v4.5.3

generating HTML code for a dropdown Menu item like 
```
<li id="nav-item-24" class="nav-item dropup">
<a class="nav-link dropdown-toggle" id="dropdown-menu-24" href="/requests.html" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	requested items
</a>
<div class="dropdown-menu" aria-labelledby="dropdown-menu-24">
<a href="/requests/register.html" target="_self" class="dropdown-item dropdown-item-28">
	register as customer
</a>
<a href="/requests/guests.html" target="_self" class="dropdown-item dropdown-item-29">
	guest access
</a>
</div>
</li>
```
Here now, jQuery events for click and keydown are on  <a class="dropdown-toggle">. 

I'd be very glad for your advise. 

Best regards,

Michael

**Comment by FinMike** [comment]
Meanwhile, i do understand it's by design of bootstrap:
https://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/

Anyway, I still like the behaviour of the old versions of t3sbootstrap, as explained above. I appreciate that there are still the options to choose from in the menu of newer versions. I'd love it if they could still work as expected. They do not now. 

I would greatly appreciate some advise on this topic as well. 

Best regards, 
Michael

**Comment by t3solution** [comment]
Are you sure you have activated "Clickable parent" in the BE module?

**Comment by FinMike** [comment]
That was one of my first thoughts. Be sure I have. 

Best regards, 

Michael

**Comment by t3solution** [comment]
Iss there any JS error in the console?

**Comment by FinMike** [comment]
Console shows javascript being loaded in this order:
fileadmin/T3SB/Resources/Public/JS/jquery.min.js?1615126337[HTTP/1.1 304 Not Modified 3ms]
fileadmin/T3SB/Resources/Public/JS/popper.js?1615126337[HTTP/1.1 304 Not Modified 31ms]
fileadmin/T3SB/Resources/Public/JS/bootstrap.min.js?1615126337[HTTP/1.1 304 Not Modified 28ms]
fileadmin/T3SB/Resources/Public/JS/jquery.easing.min.js?1615126337[HTTP/1.1 304 Not Modified 28ms]

but nothing happens on hover or on click. No errors. 

Best regards,

Michael

**Comment by t3solution** [comment]
If the site is online, you can give me admin access, then I'll see, what I can do!

**Comment by FinMike** [comment]
Thank you so much. I'll have to set the site up on my staging server, as it is in development locally here. I can get to that on the upcoming weekend. I'll get back to you by mail then. 

Best regards,

Michael

**Comment by FinMike** [comment]
Hi, thank you ever so much for your Mails - you really helped. 
I think we can close this issue. 

Best regards, Michael
