### ISSUE TITLE
Upgrade Wizard constants to database 4.5.4 -> 4.5.5 crashes

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#89]
executing the Upgrade Wizard constants to database 4.5.4 -> 4.5.5 crashes with this error
```
(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Warning: Invalid argument supplied for foreach() 
in /home/www/dev1/html/cms/typo3conf/ext/t3sbootstrap/Classes/Updates/t3sbConstantsUpdateWizard.php line 203 
in /home/www/dev1/html/typo3_src-10.4.13/typo3/sysext/core/Classes/Error/ErrorHandler.php line 130
```
This is a multisite installation with about a dozen sites.

How to debug this?

How to get the wizard back for excution? Constant bootstrap.wizardsMarkedUndone = 1 is set. But Backend Module is not accessible due to "Return value of T3SBS\T3sbootstrap\Controller\ConfigController::getCustomScss() must be of the type array, null returned"

we are on 
PHP 7.3.26
TYPO3 10.4.13

**Comment by t3solution** [comment]
@How to debug this?
You can debug in the ConfigController and open the BE-Modul!

**Comment by t3solution** [comment]
New version 5 - new issues!
