### ISSUE TITLE
have EXT:news integration optional?

### ISSUE THREAD

**Issue by TrueType** [t3solution/t3sbootstrap#9]
As I see it, the integration with EXT:news is quite hardcoded in ext_localconf.php around line 103. Would it be possible to make it optional? Right now I find myself in a situation where to build a news system and I am asking myself what would be better - to use the EXT:t3sbootstrap integrated version, which is an override of a specific version and which I have to again override myself in a not too easy folder structure - or fall back on the EXT:news templates, where I might be closer to EXT:news, but miss some usefull/necessary adjustments made by EXT:t3sbootstrap?

**Comment by t3solution** [comment]
You can use the following to avoid the default settings for EXT:news:
Constant:
bootstrap.ext.news = 0
Setup:
bootstrap.ext.news >

**Comment by t3solution** [comment]
The integration of some news templates adapted for bootstrap is now optional. Setting in EM config.

**Comment by t3solution** [comment]
improvement was implemented
https://github.com/t3solution/t3sbootstrap/commit/607671fe1174e30783527ad470125dec6ad2a9c8
https://github.com/t3solution/t3sbootstrap/commit/067e4efb9a8602063effbfe598b9e93b638ddeae
