### ISSUE TITLE
Custom-SCSS 

### ISSUE THREAD

**Issue by twixwix** [t3solution/t3sbootstrap#90]
First I have to say it is a clean install (typo3 10.4.13). When I want so run the scheduler there is no Task available in the scheduler.
Is there a way to do it by hand?

**Comment by t3solution** [comment]
... you can find the scheduler as following:
Create a new Task:
Execute console commands -> scroll down to Schedulable Command -> select

**Comment by twixwix** [comment]
Thanks a lot for the answer :-)
