### ISSUE TITLE
Upgrade 4.5.4 -> 4.5.5: written t3sbconstants.typoscript empty

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#92]
Hi,

after saving T3SB Config in BE module the file fileadmin/T3SB/Configuration/TypoScript/t3sbconstants.typoscript is written empty. 

So no constants are available for inclusion in last line of /Configuration/TypoScript/constants.typoscript

This leads to settings.config.uid => '{$bootstrap.config.uid}' and "The main configuration has to be created first on the root page." in FE

We have an updated  T3SB Config in DB, root page is located in a folder.

As this is a multi site system there is another T3SB Config in DB, with another root page in another folder. Saving this one OVERWRITES fileadmin/T3SB/Configuration/TypoScript/t3sbconstants.typoscript with another empty file. t3sbconstants-xxx.typoscript files from older versions stay untouched.

So
- Why is fileadmin/T3SB/Configuration/TypoScript/t3sbconstants.typoscript empty?
- How sholud this work in a multi site setup?

**Comment by t3solution** [comment]
I can't understand how it can come to an empty t3sbconstants.typoscript file. The problem should be i your installation.
BTW: In the current version only one t3sbconstants.typoscript file is needed, because i use constants within the file.
@ Multidomain
Only if SCSS is used without CDW, the following notes must be observed:
https://www.t3sbootstrap.de/dokumentation/snippets/css-scss/custom-scss#c473

**Comment by t3solution** [comment]
... sorry, not CDW - it should be CDN

**Comment by peerlight** [comment]
Thanks for the clarification regarding t3sbconstants.typoscript

Will investigate further ...

There are working custom-variables-....scss in /uploads/tx_t3sbootstrap/ - so this should not be a problem

**Comment by peerlight** [comment]
I can reproduce it as follows:

create new 
- page in root (0) and set it as siteroot
- root template with t3sbootstrap
- T3SB Config in module
=> DB looks fine and t3sbconstants.typoscript is written with values

create new folder in root (0), move formerly created page into it, go to module and save unchanged  T3SB Config
=> DB ok but t3sbconstants.typoscript is written EMPTY

**Comment by peerlight** [comment]
possible workaround?

as this is an upgrade project with constants in an own sitepackage extension for some identically configured sites i am thinking about skipping the inlining, upgrading to db and writing to t3sbconstants.typoscript process

so i would just go with a complete set of default constants and have site specific changes in conditions.

nearly the same like before but without loading constants from Configuration/TypoScript/constants.typoscript

**Comment by at-ac** [comment]
Hi,
I have the same issue with empty file after upgrading the extension on a website we currently create.

My first workaround was a completely fresh TYPO3 installation (10.4.16) with latest EXT version (4.5.6) and export/import pages, contents etc.

Now the website is ready for launch and I copied it into customers account (same server) and run into the issue again. When I change a setting and click the "Save" button an empty file results and FE is broken: "The main configuration has to be created first on the root page."

Then I investigated with my friend (credits to chrissie ^ x-tra-designs) and we came to this point:

File t3sbootstrap/Classes/Controller/ConfigController.php
around Line 590
```
		if ( count($rootTemplates) ) {
			$filecontent = '';
			foreach ($rootTemplates as $key=>$rootTemplate) {
				foreach ( $this->configRepository->findAll() as $config ) {
					$rootLineArray = GeneralUtility::makeInstance(RootlineUtility::class, $config->getPid())->get();
					if ( $config->getPid() == $rootTemplate['pid'] ) {

						if ( count($rootTemplates) == 1 ) {
							$filecontent .= self::getConstants($config, TRUE).PHP_EOL;
						} else {

							//$filecontent .= 'REACHED';					// chrissie
							//$filecontent .= PHP_EOL . "UID:" .$rootLineArray[0]['uid'];	// chrissie uid is 2
							//$filecontent .= PHP_EOL . "PID:" .$rootTemplate['pid'];	// chrissie pid is 1
							$rootLineArray[0]['uid'] = 1;					// chrissie hack for at-ac: was 2, did not work, why?

							if ($rootLineArray[0]['uid'] == $rootTemplate['pid'] ){
								$filecontent .= '['.$rootTemplate['pid'].' in tree.rootLineIds]'.PHP_EOL;
								$filecontent .= self::getConstants($config, TRUE);
								$filecontent .= '[END]'.PHP_EOL.PHP_EOL;
							}
						}
					} else {
						if ( count($rootTemplates) == 1 ) {
							if ($rootLineArray[0]['uid'] == $rootTemplate['pid'] ){
								if ($config->getGeneralRootline() || $config->getNavbarMegamenu()) {
									$filecontent .= '['.$config->getPid().' in tree.rootLineIds]'.PHP_EOL;
								} else {
									$filecontent .= '[page["uid"] == '.$config->getPid().']'.PHP_EOL;
								}
								$filecontent .= self::getConstants($config, FALSE);
								$filecontent .= '[END]'.PHP_EOL.PHP_EOL;
							}
						} else 
```
For any reason the uid was "2" and the file was empty (I have only one configuration in the page tree, maybe I deleted one in the development process, not sure).
If we set $rootLineArray[0]['uid'] = 1 everything works as expected.

I hope this can help to improve this great extension!

**Comment by at-ac** [comment]
I think, I could now figure out where $rootLineArray[0]['uid'] = 2 comes from:
A teammate (is Admin) created a copy of the root page (siteroot) containing the T3SB config. This leads to a new config which was not written to database and not displayed in "Pages with T3SB Configuration".

Deleting this configuration on the new page via T3SB-Modul did not solve the problem.
Deleting the new page did -> constants were written to file again.
Copy the root page as an editor (no rights for [tx_t3sbootstrap_domain_model_config]) is no problem.

**Comment by chris-x-tra** [comment]
Even if you cannot reproduce the problem, it is easy to see: if the code reaches this case:
```
if ( count($rootTemplates) == 1 ) {
...
} else {
... reached here
```

and this condition does not match, which is obviously the case in our scenario
`
if ($rootLineArray[0]['uid'] == $rootTemplate['pid'] ){
`
then there will get a empty config file written out. The user gets no notice about this error, which drives him nuts and bolts.

Regards,
Chirs

**Comment by t3solution** [comment]
New version 5 - new issues!
