### ISSUE TITLE
EXT:t3sbootstrap/Resources/Public/Contrib/Bootstrap is missing

### ISSUE THREAD

**Issue by Slartibartvic** [t3solution/t3sbootstrap#93]
In _t3sbootstrap/Configuration/TypoScript/Page/IncludeBootstrapScss.typoscript_ there's an automatic include of the bootstrap SCSS files, if ws_scss is activated - however those files don't seem to be included anymore in the extension.

A possible solution would be to either:

- include the bootstrap SCSS files, or
- rewrite the includes so that the SCSS is only loaded if you decide to roll your own

**Comment by t3solution** [comment]
New version 5 - new issues!
