### ISSUE TITLE
copy element and paste as reference not available

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#94]
T3 10.4.13 / T3SB 4.5.5
![copy-paste-reference](https://user-images.githubusercontent.com/47745128/110913456-79720700-8315-11eb-976a-05c2dea970fe.png)

**Comment by t3solution** [comment]
The same behavior in a virgin (without t3sbootstrap) installation (v10.4.13)!

**Comment by CarstenHager** [comment]
You can use this EXT.


https://extensions.typo3.org/extension/paste_reference

**Comment by asche76** [comment]
thank you
