### ISSUE TITLE
Duplicate 'clearfix' class collides with contentMarginTop in 'in Text' images

### ISSUE THREAD

**Issue by felepp** [t3solution/t3sbootstrap#95]
Using 'in Text' media generates the `clearfix` class twice on the content element and when using the global contentMarginTop it looks like this

`clearfixmt-5 clearfix`

I have temporarily fixed this by adding a space in the `BootstrapProcessor.php`, but I'm not sure where the first `clearfix` is coming from, so there is probably a problem somewhere else.

**Comment by t3solution** [comment]
Which version is in use?
I cannot reproduce the problem.

**Comment by t3solution** [comment]
New version 5 - new issues!
