### ISSUE TITLE
content element - flexform container class is not respected in frontend output

### ISSUE THREAD

**Issue by asche76** [t3solution/t3sbootstrap#96]
![ce-no-container-class-frontend](https://user-images.githubusercontent.com/47745128/110962695-86ace700-8351-11eb-8e59-0fc243ded9d1.png)

**Comment by t3solution** [comment]
You probably have set up a .container for the page.
In this case the .container is not created in the CE. This prevents nested .containers.
If you still need a .container, then you can use the CE container.

**Comment by asche76** [comment]
ok got it, even container-fluid px-o is not allowed in page properties - thank you
