### ISSUE TITLE
Javascript bug in Private/Partials/Page/Assets.html

### ISSUE THREAD

**Issue by bibusdax** [t3solution/t3sbootstrap#98]
var offsetSize = {settings.config.sectionmenuAnchorOffset};
and
var scrollspyOffset = {settings.config.sectionmenuScrollspyOffset};

are not working and cause error messages.

My quick solution was to set offsetSize and scrollspyOffset to 0.

**Comment by t3solution** [comment]
New version 5 - new issues!
