### ISSUE TITLE
no BG image shown when screen larger than 2560

### ISSUE THREAD

**Issue by peerlight** [t3solution/t3sbootstrap#99]
BG images in jumbotron or backgroundwrapper are not shown when width of browser window exceeds 2560. Inline CSS for images is missing a default that is always shown:

```
@media (max-width: 2560px) {
    #s10677 {  background-image: url("/fileadmin/bilder/original-file.jpg"); }
}
```

**Comment by peerlight** [comment]
the $mediaQueries defined in BackgroundImageUtility.php line 138 are ok 

but in line 156 they are all written with `max-width`

`$css .= '@media (max-width: '.$querie.'px) {';`

this should be reworked to have no upper limit otherwise there is no image at all above the last `max-width`

so just use the last `max-with` for a `min-width` query?

**Comment by t3solution** [comment]
... the best and easiest solution -> modify constant:
bootstrap.image.bgMediaQueries = **2900**, 2560, 1920, 1200, 992, 768, 576

**Comment by peerlight** [comment]
I would not call this "solution" as it just shifts the upper limit

Besides that thank your for making bgMediaQueries available via constants.

Had already fixed it directly in BackgroundImageUtility.php

Better way would be to extract largest value from array and use it for a `min-width` definition or completely rewrite to using `min-width` (needs $cropVariant = 'mobile'; as default) like in other image outputs

**Comment by t3solution** [comment]
The problem with your solution is this:
The bgMediaQueries are used for rendering. If you now use the min-width definition, the images will be output in a poor resolution.

**Comment by t3solution** [comment]
... you can set the largest possible screen width (bold):
bootstrap.image.bgMediaQueries = **2900**, 2560, 1920, 1200, 992, 768, 576

**Comment by quadronet** [comment]
bootstrap.image.bgMediaQueries = 5500, 3500, 2560, 1920, 1200, 992, 768, 576

is without any solution....

**Comment by t3solution** [comment]
... in what context does it not work?

New Test:
Here my setting in CONSTANTS: `bootstrap.image.bgMediaQueries = 2900, 2560, 1920, 1200, 992, 768, 576`
Result:
![grafik](https://user-images.githubusercontent.com/5745943/131305077-6e7ca6b9-4d0f-46b9-b38c-91b0f2b66d50.png)

For me it is working as expected!

**Comment by quadronet** [comment]
With the background-wrapper. Here you can see this: https://diele.1qn.de/, over 2560px no background-image is shown. 

Second question, where is the padding set for the section? : 
<section id="s6" class=" background-image bgImageSize" **style=" padding: 10rem 1rem;filter: opacity(100%);"**><div id="c7"><header class="header-7 h-1 text-center"><h1 class=" display-1">

**Comment by t3solution** [comment]
BUGFIX in 3 files "BUGFIX: Media Queries for BG-wrapper":
https://github.com/t3solution/t3sbootstrap/commits/master

**Comment by t3solution** [comment]
... your second question - here the answer:
You have to disable "Enable content overlay and autoheight for background-image"
or use "Surcharge height to background-image"

**Comment by t3solution** [comment]
New version 5 - new issues!
